In previous notebook, add cell type assignments to info table, then don't need the metadata table save.

In [1]:
library(BSgenome.Hsapiens.UCSC.hg38)
library(patchwork)
library(readr)
library(stringr)
library(dplyr)
set.seed(1234)

#### Send to channel code
library(parallel)
library(plyr)
library(ggpubr)
library(car)
library(qvalue)

library(pheatmap)
library(RColorBrewer)
library(beeswarm)

Loading required package: BSgenome

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: GenomicRanges

Loading required package: Biostrings

Loading required package: XVector


Attaching package: ‘Biostrings’


The following object is masked from ‘package:base’:

    strsplit


Loading required package: rtracklayer


Attaching package: ‘dplyr’


The following objects are masked from ‘package:Biostrings’:

    collapse, intersect, setdiff, setequal, union


The following object is masked from ‘package:XVector’:

    slice


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


------------------------------------------------------------------------------

You have loaded plyr after dplyr - this is likely to cause problems.
If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
library(plyr); library(dplyr)

------------------------------------------------------------------------------


Attaching package: ‘plyr’


The following objects are masked from ‘package:dplyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize


The following object is masked from ‘package:XVector’:

    compact


The following object is masked from ‘package:IRanges’:

    desc


The following object is masked from ‘package:S4Vectors’:

    rename


Loading required package: ggplot2


Attaching package: ‘ggpubr’


The following object is masked from ‘package:plyr’:

    mutate


Loading required package: carData


Attaching package: ‘car’


The following object is masked from ‘package:dplyr’:

    recode

In [2]:
in_dir <- '/nfs/lab/welison/multiome/chromvar/240209_ChromVar_Outputs/'

#Load in devscores, info, motif
motifdata <- read.table(file=paste0(in_dir,'motifdata.txt'), sep="\t")
info <- read.table(file=paste0(in_dir,'info_table.txt'))
TFClass_Lookup <- read_csv("/nfs/lab/welison/References/220907_WE_Chromvar_to_Gene_By_Subfam_Complete(JAPRAR2022_TFClass).csv")
TFClass_Full <- read_csv("/nfs/lab/welison/References/220907_WE_Chromvar_to_Gene_Jaspar2022.csv")
variability <- read.table(file=paste0(in_dir,'variability.txt'), sep="\t")

head(motifdata)
head(info)
dim(TFClass_Lookup)
head(TFClass_Lookup)

head(variability)
dim(variability)

Rows: 10368 Columns: 4
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (4): full_jaspar_motif, jaspar_motif, lowest_level_family, gene

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1669 Columns: 20
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (20): full_jaspar_motif, jaspar_motif, jaspar_name_1, jaspar_name_2, TFC...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  V1                V2       V3
1 MA0030.1_FOXF2    FOXF2    Fork head/winged helix factors
2 MA0031.1_FOXD1    FOXD1    Fork head/winged helix factors
3 MA0051.1_IRF2     IRF2     Tryptophan cluster factors
4 MA0059.1_MAX::MYC MAX::MYC Basic helix-loop-helix factors (bHLH)
5 MA0066.1_PPARG    PPARG    Nuclear receptors with C4 zinc fingers
6 MA0069.1_PAX6     PAX6     Paired box factors

                          def    cells                     groups
MM_339_AAACGAATCCCGAAGC-1 MM_339 MM_339_AAACGAATCCCGAAGC-1 earlyT1D
MM_339_AAACGAATCTATGAGC-1 MM_339 MM_339_AAACGAATCTATGAGC-1 earlyT1D
MM_339_AAACTCGGTGTGCTTA-1 MM_339 MM_339_AAACTCGGTGTGCTTA-1 earlyT1D
MM_339_AAAGATGTCGGATGTT-1 MM_339 MM_339_AAAGATGTCGGATGTT-1 earlyT1D
MM_339_AAAGGATAGGAGTCTG-1 MM_339 MM_339_AAAGGATAGGAGTCTG-1 earlyT1D
MM_339_AAAGGATAGTCGAGCA-1 MM_339 MM_339_AAAGGATAGTCGAGCA-1 earlyT1D
                          cluster      samples FRIP      TSS.enrichment
MM_339_AAACGAATCCCGAAGC-1 Acinar_1_2_6 6247    0.5421319 4.928013
MM_339_AAACGAATCTATGAGC-1 Acinar_1_2_6 6247    0.7366399 5.622038
MM_339_AAACTCGGTGTGCTTA-1 Acinar_1_2_6 6247    0.6134342 4.720066
MM_339_AAAGATGTCGGATGTT-1 Acinar_1_2_6 6247    0.6927803 4.036170
MM_339_AAAGGATAGGAGTCTG-1 Acinar_1_2_6 6247    0.7235805 5.164169
MM_339_AAAGGATAGTCGAGCA-1 Acinar_1_2_6 6247    0.5906291 4.659066
                          nCount_ATAC nFeature_ATAC
MM_339_AAACGAATCCCGAAGC-1 748         715
MM_339_AAACGAATCTATGAGC-1 830         802
MM_339_AAACTCGGTGTGCTTA-1 505         489
MM_339_AAAGATGTCGGATGTT-1 746         726
MM_339_AAAGGATAGGAGTCTG-1 621         602
MM_339_AAAGGATAGTCGAGCA-1 834         797

[1] 10368     4

  full_jaspar_motif jaspar_motif lowest_level_family gene
1 MA0030.1_FOXF2    FOXF2        FOXF                FOXF2
2 MA0030.1_FOXF2    FOXF2        FOXF                FOXF1
3 MA0031.1_FOXD1    FOXD1        FOXD                FOXD1
4 MA0031.1_FOXD1    FOXD1        FOXD                FOXD2
5 MA0031.1_FOXD1    FOXD1        FOXD                FOXD3
6 MA0031.1_FOXD1    FOXD1        FOXD                FOXD4L1

                  name     variability bootstrap_lower_bound
MA0030.1_FOXF2    FOXF2    1.203838    1.198981
MA0031.1_FOXD1    FOXD1    1.258115    1.252999
MA0051.1_IRF2     IRF2     1.113662    1.108953
MA0059.1_MAX::MYC MAX::MYC 1.035252    1.031647
MA0066.1_PPARG    PPARG    1.018128    1.014559
MA0069.1_PAX6     PAX6     1.054041    1.049918
                  bootstrap_upper_bound p_value       p_value_adj
MA0030.1_FOXF2    1.208643               0.000000e+00  0.000000e+00
MA0031.1_FOXD1    1.263342               0.000000e+00  0.000000e+00
MA0051.1_IRF2     1.118249               0.000000e+00  0.000000e+00
MA0059.1_MAX::MYC 1.038709               1.326763e-95  1.932884e-95
MA0066.1_PPARG    1.021752               6.234495e-27  7.676638e-27
MA0069.1_PAX6     1.058356              2.990752e-220 5.306667e-220

[1] 692   6

In [3]:
# This is the big one; the deviation scores. Runs slow
dev_file <- paste0(in_dir,'devscores.txt')

devscores <- vroom::vroom(file=dev_file, skip=1, col_names=FALSE)
devscores <- tibble::column_to_rownames(devscores, var="X1")
colnames(devscores) <- str_split(readLines(file(dev_file),n=1), " ")[[1]]

dim(devscores)
head(devscores)

Rows: 692 Columns: 174599
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: " "
chr      (1): X1
dbl (174598): X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1]    692 174598

                  MM_339_AAACGAATCCCGAAGC-1 MM_339_AAACGAATCTATGAGC-1
MA0030.1_FOXF2     0.54520151                0.40990183
MA0031.1_FOXD1    -0.64639620                0.56733851
MA0051.1_IRF2     -0.04734576                0.21278816
MA0059.1_MAX::MYC -0.01129497                0.06407827
MA0066.1_PPARG     0.51365043               -0.50851101
MA0069.1_PAX6     -2.20269142               -0.84260738
                  MM_339_AAACTCGGTGTGCTTA-1 MM_339_AAAGATGTCGGATGTT-1
MA0030.1_FOXF2     3.35607428                2.000801239
MA0031.1_FOXD1     2.16471443                0.222432873
MA0051.1_IRF2     -1.17043162                0.006864465
MA0059.1_MAX::MYC -0.60875582               -0.568995229
MA0066.1_PPARG    -0.55188880               -0.488296947
MA0069.1_PAX6     -0.01861448                0.711684614
                  MM_339_AAAGGATAGGAGTCTG-1 MM_339_AAAGGATAGTCGAGCA-1
MA0030.1_FOXF2     0.9658235                -0.459021816
MA0031.1_FOXD1     0.1040411                -1.840425687
MA0051.1_IRF2     -0.6147434                 0.779877039
MA0059.1_MAX::MYC  1.0334839                 0.008193637
MA0066.1_PPARG    -0.6396850                 0.131552195
MA0069.1_PAX6     -1.0814076                 0.492742898
                  MM_339_AAAGGGCCAGTCAGCC-1 MM_339_AAAGGGCTCGATATGC-1
MA0030.1_FOXF2     0.44334913               -0.25558497
MA0031.1_FOXD1     1.07262678               -0.05391174
MA0051.1_IRF2     -0.95418391                0.84427104
MA0059.1_MAX::MYC -1.30026440               -0.93085128
MA0066.1_PPARG    -0.30285472                1.31740292
MA0069.1_PAX6      0.09633553               -0.41465127
                  MM_339_AAAGGGCTCGGTTAGT-1 MM_339_AAATGAGGTGCCAAGA-1 ⋯
MA0030.1_FOXF2    -1.6471011                 0.8835954                ⋯
MA0031.1_FOXD1     1.3205662                 0.8736271                ⋯
MA0051.1_IRF2     -0.1533793                -0.6127317                ⋯
MA0059.1_MAX::MYC -2.0120367                -0.2730295                ⋯
MA0066.1_PPARG     1.8427194                 0.4069058                ⋯
MA0069.1_PAX6     -1.0573779                 0.4792118                ⋯
                  MM_391_GTGCCAGCAGGGTAAC-1 MM_460_AAATGCCGTGCATTGT-1
MA0030.1_FOXF2    -1.3485672                -1.24054617
MA0031.1_FOXD1    -2.0031346                -1.47942813
MA0051.1_IRF2      0.3081769                 0.92292903
MA0059.1_MAX::MYC -1.1595347                 0.42933240
MA0066.1_PPARG     1.3590695                 0.03172931
MA0069.1_PAX6     -0.5531416                 1.12677198
                  MM_460_GCACCTTCATGCGCTG-1 MM_460_GTAATCGCAAAGAAGG-1
MA0030.1_FOXF2     0.6432168                 0.53422671
MA0031.1_FOXD1    -0.2572786                -0.84672181
MA0051.1_IRF2      1.0573372                 0.55484583
MA0059.1_MAX::MYC  2.3681214                -1.55277513
MA0066.1_PPARG     0.1511277                 0.35230581
MA0069.1_PAX6     -0.6887637                 0.07516654
                  MM_460_TAGTCCCAGAAAGCAG-1 MM_460_TTCATTGTCGCAAACT-1
MA0030.1_FOXF2    -0.8512291                 0.34641291
MA0031.1_FOXD1    -1.4112522                -1.44849245
MA0051.1_IRF2     -0.8093365                 1.63052376
MA0059.1_MAX::MYC -1.3609323                -1.10154128
MA0066.1_PPARG    -1.8023297                -0.83032002
MA0069.1_PAX6     -1.1501492                 0.08811665
                  MM_536_GGAGGATCATCCCTCA-1 MM_544_CTAGCGGGTTTAGACC-1
MA0030.1_FOXF2    -1.3156336                -0.1606987
MA0031.1_FOXD1    -1.0407649                -0.3555410
MA0051.1_IRF2      0.6905937                -1.1745899
MA0059.1_MAX::MYC -1.9283999                -0.4375171
MA0066.1_PPARG     0.4737512                -0.1385413
MA0069.1_PAX6     -1.6427782                -0.6124164
                  MM_546_GCACGGTCAGTCAGCC-1 MM_546_TTGCAGAGTTCTGAGT-1
MA0030.1_FOXF2    -0.4841276                -0.1220044
MA0031.1_FOXD1    -2.0004751                -1.9848008
MA0051.1_IRF2      3.0360215                 0.9012208
MA0059.1_MAX::MYC -0.9435472                -1.2343960
MA0066.1_PPARG    -0.9820997                -0.3458552
MA0069.1_PAX6     -0.0492491                -2.0683459

In [4]:
# Pick a cell type
cell_types <- unique(info$cluster)
acinar_labels <- cell_types[str_detect(cell_types,'Acinar')]
acinar_labels

[1] "Acinar_1_2_6" "Acinar_5"     "Acinar_3"     "Acinar_4"

In [5]:
#Filter devscores by cell type
ct_info <- info[info$cluster %in% acinar_labels,]
ct_info$cluster_sample <- paste0(ct_info$cluster, "::", ct_info$samples)
cell_type_barcodes <- rownames(ct_info)

ct_devscores <- devscores[cell_type_barcodes]
head(ct_devscores)

                  MM_339_AAACGAATCCCGAAGC-1 MM_339_AAACGAATCTATGAGC-1
MA0030.1_FOXF2     0.54520151                0.40990183
MA0031.1_FOXD1    -0.64639620                0.56733851
MA0051.1_IRF2     -0.04734576                0.21278816
MA0059.1_MAX::MYC -0.01129497                0.06407827
MA0066.1_PPARG     0.51365043               -0.50851101
MA0069.1_PAX6     -2.20269142               -0.84260738
                  MM_339_AAACTCGGTGTGCTTA-1 MM_339_AAAGATGTCGGATGTT-1
MA0030.1_FOXF2     3.35607428                2.000801239
MA0031.1_FOXD1     2.16471443                0.222432873
MA0051.1_IRF2     -1.17043162                0.006864465
MA0059.1_MAX::MYC -0.60875582               -0.568995229
MA0066.1_PPARG    -0.55188880               -0.488296947
MA0069.1_PAX6     -0.01861448                0.711684614
                  MM_339_AAAGGATAGGAGTCTG-1 MM_339_AAAGGATAGTCGAGCA-1
MA0030.1_FOXF2     0.9658235                -0.459021816
MA0031.1_FOXD1     0.1040411                -1.840425687
MA0051.1_IRF2     -0.6147434                 0.779877039
MA0059.1_MAX::MYC  1.0334839                 0.008193637
MA0066.1_PPARG    -0.6396850                 0.131552195
MA0069.1_PAX6     -1.0814076                 0.492742898
                  MM_339_AAAGGGCCAGTCAGCC-1 MM_339_AAAGGGCTCGATATGC-1
MA0030.1_FOXF2     0.44334913               -0.25558497
MA0031.1_FOXD1     1.07262678               -0.05391174
MA0051.1_IRF2     -0.95418391                0.84427104
MA0059.1_MAX::MYC -1.30026440               -0.93085128
MA0066.1_PPARG    -0.30285472                1.31740292
MA0069.1_PAX6      0.09633553               -0.41465127
                  MM_339_AAAGGGCTCGGTTAGT-1 MM_339_AAATGAGGTGCCAAGA-1 ⋯
MA0030.1_FOXF2    -1.6471011                 0.8835954                ⋯
MA0031.1_FOXD1     1.3205662                 0.8736271                ⋯
MA0051.1_IRF2     -0.1533793                -0.6127317                ⋯
MA0059.1_MAX::MYC -2.0120367                -0.2730295                ⋯
MA0066.1_PPARG     1.8427194                 0.4069058                ⋯
MA0069.1_PAX6     -1.0573779                 0.4792118                ⋯
                  MM_343_TGATCAGAGTCCGTGC-1 MM_344_GGGTTATGTGGTCGAA-1
MA0030.1_FOXF2     0.11774177                0.05098749
MA0031.1_FOXD1    -0.11478954               -1.99743894
MA0051.1_IRF2     -0.41060749               -2.34039655
MA0059.1_MAX::MYC -0.74872369                0.19077289
MA0066.1_PPARG     1.57030957                0.30522468
MA0069.1_PAX6      0.03741945               -0.55272681
                  MM_344_TTACTTGTCACGATTG-1 MM_365_AGGCGTCGTGCAAAGC-1
MA0030.1_FOXF2    -0.04810347                0.3004695
MA0031.1_FOXD1     0.95563125                1.5885369
MA0051.1_IRF2      1.96020891                0.9460906
MA0059.1_MAX::MYC  1.77105142               -0.3716778
MA0066.1_PPARG     0.16772170                0.2058686
MA0069.1_PAX6      0.01524922               -2.9344526
                  MM_365_TTGTCTATCCATAACG-1 MM_388_AGGACGATCGGTCTCT-1
MA0030.1_FOXF2     2.24742975                0.16995892
MA0031.1_FOXD1    -0.38897092               -0.01416535
MA0051.1_IRF2     -1.19794304               -2.58492544
MA0059.1_MAX::MYC -0.29008807               -0.91362941
MA0066.1_PPARG     0.02586427               -0.29000089
MA0069.1_PAX6     -0.22372915               -2.11376888
                  MM_392_GTCGTAAGTTAACTCG-1 MM_394_TAAGTGCCAGGCTACC-1
MA0030.1_FOXF2     0.91933604                0.6541884
MA0031.1_FOXD1     0.12739287                0.4347822
MA0051.1_IRF2     -0.07967277                0.8009769
MA0059.1_MAX::MYC -0.51691895                0.7709466
MA0066.1_PPARG    -1.41702940               -1.4548441
MA0069.1_PAX6     -0.53025330               -1.1320367
                  MM_543_TGCTATTAGTCAACTC-1 MM_545_GCCATAATCGATGAAA-1
MA0030.1_FOXF2     0.545410549              -0.2933488
MA0031.1_FOXD1    -1.319355763               1.6584833
MA0051.1_IRF2      0.939301684               0.9750772
MA0059.1_MAX::MYC  0.045776489               0.2942622
MA0066.1_PPARG    -0.007677915               0.7754606
MA0069.1_PAX6     -0.996974986              -2.0408134

# Significance Testing

Asked to try all versus one t-tests 7/20/23

In [6]:
#Check the cluster labels
acinar_labels

[1] "Acinar_1_2_6" "Acinar_5"     "Acinar_3"     "Acinar_4"

In [7]:
# Average motif accessibiltiy by cluster and sample
clust_samp = sapply(unique(ct_info$cluster_sample), 
            function(i) rowMeans(ct_devscores[,ct_info$cells[ct_info$cluster_sample==i],drop = FALSE], na.rm=T))

clust_samp
                    
clust_samp <- data.frame(t(clust_samp), check.names=FALSE)
                
clust_samp$cluster <- str_split(rownames(clust_samp), "::", simplify=T)[,1]
clust_samp$sample <- str_split(rownames(clust_samp), "::", simplify=T)[,2]
                    
dim(clust_samp)
head(clust_samp)

                     Acinar_1_2_6::6247 Acinar_5::6247 Acinar_3::6247
MA0030.1_FOXF2        0.288221390        0.911368329    0.67485029
MA0031.1_FOXD1        0.343491514        0.925559109    0.82597127
MA0051.1_IRF2        -0.343361258       -0.941498166   -0.63863696
MA0059.1_MAX::MYC    -0.022240786       -0.119718916   -0.18223376
MA0066.1_PPARG        0.002049667        0.090518460   -0.01236141
MA0069.1_PAX6        -0.112726661       -0.414933019   -0.26612253
MA0070.1_PBX1         0.075011763        0.448681793    0.09432914
MA0071.1_RORA         0.109589020        0.381285074    0.20488259
MA0072.1_RORA        -0.057396369       -0.281455428   -0.17533705
MA0073.1_RREB1       -0.180194181       -0.505641784   -0.35210531
MA0074.1_RXRA::VDR    0.026911122        0.239697517    0.10347433
MA0077.1_SOX9        -0.021888547       -0.211942565   -0.06590059
MA0084.1_SRY          0.109700348        0.382343078    0.21118661
MA0091.1_TAL1::TCF3   0.047890719        0.147275195    0.06143900
MA0101.1_REL         -0.432221392       -1.207547519   -0.75606872
MA0107.1_RELA        -0.443967267       -1.429138537   -0.85326656
MA0115.1_NR1H2::RXRA  0.286226485        0.742802473    0.54344525
MA0119.1_NFIC::TLX1   0.244918623        0.774797709    0.48841466
MA0130.1_ZNF354C      0.042186906        0.197713383    0.06370938
MA0139.1_CTCF         0.615712745        1.535185392    1.18584220
MA0149.1_EWSR1-FLI1  -0.394509215       -0.954803976   -0.73277501
MA0138.2_REST         0.134905260        0.614379653    0.29125542
MA0155.1_INSM1       -0.155334407       -0.526143863   -0.35881860
MA0159.1_RARA::RXRA  -0.018931231        0.002081368   -0.12063227
MA0163.1_PLAG1       -0.081497823       -0.341757640   -0.16485371
MA0259.1_ARNT::HIF1A  0.011562704        0.031213102   -0.04725724
MA0468.1_DUX4        -0.020514193        0.116563606   -0.14103844
MA0476.1_FOS         -0.978432204       -2.117122538   -1.26437465
MA0478.1_FOSL2       -0.983956206       -2.096949254   -1.30704959
MA0479.1_FOXH1        0.027011502        0.170244877    0.10919831
⋮                    ⋮                  ⋮              ⋮
MA0765.3_ETV5        -0.16025523        -0.56440896    -0.38699287
MA0784.2_POU1F1       0.06737707         0.03117158     0.03514482
MA0798.3_RFX3        -0.39883938        -1.07479766    -0.80681951
MA0799.2_RFX4        -0.34041254        -1.16701810    -0.65203026
MA0818.2_BHLHE22      0.24619142         0.35997411     0.47502619
MA0819.2_CLOCK        0.01339993         0.02703987    -0.07538146
MA0821.2_HES5         0.02897375        -0.06230282    -0.02960977
MA0828.2_SREBF2      -0.01778005        -0.11443821    -0.04298289
MA0831.3_TFE3        -0.16777184        -0.36886244    -0.38068030
MA0837.2_CEBPE       -0.43259630        -1.15932786    -0.74645984
MA0847.3_FOXD2        0.50432309         1.52881628     0.95088059
MA0865.2_E2F8         0.01208941        -0.01706838     0.12193406
MA0877.3_BARHL1       0.02335706        -0.39863069    -0.05393275
MA0878.3_CDX1        -0.07900383        -0.19275364    -0.14983150
MA0879.2_DLX1        -0.14277687        -0.43999342    -0.34853723
MA0884.2_DUXA        -0.02137666         0.04622134    -0.10826629
MA1483.2_ELF2        -0.48679507        -1.34458334    -0.96175702
MA1487.2_FOXE1        0.45981092         1.21221221     0.95396003
MA1491.2_GLI3        -0.07947948        -0.20130002    -0.12966756
MA1498.2_HOXA7       -0.09757202        -0.42704280    -0.20790647
MA1511.2_KLF10       -0.17602292        -0.56492991    -0.34784718
MA1525.2_NFATC4      -0.23864376        -0.83759819    -0.42091232
MA1532.2_NR1D2       -0.04375100        -0.20664310     0.04203487
MA1547.2_PITX2        0.05277552         0.22356241     0.06211239
MA1563.2_SOX18        0.08216360         0.14820043     0.11476671
MA1566.2_TBX3         0.49429169         1.52649487     0.96431464
MA1601.2_ZNF75D       0.10700789         0.28509207     0.16506320
MA1630.2_ZNF281      -0.24218907        -0.85542998    -0.50190494
MA1633.2_BACH1       -0.95968919        -2.11944726    -1.23438728
MA0597.2_THAP1        0.16714869         0.53734369     0.32778600
                     Acinar_4::6247 Acinar_1_2_6::6418 Acinar_3::6418
MA0030.1_FOXF2        0.94419791     0.062074954        0.203942062
MA0031.1_FOXD1        0.76108221     0.109934165        0.288840758
MA0051.1_IRF2        -1.21497578    -0.095611360       -0.203231519
MA0059.1_MAX::MYC    -0.46287207     0.001444589       -0.096570137
MA0066.1_PPARG       -0.13239338     0.037376184        0.094626248
MA0069.1_PAX6        -0.56866442    -0.058659786       -0.046901089
MA0070.1_PBX1         0.01501102     0.034099768        0.061751548
MA0071.1_RORA         0.24476057     0.014143555        0.054371139
MA0072.1_RORA        -0.21475368    -0.072812574       -0.179599266
MA0073.1_RREB1       -0.27179953    -0.081031600       -0.171604721
MA0074.1_RXRA::VDR   -0.36681455     0.041957241        0.025687551
MA0077.1_SOX9        -0.48886953    -0.022077884       -0.107172931
MA0084.1_SRY         -0.04372988     0.025678071        0.025982742
MA0091.1_TAL1::TCF3   0.44580677    -0.048822896       -0.122582579
MA0101.1_REL         -1.57666399    -0.077019511       -0.249666849
MA0107.1_RELA        -1.55811118    -0.077007272       -0.270325001
MA0115.1_NR1H2::RXRA  1.13846533     0.084275687        0.216569064
MA0119.1_NFIC::TLX1   1.06799422     0.085563753        0.203790548
MA0130.1_ZNF354C      0.23914947     0.007324140        0.096018518
MA0139.1_CTCF         2.15683809     0.240639452        0.542063057
MA0149.1_EWSR1-FLI1  -1.39904667    -0.124273000       -0.296948497
MA0138.2_REST         0.44375160     0.032501507        0.107236367
MA0155.1_INSM1       -0.56830628    -0.046887789       -0.120490996
MA0159.1_RARA::RXRA  -0.03688986     0.005530877        0.007581403
MA0163.1_PLAG1        0.05358444    -0.063700566       -0.145514776
MA0259.1_ARNT::HIF1A  0.11478138     0.015661114       -0.067212150
MA0468.1_DUX4        -0.34613096    -0.015811146        0.051678734
MA0476.1_FOS         -3.24774394     0.061264750        0.591074845
MA0478.1_FOSL2       -3.33780749     0.078403928        0.682366566
MA0479.1_FOXH1       -0.02100043    -0.001813408        0.092597399
⋮                    ⋮              ⋮                  ⋮
MA0765.3_ETV5        -0.61702811    -0.114335098       -0.29882917
MA0784.2_POU1F1      -0.33875848     0.026134697        0.07158183
MA0798.3_RFX3        -1.29689354    -0.103298905       -0.26300391
MA0799.2_RFX4        -0.96930143    -0.128701734       -0.38182548
MA0818.2_BHLHE22      0.60248199     0.068942302        0.17245914
MA0819.2_CLOCK       -0.18984829     0.002651020       -0.03871635
MA0821.2_HES5         0.12556925     0.030676203       -0.09095257
MA0828.2_SREBF2       0.08232206     0.019346893       -0.01030310
MA0831.3_TFE3        -0.38022031    -0.032633295       -0.17989493
MA0837.2_CEBPE       -1.26048327     0.050857688        0.19067424
MA0847.3_FOXD2        1.57652037     0.137154387        0.34016264
MA0865.2_E2F8         0.55378706     0.019628814        0.01983352
MA0877.3_BARHL1      -0.11048567     0.004199346       -0.02511075
MA0878.3_CDX1        -0.66025404    -0.021636946       -0.13989005
MA0879.2_DLX1        -0.64350128    -0.041298096       -0.15712091
MA0884.2_DUXA        -0.07942432    -0.002844028        0.04374141
MA1483.2_ELF2        -1.60764938    -0.137880444       -0.34766195
MA1487.2_FOXE1        1.37314120     0.118957911        0.29373419
MA1491.2_GLI3        -0.03657177    -0.053742482       -0.11319312
MA1498.2_HOXA7       -0.77451392    -0.049495778       -0.13971399
MA1511.2_KLF10       -0.64003301    -0.079713318       -0.15040796
MA1525.2_NFATC4      -1.20050308    -0.109654677       -0.24298267
MA1532.2_NR1D2        0.21368268     0.005201858        0.01740315
MA1547.2_PITX2        0.04341841     0.037192407        0.06063815
MA1563.2_SOX18        0.20598252     0.036682755        0.05915057
MA1566.2_TBX3         1.64253717     0.151997457        0.46253507
MA1601.2_ZNF75D       0.38825321     0.001158809        0.03845619
MA1630.2_ZNF281      -0.77142261    -0.102466888       -0.26751040
MA1633.2_BACH1       -3.06779255     0.080150496        0.59150090
MA0597.2_THAP1        0.55890092     0.087824445        0.16260266
                     Acinar_1_2_6::6339 Acinar_3::6339 Acinar_4::6339
MA0030.1_FOXF2        1.196746e-01       0.449885917    0.56658238
MA0031.1_FOXD1        2.365999e-01       0.719279209    1.38852639
MA0051.1_IRF2        -1.629510e-01      -0.358621929   -0.34783746
MA0059.1_MAX::MYC     6.589320e-02       0.181919273   -0.30285498
MA0066.1_PPARG        3.951064e-02       0.028633112    0.01630102
MA0069.1_PAX6        -3.161382e-02      -0.165541586   -1.21446828
MA0070.1_PBX1        -7.907521e-03       0.151451677   -0.32864573
MA0071.1_RORA         2.768817e-02       0.092994990    0.75401909
MA0072.1_RORA        -4.940730e-02      -0.148294930   -1.25190180
MA0073.1_RREB1       -6.438620e-02      -0.337941823   -0.07808865
MA0074.1_RXRA::VDR    7.816252e-02      -0.074352065    0.12503146
MA0077.1_SOX9        -1.859881e-03      -0.149855460   -1.14270535
MA0084.1_SRY          4.733622e-02       0.009744942    0.08484299
MA0091.1_TAL1::TCF3   3.708754e-02       0.082557551    0.56731764
MA0101.1_REL         -9.394269e-02      -0.306508846    0.24837806
MA0107.1_RELA        -1.170462e-01      -0.269608052    1.07714687
MA0115.1_NR1H2::RXRA  1.792839e-01       0.487815657    1.57802317
MA0119.1_NFIC::TLX1   7.128100e-02       0.501650859    1.86963756
MA0130.1_ZNF354C      2.867604e-02       0.060542688    0.82587315
MA0139.1_CTCF         1.822624e-01       0.457931109    0.74945863
MA0149.1_EWSR1-FLI1  -2.494612e-01      -0.478009503   -1.16941913
MA0138.2_REST         5.203457e-02       0.212258380    0.85654643
MA0155.1_INSM1       -3.987585e-02      -0.131943123    0.48311301
MA0159.1_RARA::RXRA   5.432305e-05       0.088877067    0.38325807
MA0163.1_PLAG1       -9.100307e-02      -0.158035940   -0.65730244
MA0259.1_ARNT::HIF1A  4.897151e-02      -0.036938104    0.06206268
MA0468.1_DUX4         6.418995e-02       0.037439720    0.52926201
MA0476.1_FOS         -3.223227e-01       0.214132136   -0.27847240
MA0478.1_FOSL2       -3.212392e-01       0.354919862   -0.72241637
MA0479.1_FOXH1        8.639091e-03       0.067601393   -0.36629892
⋮                    ⋮                  ⋮              ⋮
MA0765.3_ETV5        -0.054755032       -0.317478050   -0.52238657
MA0784.2_POU1F1       0.074332139        0.145892563    0.42797131
MA0798.3_RFX3        -0.083863165       -0.281025833   -1.80852875
MA0799.2_RFX4        -0.170001810       -0.347919397   -1.16184937
MA0818.2_BHLHE22      0.128203793        0.245184868    1.13361223
MA0819.2_CLOCK        0.062382954        0.165355039   -0.22735460
MA0821.2_HES5         0.130551617        0.097864749    0.38389833
MA0828.2_SREBF2       0.098377637        0.216328241    1.50148256
MA0831.3_TFE3         0.061388716        0.033575457    1.13333709
MA0837.2_CEBPE       -0.080056865        0.049350024    0.05057991
MA0847.3_FOXD2        0.241793545        0.676163319    0.83111618
MA0865.2_E2F8         0.071674471       -0.021561846    0.64240345
MA0877.3_BARHL1      -0.004761402       -0.048451751    0.32602240
MA0878.3_CDX1        -0.012304774       -0.147706406    0.19407699
MA0879.2_DLX1        -0.025279484       -0.153936465   -0.17574935
MA0884.2_DUXA         0.005307377        0.043266603    0.17670231
MA1483.2_ELF2        -0.159722495       -0.405774943   -0.31571027
MA1487.2_FOXE1        0.184513432        0.487408210    0.98129665
MA1491.2_GLI3        -0.014900977       -0.146502721    0.10770547
MA1498.2_HOXA7       -0.027576819       -0.156859968   -0.98513281
MA1511.2_KLF10       -0.081157391       -0.201155691   -0.40319316
MA1525.2_NFATC4       0.006070690        0.003377144   -0.52420696
MA1532.2_NR1D2        0.030773077        0.069143855    0.46505201
MA1547.2_PITX2        0.043719907       -0.012099616    0.26065677
MA1563.2_SOX18        0.061953331       -0.008356085   -0.11363377
MA1566.2_TBX3         0.278752139        0.699411965    0.50149762
MA1601.2_ZNF75D       0.039924067        0.194348229   -0.01010817
MA1630.2_ZNF281      -0.142007322       -0.289917447   -0.39221447
MA1633.2_BACH1       -0.268976946        0.301268119   -0.49417845
MA0597.2_THAP1        0.056272581        0.163636270    0.85339866
                     Acinar_1_2_6::6197 ⋯ Acinar_4::6512 Acinar_5::6505
MA0030.1_FOXF2        0.21025019        ⋯ -0.37281217     0.58291194
MA0031.1_FOXD1        0.24758389        ⋯  0.87443622     0.42817360
MA0051.1_IRF2        -0.39496448        ⋯ -0.56390143    -0.37800792
MA0059.1_MAX::MYC    -0.03177845        ⋯ -0.13714213    -0.36040976
MA0066.1_PPARG        0.01085940        ⋯  0.78459220     0.34669837
MA0069.1_PAX6        -0.16841572        ⋯ -0.69352349    -0.31982734
MA0070.1_PBX1         0.03629012        ⋯  0.24118900    -0.01364684
MA0071.1_RORA         0.18508580        ⋯  0.30496000     0.07787003
MA0072.1_RORA        -0.06546575        ⋯ -0.17027318    -0.15668805
MA0073.1_RREB1       -0.24790279        ⋯ -0.67090991    -0.57909444
MA0074.1_RXRA::VDR    0.07101506        ⋯  0.64968110    -0.02892368
MA0077.1_SOX9         0.01753380        ⋯ -0.37439227    -0.65011229
MA0084.1_SRY          0.05768146        ⋯ -0.33394361    -0.08687743
MA0091.1_TAL1::TCF3  -0.03558609        ⋯  0.18625626     0.03352204
MA0101.1_REL         -0.48873470        ⋯ -1.71356817    -0.35960981
MA0107.1_RELA        -0.44814151        ⋯ -1.56873068    -0.55173427
MA0115.1_NR1H2::RXRA  0.39920258        ⋯  1.10406507     1.24854285
MA0119.1_NFIC::TLX1   0.22178353        ⋯  0.98307996     0.73307755
MA0130.1_ZNF354C      0.03794734        ⋯  0.03745593     0.01866397
MA0139.1_CTCF         0.54661866        ⋯  1.55028754     0.43559734
MA0149.1_EWSR1-FLI1  -0.35625623        ⋯ -0.48284213    -0.36752309
MA0138.2_REST         0.13375873        ⋯ -0.34829088     0.45997258
MA0155.1_INSM1       -0.16591611        ⋯  0.30920668    -0.05057534
MA0159.1_RARA::RXRA   0.04047609        ⋯  0.26100978     0.86553860
MA0163.1_PLAG1       -0.09672011        ⋯  0.08629953    -0.09672598
MA0259.1_ARNT::HIF1A  0.01285505        ⋯  0.18724061     0.19333890
MA0468.1_DUX4        -0.01986103        ⋯ -0.48396090    -0.30223024
MA0476.1_FOS         -0.25491286        ⋯ -1.47283283    -1.09162501
MA0478.1_FOSL2       -0.26669536        ⋯ -0.55370563    -0.78505263
MA0479.1_FOXH1       -0.01362508        ⋯  0.42203725    -0.06227726
⋮                    ⋮                  ⋱ ⋮              ⋮
MA0765.3_ETV5        -0.212711323       ⋯ -1.08574238    -0.50736178
MA0784.2_POU1F1      -0.005718537       ⋯ -0.42449467    -0.26940894
MA0798.3_RFX3        -0.399064071       ⋯ -1.36627427    -0.48161339
MA0799.2_RFX4        -0.379535071       ⋯ -0.57103624    -1.26845095
MA0818.2_BHLHE22      0.179151378       ⋯  0.84773066     0.00173740
MA0819.2_CLOCK        0.022496643       ⋯  0.08841388     0.34736660
MA0821.2_HES5         0.053514245       ⋯  0.29859360    -0.12526501
MA0828.2_SREBF2       0.033397575       ⋯  0.08936104    -0.14287302
MA0831.3_TFE3        -0.133177791       ⋯ -0.22062806    -0.40503775
MA0837.2_CEBPE       -0.573757590       ⋯ -0.64981840    -0.22559588
MA0847.3_FOXD2        0.475051685       ⋯  0.67873564     1.05775869
MA0865.2_E2F8         0.010817940       ⋯ -0.05278043    -0.04926457
MA0877.3_BARHL1      -0.074472585       ⋯  0.14090985    -0.53465694
MA0878.3_CDX1        -0.081089708       ⋯ -0.21830154    -0.34108096
MA0879.2_DLX1        -0.154464836       ⋯ -0.33170648    -0.10057326
MA0884.2_DUXA        -0.028614217       ⋯ -0.04832951    -0.27069096
MA1483.2_ELF2        -0.585573622       ⋯ -1.11636601    -0.63088026
MA1487.2_FOXE1        0.468132735       ⋯  0.19930667     1.02512633
MA1491.2_GLI3        -0.078741805       ⋯  0.41628630    -0.28190986
MA1498.2_HOXA7       -0.119083403       ⋯ -0.40398832     0.05371902
MA1511.2_KLF10       -0.223603762       ⋯ -0.23916009    -0.38813879
MA1525.2_NFATC4      -0.290307026       ⋯ -0.57765689    -0.26940521
MA1532.2_NR1D2       -0.019369348       ⋯  0.24660451    -0.09229137
MA1547.2_PITX2        0.034612358       ⋯ -0.03422767     0.07656697
MA1563.2_SOX18        0.041043612       ⋯ -0.77569731     0.31184250
MA1566.2_TBX3         0.486269604       ⋯  1.63944448     0.94714746
MA1601.2_ZNF75D       0.052389511       ⋯ -0.16721405     0.65321208
MA1630.2_ZNF281      -0.282991100       ⋯ -0.46590199    -0.61600561
MA1633.2_BACH1       -0.242000448       ⋯ -0.83509458    -0.73225549
MA0597.2_THAP1        0.146941262       ⋯  0.83335403     0.75747705
                     Acinar_4::6505 Acinar_5::6339 Acinar_5::6310
MA0030.1_FOXF2       -0.68341087     0.56915239    -0.37969559
MA0031.1_FOXD1        0.65668678     0.91200934     0.70278856
MA0051.1_IRF2         0.20202006    -0.78279488    -0.63233232
MA0059.1_MAX::MYC     0.10278185    -0.18874351     0.89579583
MA0066.1_PPARG        0.21038560    -0.05416728     0.59205959
MA0069.1_PAX6        -0.69850063     0.03471583    -1.05245416
MA0070.1_PBX1         1.37645127    -0.29529326     1.16896878
MA0071.1_RORA        -0.24759140     0.35917895     0.83390413
MA0072.1_RORA         0.12711748     0.04504954     0.52084069
MA0073.1_RREB1       -0.57229097    -0.04004149    -0.90249966
MA0074.1_RXRA::VDR   -0.01215188    -0.25497410    -0.32582855
MA0077.1_SOX9         0.41928732     0.13417502    -0.34133908
MA0084.1_SRY          0.75287141    -0.49449710     0.07312079
MA0091.1_TAL1::TCF3  -1.01444778     0.22270135     0.36074416
MA0101.1_REL         -1.94416397    -0.52557036    -0.66061305
MA0107.1_RELA        -1.01652308    -0.44283486    -0.44544454
MA0115.1_NR1H2::RXRA  0.67239858     0.68706287     0.57027195
MA0119.1_NFIC::TLX1   1.65046180    -0.15669374     1.34611046
MA0130.1_ZNF354C      0.78917160     0.72679141    -1.34957621
MA0139.1_CTCF         0.35130106     0.47421045     0.63963662
MA0149.1_EWSR1-FLI1   0.83369467    -0.91493866    -0.61611791
MA0138.2_REST         1.79744870     0.20392734     0.06827985
MA0155.1_INSM1       -0.84463390    -0.33229572    -0.09631590
MA0159.1_RARA::RXRA   0.68796797    -0.06194057     0.30464704
MA0163.1_PLAG1       -0.22148213    -0.12100972    -0.38393944
MA0259.1_ARNT::HIF1A  0.80161369    -0.29356343    -0.41440177
MA0468.1_DUX4         0.89705872     0.05650562     0.71409655
MA0476.1_FOS         -0.39468488    -0.74807870    -1.25645718
MA0478.1_FOSL2        0.31140380    -0.72317589    -1.64740195
MA0479.1_FOXH1        0.01853574     0.42355304    -0.55356015
⋮                    ⋮              ⋮              ⋮
MA0765.3_ETV5        -0.87252301     0.092233992   -0.422937465
MA0784.2_POU1F1      -0.53210934     0.108149316    0.883958910
MA0798.3_RFX3        -1.73628627    -0.422493610   -1.519110982
MA0799.2_RFX4        -1.15211356    -0.501596168   -0.558865000
MA0818.2_BHLHE22     -0.17451649     0.699457183    0.317851215
MA0819.2_CLOCK        1.26444194    -0.002193022    0.418230578
MA0821.2_HES5         1.15153940     0.135312714    0.205899046
MA0828.2_SREBF2       0.23409889     0.053371059    0.178806120
MA0831.3_TFE3         0.10026312     0.294972678   -0.147096056
MA0837.2_CEBPE       -0.49844355    -0.377711619   -0.758031663
MA0847.3_FOXD2        1.15793119     0.525824166    0.561059271
MA0865.2_E2F8        -0.11120819     0.137968747   -0.485720849
MA0877.3_BARHL1       0.16706869     0.244720946   -0.148922542
MA0878.3_CDX1        -0.07047660    -0.303639468    0.404257797
MA0879.2_DLX1        -0.92742465     0.045997556   -0.027489924
MA0884.2_DUXA         0.10110102     0.346152907    0.731290982
MA1483.2_ELF2        -1.09089682    -0.303659949   -0.424203776
MA1487.2_FOXE1        0.44501874     0.167051833    0.659375957
MA1491.2_GLI3         0.10091336    -0.630013070   -0.091803510

[1] 115 694

                   MA0030.1_FOXF2 MA0031.1_FOXD1 MA0051.1_IRF2
Acinar_1_2_6::6247 0.28822139     0.3434915      -0.34336126
Acinar_5::6247     0.91136833     0.9255591      -0.94149817
Acinar_3::6247     0.67485029     0.8259713      -0.63863696
Acinar_4::6247     0.94419791     0.7610822      -1.21497578
Acinar_1_2_6::6418 0.06207495     0.1099342      -0.09561136
Acinar_3::6418     0.20394206     0.2888408      -0.20323152
                   MA0059.1_MAX::MYC MA0066.1_PPARG MA0069.1_PAX6 MA0070.1_PBX1
Acinar_1_2_6::6247 -0.022240786       0.002049667   -0.11272666   0.07501176
Acinar_5::6247     -0.119718916       0.090518460   -0.41493302   0.44868179
Acinar_3::6247     -0.182233762      -0.012361412   -0.26612253   0.09432914
Acinar_4::6247     -0.462872068      -0.132393377   -0.56866442   0.01501102
Acinar_1_2_6::6418  0.001444589       0.037376184   -0.05865979   0.03409977
Acinar_3::6418     -0.096570137       0.094626248   -0.04690109   0.06175155
                   MA0071.1_RORA MA0072.1_RORA MA0073.1_RREB1 ⋯ MA1532.2_NR1D2
Acinar_1_2_6::6247 0.10958902    -0.05739637   -0.1801942     ⋯ -0.043750999
Acinar_5::6247     0.38128507    -0.28145543   -0.5056418     ⋯ -0.206643097
Acinar_3::6247     0.20488259    -0.17533705   -0.3521053     ⋯  0.042034870
Acinar_4::6247     0.24476057    -0.21475368   -0.2717995     ⋯  0.213682681
Acinar_1_2_6::6418 0.01414355    -0.07281257   -0.0810316     ⋯  0.005201858
Acinar_3::6418     0.05437114    -0.17959927   -0.1716047     ⋯  0.017403146
                   MA1547.2_PITX2 MA1563.2_SOX18 MA1566.2_TBX3 MA1601.2_ZNF75D
Acinar_1_2_6::6247 0.05277552     0.08216360     0.4942917     0.107007894
Acinar_5::6247     0.22356241     0.14820043     1.5264949     0.285092066
Acinar_3::6247     0.06211239     0.11476671     0.9643146     0.165063201
Acinar_4::6247     0.04341841     0.20598252     1.6425372     0.388253213
Acinar_1_2_6::6418 0.03719241     0.03668276     0.1519975     0.001158809
Acinar_3::6418     0.06063815     0.05915057     0.4625351     0.038456187
                   MA1630.2_ZNF281 MA1633.2_BACH1 MA0597.2_THAP1 cluster
Acinar_1_2_6::6247 -0.2421891      -0.9596892     0.16714869     Acinar_1_2_6
Acinar_5::6247     -0.8554300      -2.1194473     0.53734369     Acinar_5
Acinar_3::6247     -0.5019049      -1.2343873     0.32778600     Acinar_3
Acinar_4::6247     -0.7714226      -3.0677926     0.55890092     Acinar_4
Acinar_1_2_6::6418 -0.1024669       0.0801505     0.08782445     Acinar_1_2_6
Acinar_3::6418     -0.2675104       0.5915009     0.16260266     Acinar_3
                   sample
Acinar_1_2_6::6247 6247
Acinar_5::6247     6247
Acinar_3::6247     6247
Acinar_4::6247     6247
Acinar_1_2_6::6418 6418
Acinar_3::6418     6418

In [8]:
# Run an anova comparing the motifs accessibility across clusters, controlling for sample
clust_anova_data <- select(clust_samp, samples=sample, cluster, everything())
results <- numeric(0)

donor_anova_results = data.frame(matrix(nrow=nrow(ct_devscores), ncol = 2))
rownames(donor_anova_results)= colnames(clust_anova_data)[3:ncol(clust_anova_data)]
    
#for (i in 3) {
for (i in 3:ncol(clust_anova_data)) {
    motif <- colnames(clust_anova_data)[i]
    mod1 = aov(clust_anova_data[,i] ~ cluster + samples, data = clust_anova_data)
    res <- Anova(mod1, type="II")
    
    donor_anova_results[motif,1] <- motif
    donor_anova_results[motif,2] <- as.numeric(broom::tidy(res)[1,5])
}

dim(donor_anova_results)
head(donor_anova_results)

[1] 692   2

                  X1                X2
MA0030.1_FOXF2    MA0030.1_FOXF2    6.959097e-04
MA0031.1_FOXD1    MA0031.1_FOXD1    1.307808e-11
MA0051.1_IRF2     MA0051.1_IRF2     1.554499e-14
MA0059.1_MAX::MYC MA0059.1_MAX::MYC 1.119976e-02
MA0066.1_PPARG    MA0066.1_PPARG    6.430220e-01
MA0069.1_PAX6     MA0069.1_PAX6     5.950115e-06

In [9]:
#FDR Correct and check results
colnames(donor_anova_results)[1:2] <- c('Motif','p.value')
donor_anova_results <- arrange(donor_anova_results, p.value)
donor_anova_results$q.values <- qvalue(donor_anova_results$p.value)$qvalue

dim(donor_anova_results)
sum(donor_anova_results$p.value < 0.05)
sum(donor_anova_results$q.value < .05)
head(donor_anova_results)
tail(donor_anova_results)

[1] 692   3

[1] 534

[1] 610

  Motif               p.value      q.values
1 MA0745.2_SNAI2      3.368285e-42 3.073344e-40
2 MA0103.3_ZEB1       2.124091e-41 9.690483e-40
3 MA0499.2_MYOD1      2.640159e-38 8.029921e-37
4 MA1559.1_SNAI3      1.195929e-37 2.399726e-36
5 MA1935.1_ERF::FOXI1 1.315011e-37 2.399726e-36
6 MA0522.3_TCF3       5.413610e-37 7.642365e-36

    Motif            p.value   q.values
687 MA1644.1_NFYC    0.9412758 0.1250151
688 MA2003.1_NKX2-4  0.9526814 0.1263460
689 MA1474.1_CREB3L4 0.9546158 0.1264188
690 MA0794.1_PROX1   0.9646204 0.1275586
691 MA0865.2_E2F8    0.9855639 0.1301395
692 MA1645.1_NKX2-2  0.9991224 0.1317392

In [10]:
#Post hoc compare individual clusters to everything else and correct with holm's

type_anova_results_full = data.frame(matrix(nrow=nrow(ct_devscores), ncol = 1))
colnames(type_anova_results_full) <- c('Motif')
type_anova_results_full$Motif <- rownames(ct_devscores)

for (type in acinar_labels) {
    type_anova_data <- select(clust_samp, samples=sample, cluster, everything())
    
    type_anova_data$cluster <- type_anova_data$cluster ==type
    type_anova_data <- group_by(type_anova_data, cluster, samples) %>%
                            summarize_all(mean)
    
    type_anova_results = data.frame(matrix(nrow=nrow(ct_devscores), ncol = 2))
    colnames(type_anova_results) <- c('Motif',paste0(type, ".p.value"))
    rownames(type_anova_results)= colnames(type_anova_data)[3:ncol(type_anova_data)]
        
    #for (i in 3) {
    for (i in 3:ncol(type_anova_data)) {
        motif <- colnames(type_anova_data)[i]
        mod1 = aov(unlist(type_anova_data[,i]) ~ cluster + samples, data = type_anova_data)
        res <- Anova(mod1, type="II")
        
        type_anova_results[motif,'Motif'] <- motif
        type_anova_results[motif,2] <- as.numeric(broom::tidy(res)[1,5])
    }
        
    type_anova_results_full <- left_join(type_anova_results_full, type_anova_results)
}

dim(type_anova_results_full)
head(type_anova_results_full)

Joining with `by = join_by(Motif)`
Joining with `by = join_by(Motif)`
Joining with `by = join_by(Motif)`
Joining with `by = join_by(Motif)`

[1] 692   5

  Motif             Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1 MA0030.1_FOXF2    1.878561e-06         7.161564e-03     0.4033856373
2 MA0031.1_FOXD1    8.190823e-11         2.474089e-04     0.7115260632
3 MA0051.1_IRF2     2.146152e-10         1.182946e-07     0.0001289029
4 MA0059.1_MAX::MYC 7.680233e-03         1.116966e-01     0.0013265279
5 MA0066.1_PPARG    3.355028e-01         2.115934e-01     0.2765041439
6 MA0069.1_PAX6     1.016753e-06         6.478739e-03     0.0012452074
  Acinar_4.p.value
1 0.4695431201
2 0.0071438760
3 0.0008358103
4 0.1502414143
5 0.6371728416
6 0.0280443027

In [11]:
#Run the holm's correction
holm_df <- data.frame()

for (i in 1:nrow(type_anova_results_full)) {
    holm_adjust <- p.adjust(type_anova_results_full[i,2:5], method='holm')
    names(holm_adjust) <- str_replace(names(holm_adjust), 'p.value','holm')
    holm_adjust <- data.frame(t(data.frame(holm_adjust)))
    holm_adjust$Motif <- type_anova_results_full[i,1]
    
    holm_df <- rbind(holm_df, data.frame(holm_adjust))
}

type_anova_results_full_holm <- left_join(type_anova_results_full, holm_df)

dim(type_anova_results_full_holm)
sum(is.na(type_anova_results_full_holm))
head(type_anova_results_full_holm)

Joining with `by = join_by(Motif)`

[1] 692   9

[1] 0

  Motif             Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1 MA0030.1_FOXF2    1.878561e-06         7.161564e-03     0.4033856373
2 MA0031.1_FOXD1    8.190823e-11         2.474089e-04     0.7115260632
3 MA0051.1_IRF2     2.146152e-10         1.182946e-07     0.0001289029
4 MA0059.1_MAX::MYC 7.680233e-03         1.116966e-01     0.0013265279
5 MA0066.1_PPARG    3.355028e-01         2.115934e-01     0.2765041439
6 MA0069.1_PAX6     1.016753e-06         6.478739e-03     0.0012452074
  Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1 0.4695431201     7.514245e-06      2.148469e-02  0.8067712747  0.8067712747
2 0.0071438760     3.276329e-10      7.422268e-04  0.7115260632  0.0142877519
3 0.0008358103     8.584606e-10      3.548837e-07  0.0002578058  0.0008358103
4 0.1502414143     2.304070e-02      2.233933e-01  0.0053061117  0.2233932673
5 0.6371728416     8.463736e-01      8.463736e-01  0.8463735940  0.8463735940
6 0.0280443027     4.067012e-06      1.295748e-02  0.0037356223  0.0280443027

In [12]:
# Join with the overall ANOVA data
colnames(donor_anova_results)[str_detect(colnames(donor_anova_results), 'p.value')] <- 'anova.p.value'
colnames(donor_anova_results)[str_detect(colnames(donor_anova_results), 'q.value')] <- 'anova.q.value'
#donor_anova_results
type_anova_results_full_holm_anova <- left_join(type_anova_results_full_holm, donor_anova_results)

dim(type_anova_results_full_holm_anova)
head(type_anova_results_full_holm_anova)

Joining with `by = join_by(Motif)`

[1] 692  11

  Motif             Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1 MA0030.1_FOXF2    1.878561e-06         7.161564e-03     0.4033856373
2 MA0031.1_FOXD1    8.190823e-11         2.474089e-04     0.7115260632
3 MA0051.1_IRF2     2.146152e-10         1.182946e-07     0.0001289029
4 MA0059.1_MAX::MYC 7.680233e-03         1.116966e-01     0.0013265279
5 MA0066.1_PPARG    3.355028e-01         2.115934e-01     0.2765041439
6 MA0069.1_PAX6     1.016753e-06         6.478739e-03     0.0012452074
  Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1 0.4695431201     7.514245e-06      2.148469e-02  0.8067712747  0.8067712747
2 0.0071438760     3.276329e-10      7.422268e-04  0.7115260632  0.0142877519
3 0.0008358103     8.584606e-10      3.548837e-07  0.0002578058  0.0008358103
4 0.1502414143     2.304070e-02      2.233933e-01  0.0053061117  0.2233932673
5 0.6371728416     8.463736e-01      8.463736e-01  0.8463735940  0.8463735940
6 0.0280443027     4.067012e-06      1.295748e-02  0.0037356223  0.0280443027
  anova.p.value anova.q.value
1 6.959097e-04  1.515449e-04
2 1.307808e-11  5.709526e-12
3 1.554499e-14  8.294624e-15
4 1.119976e-02  2.089788e-03
5 6.430220e-01  8.943847e-02
6 5.950115e-06  1.635271e-06

In [13]:
# Calculate deviation score average for different comparisons
dev_averages <- data.frame(Motif=colnames(clust_samp)[1:(ncol(clust_samp) - 2)])

for (clust in acinar_labels) {
    cluster_specific <- clust_samp
    cluster_specific$cluster <- cluster_specific$cluster == clust
    
    cluster_specific <- group_by(cluster_specific, cluster, sample) %>%
        summarise_all(mean) %>%
        select(-sample) %>%
        group_by(cluster) %>%
        summarise_all(mean)
    
    cluster_specific$cluster[cluster_specific$cluster] <- clust
    cluster_specific$cluster[cluster_specific$cluster == FALSE] <- paste0("not.",clust)
    
    cluster_specific <- tibble::column_to_rownames(cluster_specific, var='cluster')
    cluster_specific <- data.frame(t(cluster_specific))
    cluster_specific <- tibble::rownames_to_column(cluster_specific, var='Motif')
    
    cluster_specific[[paste0(clust, '.diff')]] <- cluster_specific[[clust]] - cluster_specific[[paste0("not.",clust)]]
    
    dev_averages <- left_join(dev_averages, cluster_specific)
}

Joining with `by = join_by(Motif)`
Joining with `by = join_by(Motif)`
Joining with `by = join_by(Motif)`
Joining with `by = join_by(Motif)`

In [14]:
# Join in deviation scores
type_anova_results_full_holm_anova_dev <- left_join(type_anova_results_full_holm_anova, dev_averages)

type_anova_results_full_holm_anova_dev

Joining with `by = join_by(Motif)`

    Motif                Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1   MA0030.1_FOXF2       1.878561e-06         7.161564e-03     4.033856e-01
2   MA0031.1_FOXD1       8.190823e-11         2.474089e-04     7.115261e-01
3   MA0051.1_IRF2        2.146152e-10         1.182946e-07     1.289029e-04
4   MA0059.1_MAX::MYC    7.680233e-03         1.116966e-01     1.326528e-03
5   MA0066.1_PPARG       3.355028e-01         2.115934e-01     2.765041e-01
6   MA0069.1_PAX6        1.016753e-06         6.478739e-03     1.245207e-03
7   MA0070.1_PBX1        1.950325e-04         1.071945e-01     5.157297e-02
8   MA0071.1_RORA        1.189834e-06         1.795454e-04     9.240308e-01
9   MA0072.1_RORA        2.290104e-02         5.710456e-01     8.850272e-01
10  MA0073.1_RREB1       3.818641e-14         9.717376e-07     3.100293e-02
11  MA0074.1_RXRA::VDR   1.073328e-02         3.464559e-01     8.185752e-01
12  MA0077.1_SOX9        1.148739e-06         1.596140e-01     3.392961e-01
13  MA0084.1_SRY         5.638107e-01         1.734758e-01     5.397903e-01
14  MA0091.1_TAL1::TCF3  6.786592e-01         3.385935e-01     2.267544e-05
15  MA0101.1_REL         2.541982e-09         4.897347e-07     5.214370e-07
16  MA0107.1_RELA        9.959064e-08         3.405388e-09     7.111582e-06
17  MA0115.1_NR1H2::RXRA 1.734276e-13         2.443042e-07     7.056164e-05
18  MA0119.1_NFIC::TLX1  8.563274e-12         1.179298e-02     3.999199e-02
19  MA0130.1_ZNF354C     1.037398e-01         5.226134e-01     8.563384e-01
20  MA0139.1_CTCF        2.041670e-09         1.396105e-04     3.421009e-06
21  MA0149.1_EWSR1-FLI1  5.260545e-13         1.524449e-05     1.571023e-06
22  MA0138.2_REST        8.457234e-08         1.902967e-01     4.586928e-02
23  MA0155.1_INSM1       3.461382e-05         2.474980e-02     5.818122e-01
24  MA0159.1_RARA::RXRA  3.580008e-01         3.894511e-01     2.043249e-02
25  MA0163.1_PLAG1       9.707800e-06         1.015805e-02     8.422183e-01
26  MA0259.1_ARNT::HIF1A 2.929046e-01         1.703781e-01     1.972743e-01
27  MA0468.1_DUX4        2.783004e-01         8.273214e-01     6.913247e-01
28  MA0476.1_FOS         1.218191e-04         1.334765e-06     1.712200e-11
29  MA0478.1_FOSL2       6.439040e-04         4.877339e-06     2.730887e-11
30  MA0479.1_FOXH1       2.555437e-01         4.439863e-01     3.401389e-02
⋮   ⋮                    ⋮                    ⋮                ⋮
663 MA0765.3_ETV5        1.299022e-13         2.288174e-04     9.844155e-04
664 MA0784.2_POU1F1      2.577133e-01         1.284384e-01     8.766635e-01
665 MA0798.3_RFX3        6.333756e-15         4.914809e-04     8.742749e-08
666 MA0799.2_RFX4        1.197942e-16         1.113793e-04     5.275652e-03
667 MA0818.2_BHLHE22     4.009071e-10         1.405053e-02     3.097819e-03
668 MA0819.2_CLOCK       2.129314e-02         4.805949e-02     1.923667e-03
669 MA0821.2_HES5        1.072833e-02         3.832327e-01     4.434327e-05
670 MA0828.2_SREBF2      1.053814e-03         3.483582e-01     5.075757e-01
671 MA0831.3_TFE3        3.006546e-03         5.758231e-02     1.730429e-02
672 MA0837.2_CEBPE       1.842437e-09         8.057534e-07     6.130090e-04
673 MA0847.3_FOXD2       1.937168e-14         5.903086e-07     1.699319e-05
674 MA0865.2_E2F8        5.907555e-01         9.248896e-01     5.773891e-01
675 MA0877.3_BARHL1      4.086280e-04         5.590938e-01     2.700637e-01
676 MA0878.3_CDX1        2.639327e-10         4.981164e-01     4.849249e-01
677 MA0879.2_DLX1        1.072301e-06         3.602499e-01     8.383289e-02
678 MA0884.2_DUXA        3.639946e-01         6.884185e-01     3.243642e-01
679 MA1483.2_ELF2        6.756606e-13         5.733928e-09     3.233385e-07
680 MA1487.2_FOXE1       1.749221e-12         7.534956e-08     1.487714e-03
681 MA1491.2_GLI3        1.298632e-03         1.980245e-03     5.581553e-01
682 MA1498.2_HOXA7       5.586005e-07         4.306392e-01     5.770647e-02
683 MA1511.2_KLF10       8.537181e-12         4.223534e-07     1.546485e-06
684 MA1525.2_NFATC4      6.243845e-08         3.940263e-04     3.482965e-03
685 MA1532.2_NR1D2       2.317577e-01         6.464799e-02     1.124279e-04
686 MA1547.2_PITX2       5.906593e-01         4.614179e-01     1.824823e-01
687 MA1563.2_SOX18       9.655773e-01         7.308639e-01     5.735175e-01
688 MA1566.2_TBX3        5.637909e-17         5.912457e-06     8.684939e-09
689 MA1601.2_ZNF75D      2.446000e-05         1.347379e-01     6.013402e-02
690 MA1630.2_ZNF281      1.590872e-17         1.421048e-05     1.189267e-07
691 MA1633.2_BACH1       4.730066e-04         3.208037e-07     6.128404e-11
692 MA0597.2_THAP1       1.971385e-15         4.360650e-04     8.464455e-07
    Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm
1   4.695431e-01     7.514245e-06      2.148469e-02  8.067713e-01
2   7.143876e-03     3.276329e-10      7.422268e-04  7.115261e-01
3   8.358103e-04     8.584606e-10      3.548837e-07  2.578058e-04
4   1.502414e-01     2.304070e-02      2.233933e-01  5.306112e-03
5   6.371728e-01     8.463736e-01      8.463736e-01  8.463736e-01
6   2.804430e-02     4.067012e-06      1.295748e-02  3.735622e-03
7   2.224225e-01     7.801299e-04      2.143890e-01  1.547189e-01
8   4.904732e-01     4.759337e-06      5.386362e-04  9.809463e-01
9   2.716860e-01     9.160417e-02      1.000000e+00  1.000000e+00
10  2.888602e-03     1.527457e-13      2.915213e-06  3.100293e-02
11  5.303483e-01     4.293310e-02      1.000000e+00  1.000000e+00
12  1.635705e-01     4.594956e-06      4.788419e-01  4.788419e-01
13  4.501992e-01     1.000000e+00      6.939031e-01  1.000000e+00
14  1.343084e-01     6.786592e-01      6.771870e-01  9.070177e-05
15  6.820878e-04     1.016793e-08      1.469204e-06  1.469204e-06
16  8.705353e-03     2.987719e-07      1.362155e-08  1.422316e-05
17  2.014495e-05     6.937104e-13      7.329125e-07  7.056164e-05
18  4.672273e-04     3.425310e-11      2.358597e-02  3.999199e-02
19  2.000563e-01     4.149592e-01      1.000000e+00  1.000000e+00
20  4.315427e-08     8.166680e-09      1.396105e-04  6.842018e-06
21  9.706877e-06     2.104218e-12      1.941375e-05  4.713068e-06
22  2.308168e-03     3.382893e-07      1.902967e-01  9.173857e-02
23  5.054334e-01     1.384553e-04      7.424940e-02  1.000000e+00
24  2.288113e-01     7.160016e-01      7.160016e-01  8.172995e-02
25  4.936582e-01     3.883120e-05      3.047414e-02  9.873165e-01
26  3.241069e-01     6.815124e-01      6.815124e-01  6.815124e-01
27  3.007253e-01     1.000000e+00      1.000000e+00  1.000000e+00
28  4.271062e-06     1.218191e-04      4.004294e-06  6.848799e-11
29  3.058844e-05     6.439040e-04      1.463202e-05  1.092355e-10
30  8.431619e-02     5.110874e-01      5.110874e-01  1.360556e-01
⋮   ⋮                ⋮                 ⋮             ⋮
663 2.202733e-05     5.196090e-13      4.576347e-04  9.844155e-04
664 8.939404e-01     7.731398e-01      5.137537e-01  1.000000e+00
665 6.087903e-07     2.533502e-14      4.914809e-04  2.622825e-07
666 2.650160e-05     4.791769e-16      2.227586e-04  5.275652e-03
667 9.808248e-04     1.603628e-09      1.405053e-02  6.195637e-03
668 8.452472e-02     6.387941e-02      9.611897e-02  7.694670e-03
669 1.285923e-03     2.145666e-02      3.832327e-01  1.773731e-04
670 3.215217e-02     4.215254e-03      6.967164e-01  6.967164e-01
671 5.973989e-01     1.202618e-02      1.151646e-01  5.191288e-02
672 6.386221e-06     7.369748e-09      2.417260e-06  6.130090e-04
673 5.711334e-06     7.748671e-14      1.770926e-06  1.699319e-05
674 9.599230e-01     1.000000e+00      1.000000e+00  1.000000e+00
675 1.108517e-01     1.634512e-03      5.590938e-01  5.401273e-01
676 1.847311e-03     1.055731e-09      9.698499e-01  9.698499e-01
677 4.021750e-03     4.289203e-06      3.602499e-01  1.676658e-01
678 2.998599e-01     1.000000e+00      1.000000e+00  1.000000e+00
679 2.520763e-05     2.702642e-12      1.720179e-08  6.466770e-07
680 8.561141e-04     6.996885e-12      2.260487e-07  1.712228e-03
681 6.816735e-01     5.194527e-03      5.940735e-03  1.000000e+00
682 4.913711e-03     2.234402e-06      4.306392e-01  1.154129e-01
683 5.934817e-04     3.414873e-11      1.267060e-06  3.092971e-06
684 8.635880e-04     2.497538e-07      1.182079e-03  3.482965e-03
685 2.273966e-01     4.547931e-01      1.939440e-01  4.497115e-04
686 6.635607e-01     1.000000e+00      1.000000e+00  7.299294e-01
687 4.425921e-01     1.000000e+00      1.000000e+00  1.000000e+00
688 1.721518e-06     2.255163e-16      5.912457e-06  2.605482e-08
689 8.175967e-02     9.783998e-05      1.804021e-01  1.804021e-01
690 9.522795e-08     6.363488e-17      1.421048e-05  2.856838e-07
691 1.367710e-05     4.730066e-04      9.624110e-07  2.451362e-10
692 1.629254e-06     7.885539e-15      4.360650e-04  2.539337e-06
    Acinar_4.holm anova.p.value ⋯ Acinar_1_2_6.diff not.Acinar_5 Acinar_5
1   8.067713e-01  6.959097e-04  ⋯ -0.29368123        0.33699151   0.51742727
2   1.428775e-02  1.307808e-11  ⋯ -0.47908016        0.51777387   0.75361113
3   8.358103e-04  1.554499e-14  ⋯  0.42732160       -0.45760182  -0.77134101
4   2.233933e-01  1.119976e-02  ⋯ -0.08194305        0.06217336   0.15690768
5   8.463736e-01  6.430220e-01  ⋯ -0.04471532        0.04754416   0.09334931
6   2.804430e-02  5.950115e-06  ⋯  0.23944826       -0.24760523  -0.39473373
7   2.224225e-01  1.918401e-02  ⋯ -0.12903260        0.11429194   0.22582676
8   9.809463e-01  2.142472e-04  ⋯ -0.24277745        0.26911233   0.44937995
9   8.150579e-01  2.645968e-01  ⋯  0.08079290       -0.09834624  -0.06669427
10  5.777204e-03  5.716259e-16  ⋯  0.33105222       -0.35431073  -0.58469814
11  1.000000e+00  2.774748e-01  ⋯ -0.09189426        0.11812177   0.15473034
12  4.788419e-01  9.918394e-03  ⋯  0.16214436       -0.13141035  -0.20980007
13  1.000000e+00  4.798476e-01  ⋯ -0.01890480        0.02189180   0.09069035
14  4.029253e-01  5.473538e-03  ⋯  0.01554181       -0.00591125   0.03590369
15  6.820878e-04  4.448564e-13  ⋯  0.45821720       -0.50510687  -0.85064002
16  8.705353e-03  3.429995e-11  ⋯  0.42850686       -0.47249238  -0.87202460
17  4.028990e-05  3.358351e-19  ⋯ -0.57579719        0.65333636   0.95375330
18  1.401682e-03  3.660158e-11  ⋯ -0.53894974        0.55409177   0.81561210
19  6.001689e-01  3.519829e-01  ⋯ -0.05271374        0.06123471   0.02274709
20  1.294628e-07  1.149990e-18  ⋯ -0.56954604        0.67601122   0.94758482
21  1.941375e-05  5.515180e-18  ⋯  0.53850495       -0.58098553  -0.87267599
22  6.924503e-03  1.246399e-07  ⋯ -0.25555693        0.29816160   0.34872252
23  1.000000e+00  9.581397e-03  ⋯  0.15617428       -0.17959365  -0.29889477
24  6.864340e-01  1.820580e-01  ⋯ -0.02471390        0.04530624   0.08683500
25  9.873165e-01  1.458527e-02  ⋯  0.15182831       -0.18060447  -0.27185939
26  6.815124e-01  2.702757e-01  ⋯  0.03283356       -0.01413027  -0.06413530
27  1.000000e+00  5.217170e-01  ⋯ -0.05168132        0.03582684   0.02241186
28  8.542124e-06  1.857219e-17  ⋯  0.66226668       -0.89902120  -1.75656688
29  6.117688e-05  1.956239e-15  ⋯  0.62160171       -0.86368564  -1.71448283
30  2.529486e-01  5.818325e-02  ⋯  0.05194455       -0.02787386   0.01184411
⋮   ⋮             ⋮             ⋱ ⋮                 ⋮            ⋮
663 6.608198e-05  2.703367e-16  ⋯  0.515692630      -0.56172465  -0.777969064
664 1.000000e+00  6.987476e-01  ⋯ -0.043053623       0.06097531   0.122174319
665 1.217581e-06  7.694154e-20  ⋯  0.558433265      -0.60473650  -0.838101694
666 7.950481e-05  9.487104e-18  ⋯  0.458870361      -0.51797508  -0.741553630
667 2.942474e-03  8.984012e-10  ⋯ -0.263532314       0.30150463   0.404755739
668 9.611897e-02  3.920143e-03  ⋯ -0.082833990       0.08814835   0.152434866
669 3.857769e-03  6.605534e-06  ⋯ -0.070514727       0.11500076   0.077458370
670 9.645650e-02  4.612753e-03  ⋯ -0.110642879       0.12273060   0.082480832
671 5.973989e-01  4.339513e-02  ⋯  0.117208945      -0.13376645  -0.223356351
672 1.277244e-05  2.290423e-15  ⋯  0.469688376      -0.54303572  -0.836341611
673 1.142267e-05  1.710207e-21  ⋯ -0.675302439       0.74878661   1.142167246
674 1.000000e+00  9.855639e-01  ⋯  0.014330657      -0.03533526  -0.031417333
675 3.325552e-01  4.740575e-02  ⋯  0.086325947      -0.07566826  -0.102157624
676 5.541934e-03  7.547976e-06  ⋯  0.160867408      -0.17248164  -0.202077029
677 1.206525e-02  2.008646e-05  ⋯  0.207735273      -0.24053266  -0.294738697
678 1.000000e+00  4.627805e-01  ⋯  0.027341055      -0.03737654  -0.014052794
679 2.520763e-05  3.279196e-20  ⋯  0.677160680      -0.76248338  -1.229309897
680 1.712228e-03  5.497418e-18  ⋯ -0.553719686       0.59599195   1.000098808
681 1.000000e+00  2.074299e-02  ⋯  0.108603552      -0.09679547  -0.260192104
682 1.474113e-02  7.649317e-06  ⋯  0.262177946      -0.26710151  -0.312572970
683 5.934817e-04  1.166801e-14  ⋯  0.250344936      -0.27606767  -0.457293407
684 1.727176e-03  1.015995e-10  ⋯  0.342354352      -0.36612474  -0.521250864
685 4.547931e-01  1.637097e-02  ⋯  0.039236516      -0.01157074  -0.091622413
686 1.000000e+00  6.784296e-01  ⋯  0.016353677       0.02983266  -0.007910015
687 1.000000e+00  8.128542e-01  ⋯ -0.001581084       0.02541791   0.049635856
688 3.443037e-06  9.939979e-22  ⋯ -0.701047582       0.77631490   1.181199579
689 1.804021e-01  3.477678e-03  ⋯ -0.128506663       0.14185774   0.222804150
690 2.856838e-07  6.446906e-23  ⋯  0.388186286      -0.41487322  -0.642824188
691 2.735420e-05  1.549159e-16  ⋯  0.597082590      -0.82559401  -1.667645384
692 3.258509e-06  1.800035e-19  ⋯ -0.401747588       0.45433344   0.609204905
    Acinar_5.diff not.Acinar_3 Acinar_3     Acinar_3.diff not.Acinar_4
1    0.18043576    0.37565291   0.40839287   0.032739964   0.36346805
2    0.23583726    0.58349083   0.57171637  -0.011774461   0.51572609
3   -0.31373919   -0.58512056  -0.40493006   0.180190501  -0.46521052
4    0.09473432    0.11512127   0.01296847  -0.102152791   0.06592540
5    0.04580514    0.04802604   0.09448791   0.046461871   0.07143713
6   -0.14712850   -0.31250140  -0.20176058   0.110740822  -0.23391655
7    0.11153482    0.16187921   0.08662911  -0.075250100   0.11966978
8    0.18026762    0.31537092   0.31243019  -0.002940737   0.29809079
9    0.03165197   -0.08887440  -0.09365701  -0.004782615  -0.06330595
10  -0.23038741   -0.42596028  -0.37126789   0.054692393  -0.37355125
11   0.03660858    0.12448934   0.13196784   0.007478502   0.11487461
12  -0.07838972   -0.16341602  -0.12809424   0.035321784  -0.12353057
13   0.06879855    0.03411748   0.05280358   0.018686103   0.05597898
14   0.04181494    0.04339210  -0.11866873  -0.162060824  -0.02293837
15  -0.34553315   -0.67658188  -0.34750305   0.329078832  -0.48318817
16  -0.39953222   -0.65445463  -0.34508124   0.309373389  -0.49126639
17   0.30041694    0.76998509   0.61275342  -0.157231673   0.62224642
18   0.26152033    0.65493301   0.55213646  -0.102796552   0.53124898
19  -0.03848762    0.05064722   0.05863724   0.007990024   0.03132287
20   0.27157359    0.80937161   0.55709609  -0.252275522   0.60758303
21  -0.29169046   -0.72065336  -0.47730968   0.243343685  -0.53551722
22   0.05056092    0.32786662   0.25628653  -0.071580097   0.24103290
23  -0.11930112   -0.21443967  -0.19992917   0.014510499  -0.19759337
24   0.04152876    0.04007367   0.10549646   0.065422789   0.07694360
25  -0.09125492   -0.20364361  -0.21068652  -0.007042910  -0.19135724
26  -0.05000502   -0.01807858  -0.06099529  -0.042916702  -0.04299102
27  -0.01341498    0.04120866   0.02562456  -0.015584096   0.01555395
28  -0.85754568   -1.48428356  -0.03698718   1.447296386  -0.80516835
29  -0.85079720   -1.46628268   0.05180716   1.518089845  -0.75980582
30   0.03971797   -0.03614717   0.02818115   0.064328312   0.01955432
⋮   ⋮             ⋮            ⋮            ⋮             ⋮
663 -0.216244413  -0.653094493 -0.510385278  0.142709215  -0.506684462
664  0.061199006   0.078580970  0.071563199 -0.007017772   0.079469983
665 -0.233365197  -0.724494719 -0.489897702  0.234597016  -0.525239737
666 -0.223578546  -0.596142255 -0.510928426  0.085213829  -0.494861424
667  0.103251108   0.349977071  0.258603909 -0.091373163   0.264222610
668  0.064286514   0.134843013  0.015844972 -0.118998041   0.070390330
669 -0.037542388   0.134246230  0.016692412 -0.117553818   0.048936410
670 -0.040249771   0.120674321  0.097075518 -0.023598803   0.070471714
671 -0.089589902  -0.136249198 -0.205526142 -0.069276944  -0.165018381
672 -0.293305888  -0.677614865 -0.438946106  0.238668759  -0.513834666
673  0.393380639   0.890368449  0.730175849 -0.160192600   0.738943540
674  0.003917927  -0.029919408 -0.044269631 -0.014350223  -0.032773120
675 -0.026489363  -0.091496231 -0.057863025  0.033633206  -0.059454064
676 -0.029595390  -0.186108969 -0.165509042  0.020599926  -0.142520104
677 -0.054206037  -0.269694646 -0.194597281  0.075097365  -0.194844700
678  0.023323746  -0.044447064 -0.007918274  0.036528790  -0.012092905
679 -0.466826522  -0.953794712 -0.670089794  0.283704917  -0.758502337
680  0.404106861   0.731392109  0.609286146 -0.122105963   0.631841244
681 -0.163396634  -0.141909399 -0.122704229  0.019205169  -0.146279628
682 -0.045471463  -0.300788983 -0.205388296  0.095400687  -0.199505000
683 -0.181225733  -0.357468902 -0.223154559  0.134314343  -0.272092948
684 -0.155126120  -0.432109565 -0.332728389  0.099381175  -0.335197337
685 -0.080051672  -0.069595434  0.072677000  0.142272434  -0.007544622
686 -0.037742679   0.003431117  0.057933096  0.054501979   0.026539928
687  0.024217943   0.020645879  0.040873666  0.020227787   0.038275868
688  0.404884677   0.942322132  0.696872685 -0.245449447   0.744628679
689  0.080946405   0.176524587  0.112056233 -0.064468355   0.132974795
690 -0.227950964  -0.516712523 -0.352385791  0.164326733  -0.393226055
691 -0.842051372  -1.395792396  0.005877241  1.401669637  -0.751942259
692  0.154871464   0.527864253  0.391119913 -0.136744340   0.397840313
    Acinar_4      Acinar_4.diff
1    0.449233452   0.08576540
2    0.780814962   0.26508887
3   -0.773251983  -0.30804147
4    0.151213805   0.08528841
5    0.019434045  -0.05200309
6   -0.451613101  -0.21769655
7    0.215342409   0.09567262
8    0.371014208   0.07292341
9   -0.176956520  -0.11365057
10  -0.539533557  -0.16598230
11   0.166317751   0.05144314
12  -0.243378818  -0.11984825
13  -0.009820532  -0.06579952
14   0.092146173   0.11508454
15  -0.940716062  -0.45752789
16  -0.835336498  -0.34407010
17   1.071973688   0.44972727
18   0.908253396   0.37700442
19   0.118367439   0.08704457
20   1.199161551   0.59157852
21  -1.038429660  -0.50291244
22   0.537919861   0.29688696
23  -0.250371669  -0.05277829
24  -0.012737034  -0.08968063
25  -0.245368623  -0.05401138
26   0.021036949   0.06402797
27   0.085682193   0.07012824
28  -2.125795470  -1.32062712
29  -2.114734845  -1.35492902
30  -0.135296556  -0.15485087
⋮   ⋮             ⋮
663 -0.9656292913 -0.458944829
664  0.0660341027 -0.013435880
665 -1.1064782428 -0.581238506
666 -0.8289148678 -0.334053444
667  0.5319612953  0.267738685
668  0.2117652759  0.141374946
669  0.2811572079  0.232220798
670  0.2486210413  0.178149327
671 -0.1289674616  0.036050919
672 -0.9495691093 -0.435734444
673  1.2053020584  0.466358519
674 -0.0382000493 -0.005426929
675 -0.1554181278 -0.095964063
676 -0.3031631983 -0.160643094
677 -0.4456572535 -0.250812553
678 -0.0937458028 -0.081652898
679 -1.2749624754 -0.516460138
680  0.9190237686  0.287182524
681 -0.1140217687  0.032257859
682 -0.5319990607 -0.332494061
683 -0.4845367817 -0.212443833
684 -0.6296564238 -0.294459087
685 -0.1119489151 -0.104404293
686  0.0001938061 -0.026346122
687  0.0132670568 -0.025008812
688  1.3141220841  0.569493405
689  0.2565516114  0.123576816
690 -0.7291834118 -0.335957357
691 -1.9698851874 -1.217942929
692  0.7995161167  0.401675804

In [15]:
# Determine which cluter the motif is most accessible in
maxes <- apply(X=type_anova_results_full_holm_anova_dev[acinar_labels], MARGIN=1, FUN=max)

maxes_labels <- maxes

maxes_labels[maxes_labels==type_anova_results_full_holm_anova_dev$Acinar_1_2_6] <- 'Acinar_1_2_6'
maxes_labels[maxes_labels==type_anova_results_full_holm_anova_dev$Acinar_3] <- 'Acinar_3'
maxes_labels[maxes_labels==type_anova_results_full_holm_anova_dev$Acinar_4] <- 'Acinar_4'
maxes_labels[maxes_labels==type_anova_results_full_holm_anova_dev$Acinar_5] <- 'Acinar_5'

#maxes_labels

type_anova_results_full_holm_anova_dev$max <- maxes_labels

type_anova_results_full_holm_anova_dev

    Motif                Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1   MA0030.1_FOXF2       1.878561e-06         7.161564e-03     4.033856e-01
2   MA0031.1_FOXD1       8.190823e-11         2.474089e-04     7.115261e-01
3   MA0051.1_IRF2        2.146152e-10         1.182946e-07     1.289029e-04
4   MA0059.1_MAX::MYC    7.680233e-03         1.116966e-01     1.326528e-03
5   MA0066.1_PPARG       3.355028e-01         2.115934e-01     2.765041e-01
6   MA0069.1_PAX6        1.016753e-06         6.478739e-03     1.245207e-03
7   MA0070.1_PBX1        1.950325e-04         1.071945e-01     5.157297e-02
8   MA0071.1_RORA        1.189834e-06         1.795454e-04     9.240308e-01
9   MA0072.1_RORA        2.290104e-02         5.710456e-01     8.850272e-01
10  MA0073.1_RREB1       3.818641e-14         9.717376e-07     3.100293e-02
11  MA0074.1_RXRA::VDR   1.073328e-02         3.464559e-01     8.185752e-01
12  MA0077.1_SOX9        1.148739e-06         1.596140e-01     3.392961e-01
13  MA0084.1_SRY         5.638107e-01         1.734758e-01     5.397903e-01
14  MA0091.1_TAL1::TCF3  6.786592e-01         3.385935e-01     2.267544e-05
15  MA0101.1_REL         2.541982e-09         4.897347e-07     5.214370e-07
16  MA0107.1_RELA        9.959064e-08         3.405388e-09     7.111582e-06
17  MA0115.1_NR1H2::RXRA 1.734276e-13         2.443042e-07     7.056164e-05
18  MA0119.1_NFIC::TLX1  8.563274e-12         1.179298e-02     3.999199e-02
19  MA0130.1_ZNF354C     1.037398e-01         5.226134e-01     8.563384e-01
20  MA0139.1_CTCF        2.041670e-09         1.396105e-04     3.421009e-06
21  MA0149.1_EWSR1-FLI1  5.260545e-13         1.524449e-05     1.571023e-06
22  MA0138.2_REST        8.457234e-08         1.902967e-01     4.586928e-02
23  MA0155.1_INSM1       3.461382e-05         2.474980e-02     5.818122e-01
24  MA0159.1_RARA::RXRA  3.580008e-01         3.894511e-01     2.043249e-02
25  MA0163.1_PLAG1       9.707800e-06         1.015805e-02     8.422183e-01
26  MA0259.1_ARNT::HIF1A 2.929046e-01         1.703781e-01     1.972743e-01
27  MA0468.1_DUX4        2.783004e-01         8.273214e-01     6.913247e-01
28  MA0476.1_FOS         1.218191e-04         1.334765e-06     1.712200e-11
29  MA0478.1_FOSL2       6.439040e-04         4.877339e-06     2.730887e-11
30  MA0479.1_FOXH1       2.555437e-01         4.439863e-01     3.401389e-02
⋮   ⋮                    ⋮                    ⋮                ⋮
663 MA0765.3_ETV5        1.299022e-13         2.288174e-04     9.844155e-04
664 MA0784.2_POU1F1      2.577133e-01         1.284384e-01     8.766635e-01
665 MA0798.3_RFX3        6.333756e-15         4.914809e-04     8.742749e-08
666 MA0799.2_RFX4        1.197942e-16         1.113793e-04     5.275652e-03
667 MA0818.2_BHLHE22     4.009071e-10         1.405053e-02     3.097819e-03
668 MA0819.2_CLOCK       2.129314e-02         4.805949e-02     1.923667e-03
669 MA0821.2_HES5        1.072833e-02         3.832327e-01     4.434327e-05
670 MA0828.2_SREBF2      1.053814e-03         3.483582e-01     5.075757e-01
671 MA0831.3_TFE3        3.006546e-03         5.758231e-02     1.730429e-02
672 MA0837.2_CEBPE       1.842437e-09         8.057534e-07     6.130090e-04
673 MA0847.3_FOXD2       1.937168e-14         5.903086e-07     1.699319e-05
674 MA0865.2_E2F8        5.907555e-01         9.248896e-01     5.773891e-01
675 MA0877.3_BARHL1      4.086280e-04         5.590938e-01     2.700637e-01
676 MA0878.3_CDX1        2.639327e-10         4.981164e-01     4.849249e-01
677 MA0879.2_DLX1        1.072301e-06         3.602499e-01     8.383289e-02
678 MA0884.2_DUXA        3.639946e-01         6.884185e-01     3.243642e-01
679 MA1483.2_ELF2        6.756606e-13         5.733928e-09     3.233385e-07
680 MA1487.2_FOXE1       1.749221e-12         7.534956e-08     1.487714e-03
681 MA1491.2_GLI3        1.298632e-03         1.980245e-03     5.581553e-01
682 MA1498.2_HOXA7       5.586005e-07         4.306392e-01     5.770647e-02
683 MA1511.2_KLF10       8.537181e-12         4.223534e-07     1.546485e-06
684 MA1525.2_NFATC4      6.243845e-08         3.940263e-04     3.482965e-03
685 MA1532.2_NR1D2       2.317577e-01         6.464799e-02     1.124279e-04
686 MA1547.2_PITX2       5.906593e-01         4.614179e-01     1.824823e-01
687 MA1563.2_SOX18       9.655773e-01         7.308639e-01     5.735175e-01
688 MA1566.2_TBX3        5.637909e-17         5.912457e-06     8.684939e-09
689 MA1601.2_ZNF75D      2.446000e-05         1.347379e-01     6.013402e-02
690 MA1630.2_ZNF281      1.590872e-17         1.421048e-05     1.189267e-07
691 MA1633.2_BACH1       4.730066e-04         3.208037e-07     6.128404e-11
692 MA0597.2_THAP1       1.971385e-15         4.360650e-04     8.464455e-07
    Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm
1   4.695431e-01     7.514245e-06      2.148469e-02  8.067713e-01
2   7.143876e-03     3.276329e-10      7.422268e-04  7.115261e-01
3   8.358103e-04     8.584606e-10      3.548837e-07  2.578058e-04
4   1.502414e-01     2.304070e-02      2.233933e-01  5.306112e-03
5   6.371728e-01     8.463736e-01      8.463736e-01  8.463736e-01
6   2.804430e-02     4.067012e-06      1.295748e-02  3.735622e-03
7   2.224225e-01     7.801299e-04      2.143890e-01  1.547189e-01
8   4.904732e-01     4.759337e-06      5.386362e-04  9.809463e-01
9   2.716860e-01     9.160417e-02      1.000000e+00  1.000000e+00
10  2.888602e-03     1.527457e-13      2.915213e-06  3.100293e-02
11  5.303483e-01     4.293310e-02      1.000000e+00  1.000000e+00
12  1.635705e-01     4.594956e-06      4.788419e-01  4.788419e-01
13  4.501992e-01     1.000000e+00      6.939031e-01  1.000000e+00
14  1.343084e-01     6.786592e-01      6.771870e-01  9.070177e-05
15  6.820878e-04     1.016793e-08      1.469204e-06  1.469204e-06
16  8.705353e-03     2.987719e-07      1.362155e-08  1.422316e-05
17  2.014495e-05     6.937104e-13      7.329125e-07  7.056164e-05
18  4.672273e-04     3.425310e-11      2.358597e-02  3.999199e-02
19  2.000563e-01     4.149592e-01      1.000000e+00  1.000000e+00
20  4.315427e-08     8.166680e-09      1.396105e-04  6.842018e-06
21  9.706877e-06     2.104218e-12      1.941375e-05  4.713068e-06
22  2.308168e-03     3.382893e-07      1.902967e-01  9.173857e-02
23  5.054334e-01     1.384553e-04      7.424940e-02  1.000000e+00
24  2.288113e-01     7.160016e-01      7.160016e-01  8.172995e-02
25  4.936582e-01     3.883120e-05      3.047414e-02  9.873165e-01
26  3.241069e-01     6.815124e-01      6.815124e-01  6.815124e-01
27  3.007253e-01     1.000000e+00      1.000000e+00  1.000000e+00
28  4.271062e-06     1.218191e-04      4.004294e-06  6.848799e-11
29  3.058844e-05     6.439040e-04      1.463202e-05  1.092355e-10
30  8.431619e-02     5.110874e-01      5.110874e-01  1.360556e-01
⋮   ⋮                ⋮                 ⋮             ⋮
663 2.202733e-05     5.196090e-13      4.576347e-04  9.844155e-04
664 8.939404e-01     7.731398e-01      5.137537e-01  1.000000e+00
665 6.087903e-07     2.533502e-14      4.914809e-04  2.622825e-07
666 2.650160e-05     4.791769e-16      2.227586e-04  5.275652e-03
667 9.808248e-04     1.603628e-09      1.405053e-02  6.195637e-03
668 8.452472e-02     6.387941e-02      9.611897e-02  7.694670e-03
669 1.285923e-03     2.145666e-02      3.832327e-01  1.773731e-04
670 3.215217e-02     4.215254e-03      6.967164e-01  6.967164e-01
671 5.973989e-01     1.202618e-02      1.151646e-01  5.191288e-02
672 6.386221e-06     7.369748e-09      2.417260e-06  6.130090e-04
673 5.711334e-06     7.748671e-14      1.770926e-06  1.699319e-05
674 9.599230e-01     1.000000e+00      1.000000e+00  1.000000e+00
675 1.108517e-01     1.634512e-03      5.590938e-01  5.401273e-01
676 1.847311e-03     1.055731e-09      9.698499e-01  9.698499e-01
677 4.021750e-03     4.289203e-06      3.602499e-01  1.676658e-01
678 2.998599e-01     1.000000e+00      1.000000e+00  1.000000e+00
679 2.520763e-05     2.702642e-12      1.720179e-08  6.466770e-07
680 8.561141e-04     6.996885e-12      2.260487e-07  1.712228e-03
681 6.816735e-01     5.194527e-03      5.940735e-03  1.000000e+00
682 4.913711e-03     2.234402e-06      4.306392e-01  1.154129e-01
683 5.934817e-04     3.414873e-11      1.267060e-06  3.092971e-06
684 8.635880e-04     2.497538e-07      1.182079e-03  3.482965e-03
685 2.273966e-01     4.547931e-01      1.939440e-01  4.497115e-04
686 6.635607e-01     1.000000e+00      1.000000e+00  7.299294e-01
687 4.425921e-01     1.000000e+00      1.000000e+00  1.000000e+00
688 1.721518e-06     2.255163e-16      5.912457e-06  2.605482e-08
689 8.175967e-02     9.783998e-05      1.804021e-01  1.804021e-01
690 9.522795e-08     6.363488e-17      1.421048e-05  2.856838e-07
691 1.367710e-05     4.730066e-04      9.624110e-07  2.451362e-10
692 1.629254e-06     7.885539e-15      4.360650e-04  2.539337e-06
    Acinar_4.holm anova.p.value ⋯ not.Acinar_5 Acinar_5     Acinar_5.diff
1   8.067713e-01  6.959097e-04  ⋯  0.33699151   0.51742727   0.18043576
2   1.428775e-02  1.307808e-11  ⋯  0.51777387   0.75361113   0.23583726
3   8.358103e-04  1.554499e-14  ⋯ -0.45760182  -0.77134101  -0.31373919
4   2.233933e-01  1.119976e-02  ⋯  0.06217336   0.15690768   0.09473432
5   8.463736e-01  6.430220e-01  ⋯  0.04754416   0.09334931   0.04580514
6   2.804430e-02  5.950115e-06  ⋯ -0.24760523  -0.39473373  -0.14712850
7   2.224225e-01  1.918401e-02  ⋯  0.11429194   0.22582676   0.11153482
8   9.809463e-01  2.142472e-04  ⋯  0.26911233   0.44937995   0.18026762
9   8.150579e-01  2.645968e-01  ⋯ -0.09834624  -0.06669427   0.03165197
10  5.777204e-03  5.716259e-16  ⋯ -0.35431073  -0.58469814  -0.23038741
11  1.000000e+00  2.774748e-01  ⋯  0.11812177   0.15473034   0.03660858
12  4.788419e-01  9.918394e-03  ⋯ -0.13141035  -0.20980007  -0.07838972
13  1.000000e+00  4.798476e-01  ⋯  0.02189180   0.09069035   0.06879855
14  4.029253e-01  5.473538e-03  ⋯ -0.00591125   0.03590369   0.04181494
15  6.820878e-04  4.448564e-13  ⋯ -0.50510687  -0.85064002  -0.34553315
16  8.705353e-03  3.429995e-11  ⋯ -0.47249238  -0.87202460  -0.39953222
17  4.028990e-05  3.358351e-19  ⋯  0.65333636   0.95375330   0.30041694
18  1.401682e-03  3.660158e-11  ⋯  0.55409177   0.81561210   0.26152033
19  6.001689e-01  3.519829e-01  ⋯  0.06123471   0.02274709  -0.03848762
20  1.294628e-07  1.149990e-18  ⋯  0.67601122   0.94758482   0.27157359
21  1.941375e-05  5.515180e-18  ⋯ -0.58098553  -0.87267599  -0.29169046
22  6.924503e-03  1.246399e-07  ⋯  0.29816160   0.34872252   0.05056092
23  1.000000e+00  9.581397e-03  ⋯ -0.17959365  -0.29889477  -0.11930112
24  6.864340e-01  1.820580e-01  ⋯  0.04530624   0.08683500   0.04152876
25  9.873165e-01  1.458527e-02  ⋯ -0.18060447  -0.27185939  -0.09125492
26  6.815124e-01  2.702757e-01  ⋯ -0.01413027  -0.06413530  -0.05000502
27  1.000000e+00  5.217170e-01  ⋯  0.03582684   0.02241186  -0.01341498
28  8.542124e-06  1.857219e-17  ⋯ -0.89902120  -1.75656688  -0.85754568
29  6.117688e-05  1.956239e-15  ⋯ -0.86368564  -1.71448283  -0.85079720
30  2.529486e-01  5.818325e-02  ⋯ -0.02787386   0.01184411   0.03971797
⋮   ⋮             ⋮             ⋱ ⋮            ⋮            ⋮
663 6.608198e-05  2.703367e-16  ⋯ -0.56172465  -0.777969064 -0.216244413
664 1.000000e+00  6.987476e-01  ⋯  0.06097531   0.122174319  0.061199006
665 1.217581e-06  7.694154e-20  ⋯ -0.60473650  -0.838101694 -0.233365197
666 7.950481e-05  9.487104e-18  ⋯ -0.51797508  -0.741553630 -0.223578546
667 2.942474e-03  8.984012e-10  ⋯  0.30150463   0.404755739  0.103251108
668 9.611897e-02  3.920143e-03  ⋯  0.08814835   0.152434866  0.064286514
669 3.857769e-03  6.605534e-06  ⋯  0.11500076   0.077458370 -0.037542388
670 9.645650e-02  4.612753e-03  ⋯  0.12273060   0.082480832 -0.040249771
671 5.973989e-01  4.339513e-02  ⋯ -0.13376645  -0.223356351 -0.089589902
672 1.277244e-05  2.290423e-15  ⋯ -0.54303572  -0.836341611 -0.293305888
673 1.142267e-05  1.710207e-21  ⋯  0.74878661   1.142167246  0.393380639
674 1.000000e+00  9.855639e-01  ⋯ -0.03533526  -0.031417333  0.003917927
675 3.325552e-01  4.740575e-02  ⋯ -0.07566826  -0.102157624 -0.026489363
676 5.541934e-03  7.547976e-06  ⋯ -0.17248164  -0.202077029 -0.029595390
677 1.206525e-02  2.008646e-05  ⋯ -0.24053266  -0.294738697 -0.054206037
678 1.000000e+00  4.627805e-01  ⋯ -0.03737654  -0.014052794  0.023323746
679 2.520763e-05  3.279196e-20  ⋯ -0.76248338  -1.229309897 -0.466826522
680 1.712228e-03  5.497418e-18  ⋯  0.59599195   1.000098808  0.404106861
681 1.000000e+00  2.074299e-02  ⋯ -0.09679547  -0.260192104 -0.163396634
682 1.474113e-02  7.649317e-06  ⋯ -0.26710151  -0.312572970 -0.045471463
683 5.934817e-04  1.166801e-14  ⋯ -0.27606767  -0.457293407 -0.181225733
684 1.727176e-03  1.015995e-10  ⋯ -0.36612474  -0.521250864 -0.155126120
685 4.547931e-01  1.637097e-02  ⋯ -0.01157074  -0.091622413 -0.080051672
686 1.000000e+00  6.784296e-01  ⋯  0.02983266  -0.007910015 -0.037742679
687 1.000000e+00  8.128542e-01  ⋯  0.02541791   0.049635856  0.024217943
688 3.443037e-06  9.939979e-22  ⋯  0.77631490   1.181199579  0.404884677
689 1.804021e-01  3.477678e-03  ⋯  0.14185774   0.222804150  0.080946405
690 2.856838e-07  6.446906e-23  ⋯ -0.41487322  -0.642824188 -0.227950964
691 2.735420e-05  1.549159e-16  ⋯ -0.82559401  -1.667645384 -0.842051372
692 3.258509e-06  1.800035e-19  ⋯  0.45433344   0.609204905  0.154871464
    not.Acinar_3 Acinar_3     Acinar_3.diff not.Acinar_4 Acinar_4
1    0.37565291   0.40839287   0.032739964   0.36346805   0.449233452
2    0.58349083   0.57171637  -0.011774461   0.51572609   0.780814962
3   -0.58512056  -0.40493006   0.180190501  -0.46521052  -0.773251983
4    0.11512127   0.01296847  -0.102152791   0.06592540   0.151213805
5    0.04802604   0.09448791   0.046461871   0.07143713   0.019434045
6   -0.31250140  -0.20176058   0.110740822  -0.23391655  -0.451613101
7    0.16187921   0.08662911  -0.075250100   0.11966978   0.215342409
8    0.31537092   0.31243019  -0.002940737   0.29809079   0.371014208
9   -0.08887440  -0.09365701  -0.004782615  -0.06330595  -0.176956520
10  -0.42596028  -0.37126789   0.054692393  -0.37355125  -0.539533557
11   0.12448934   0.13196784   0.007478502   0.11487461   0.166317751
12  -0.16341602  -0.12809424   0.035321784  -0.12353057  -0.243378818
13   0.03411748   0.05280358   0.018686103   0.05597898  -0.009820532
14   0.04339210  -0.11866873  -0.162060824  -0.02293837   0.092146173
15  -0.67658188  -0.34750305   0.329078832  -0.48318817  -0.940716062
16  -0.65445463  -0.34508124   0.309373389  -0.49126639  -0.835336498
17   0.76998509   0.61275342  -0.157231673   0.62224642   1.071973688
18   0.65493301   0.55213646  -0.102796552   0.53124898   0.908253396
19   0.05064722   0.05863724   0.007990024   0.03132287   0.118367439
20   0.80937161   0.55709609  -0.252275522   0.60758303   1.199161551
21  -0.72065336  -0.47730968   0.243343685  -0.53551722  -1.038429660
22   0.32786662   0.25628653  -0.071580097   0.24103290   0.537919861
23  -0.21443967  -0.19992917   0.014510499  -0.19759337  -0.250371669
24   0.04007367   0.10549646   0.065422789   0.07694360  -0.012737034
25  -0.20364361  -0.21068652  -0.007042910  -0.19135724  -0.245368623
26  -0.01807858  -0.06099529  -0.042916702  -0.04299102   0.021036949
27   0.04120866   0.02562456  -0.015584096   0.01555395   0.085682193
28  -1.48428356  -0.03698718   1.447296386  -0.80516835  -2.125795470
29  -1.46628268   0.05180716   1.518089845  -0.75980582  -2.114734845
30  -0.03614717   0.02818115   0.064328312   0.01955432  -0.135296556
⋮   ⋮            ⋮            ⋮             ⋮            ⋮
663 -0.653094493 -0.510385278  0.142709215  -0.506684462 -0.9656292913
664  0.078580970  0.071563199 -0.007017772   0.079469983  0.0660341027
665 -0.724494719 -0.489897702  0.234597016  -0.525239737 -1.1064782428
666 -0.596142255 -0.510928426  0.085213829  -0.494861424 -0.8289148678
667  0.349977071  0.258603909 -0.091373163   0.264222610  0.5319612953
668  0.134843013  0.015844972 -0.118998041   0.070390330  0.2117652759
669  0.134246230  0.016692412 -0.117553818   0.048936410  0.2811572079
670  0.120674321  0.097075518 -0.023598803   0.070471714  0.2486210413
671 -0.136249198 -0.205526142 -0.069276944  -0.165018381 -0.1289674616
672 -0.677614865 -0.438946106  0.238668759  -0.513834666 -0.9495691093
673  0.890368449  0.730175849 -0.160192600   0.738943540  1.2053020584
674 -0.029919408 -0.044269631 -0.014350223  -0.032773120 -0.0382000493
675 -0.091496231 -0.057863025  0.033633206  -0.059454064 -0.1554181278
676 -0.186108969 -0.165509042  0.020599926  -0.142520104 -0.3031631983
677 -0.269694646 -0.194597281  0.075097365  -0.194844700 -0.4456572535
678 -0.044447064 -0.007918274  0.036528790  -0.012092905 -0.0937458028
679 -0.953794712 -0.670089794  0.283704917  -0.758502337 -1.2749624754
680  0.731392109  0.609286146 -0.122105963   0.631841244  0.9190237686
681 -0.141909399 -0.122704229  0.019205169  -0.146279628 -0.1140217687
682 -0.300788983 -0.205388296  0.095400687  -0.199505000 -0.5319990607
683 -0.357468902 -0.223154559  0.134314343  -0.272092948 -0.4845367817
684 -0.432109565 -0.332728389  0.099381175  -0.335197337 -0.6296564238
685 -0.069595434  0.072677000  0.142272434  -0.007544622 -0.1119489151
686  0.003431117  0.057933096  0.054501979   0.026539928  0.0001938061
687  0.020645879  0.040873666  0.020227787   0.038275868  0.0132670568
688  0.942322132  0.696872685 -0.245449447   0.744628679  1.3141220841
689  0.176524587  0.112056233 -0.064468355   0.132974795  0.2565516114
690 -0.516712523 -0.352385791  0.164326733  -0.393226055 -0.7291834118
691 -1.395792396  0.005877241  1.401669637  -0.751942259 -1.9698851874
692  0.527864253  0.391119913 -0.136744340   0.397840313  0.7995161167
    Acinar_4.diff max
1    0.08576540   Acinar_5
2    0.26508887   Acinar_4
3   -0.30804147   Acinar_1_2_6
4    0.08528841   Acinar_5
5   -0.05200309   Acinar_3
6   -0.21769655   Acinar_1_2_6
7    0.09567262   Acinar_5
8    0.07292341   Acinar_5
9   -0.11365057   Acinar_1_2_6
10  -0.16598230   Acinar_1_2_6
11   0.05144314   Acinar_4
12  -0.11984825   Acinar_1_2_6
13  -0.06579952   Acinar_5
14   0.11508454   Acinar_4
15  -0.45752789   Acinar_1_2_6
16  -0.34407010   Acinar_1_2_6
17   0.44972727   Acinar_4
18   0.37700442   Acinar_4
19   0.08704457   Acinar_4
20   0.59157852   Acinar_4
21  -0.50291244   Acinar_1_2_6
22   0.29688696   Acinar_4
23  -0.05277829   Acinar_1_2_6
24  -0.08968063   Acinar_3
25  -0.05401138   Acinar_1_2_6
26   0.06402797   Acinar_4
27   0.07012824   Acinar_4
28  -1.32062712   Acinar_3
29  -1.35492902   Acinar_3
30  -0.15485087   Acinar_3
⋮   ⋮             ⋮
663 -0.458944829  Acinar_1_2_6
664 -0.013435880  Acinar_5
665 -0.581238506  Acinar_1_2_6
666 -0.334053444  Acinar_1_2_6
667  0.267738685  Acinar_4
668  0.141374946  Acinar_4
669  0.232220798  Acinar_4
670  0.178149327  Acinar_4
671  0.036050919  Acinar_1_2_6
672 -0.435734444  Acinar_1_2_6
673  0.466358519  Acinar_4
674 -0.005426929  Acinar_1_2_6
675 -0.095964063  Acinar_1_2_6
676 -0.160643094  Acinar_1_2_6
677 -0.250812553  Acinar_1_2_6
678 -0.081652898  Acinar_3
679 -0.516460138  Acinar_1_2_6
680  0.287182524  Acinar_5
681  0.032257859  Acinar_1_2_6
682 -0.332494061  Acinar_1_2_6
683 -0.212443833  Acinar_1_2_6
684 -0.294459087  Acinar_1_2_6
685 -0.104404293  Acinar_3
686 -0.026346122  Acinar_3
687 -0.025008812  Acinar_5
688  0.569493405  Acinar_4
689  0.123576816  Acinar_4
690 -0.335957357  Acinar_1_2_6
691 -1.217942929  Acinar_3
692  0.401675804  Acinar_4

In [16]:
# Number of Motifs significant from holm's and overall anova
paste0("Acinar_basal motifs passing holms & anova FDR: ", sum(type_anova_results_full_holm_anova_dev$Acinar_1_2_6.holm < 0.05 & type_anova_results_full_holm_anova_dev$anova.q.value < .05))
paste0("Acinar_signaling_1 motifs passing holms & anova FDR: ", sum(type_anova_results_full_holm_anova_dev$Acinar_3.holm < 0.05 & type_anova_results_full_holm_anova_dev$anova.q.value < .05))
paste0("Acinar_secreting motifs passing holms & anova FDR: ", sum(type_anova_results_full_holm_anova_dev$Acinar_4.holm < 0.05 & type_anova_results_full_holm_anova_dev$anova.q.value < .05))
paste0("Acinar_signaling_2 motifs passing holms & anova FDR: ", sum(type_anova_results_full_holm_anova_dev$Acinar_5.holm < 0.05 & type_anova_results_full_holm_anova_dev$anova.q.value < .05))

[1] "Acinar_basal motifs passing holms & anova FDR: 523"

[1] "Acinar_signaling_1 motifs passing holms & anova FDR: 343"

[1] "Acinar_secreting motifs passing holms & anova FDR: 345"

[1] "Acinar_signaling_2 motifs passing holms & anova FDR: 349"

In [17]:
# Number of Motifs significant from holm's and overall anova and positively enriched
paste0("Acinar_basal motifs passing holms & anova FDR & positively enriched: ", 
       sum(type_anova_results_full_holm_anova_dev$Acinar_1_2_6.holm < 0.05 & 
           type_anova_results_full_holm_anova_dev$anova.q.value < .05 & 
           type_anova_results_full_holm_anova_dev$Acinar_1_2_6.diff > 0))
paste0("Acinar_signaling_1 motifs passing holms & anova FDR & positively enriched: ", 
       sum(type_anova_results_full_holm_anova_dev$Acinar_3.holm < 0.05 & 
           type_anova_results_full_holm_anova_dev$anova.q.value < .05 & 
           type_anova_results_full_holm_anova_dev$Acinar_3.diff > 0))
paste0("Acinar_secreting motifs passing holms & anova FDR & positively enriched: ", 
       sum(type_anova_results_full_holm_anova_dev$Acinar_4.holm < 0.05 & 
           type_anova_results_full_holm_anova_dev$anova.q.value < .05 & 
           type_anova_results_full_holm_anova_dev$Acinar_4.diff > 0))
paste0("Acinar_signaling_2 motifs passing holms & anova FDR & positively enriched: ", 
       sum(type_anova_results_full_holm_anova_dev$Acinar_5.holm < 0.05 & 
           type_anova_results_full_holm_anova_dev$anova.q.value < .05 & 
           type_anova_results_full_holm_anova_dev$Acinar_5.diff > 0))

[1] "Acinar_basal motifs passing holms & anova FDR & positively enriched: 334"

[1] "Acinar_signaling_1 motifs passing holms & anova FDR & positively enriched: 221"

[1] "Acinar_secreting motifs passing holms & anova FDR & positively enriched: 127"

[1] "Acinar_signaling_2 motifs passing holms & anova FDR & positively enriched: 127"

In [18]:
# Number of Motifs significant from holm's and overall anova and max deviation score in a given cluster
paste0("Acinar_basal motifs passing holms & anova FDR & greatest in subtype: ", 
       sum(type_anova_results_full_holm_anova_dev$Acinar_1_2_6.holm < 0.05 & 
           type_anova_results_full_holm_anova_dev$anova.q.value < .05 & 
           type_anova_results_full_holm_anova_dev$max == 'Acinar_1_2_6'))
paste0("Acinar_signaling_1 motifs passing holms & anova FDR & greatest in subtype: ", 
       sum(type_anova_results_full_holm_anova_dev$Acinar_3.holm < 0.05 & 
           type_anova_results_full_holm_anova_dev$anova.q.value < .05 & 
           type_anova_results_full_holm_anova_dev$max == 'Acinar_3'))
paste0("Acinar_secreting motifs passing holms & anova FDR & greatest in subtype: ", 
       sum(type_anova_results_full_holm_anova_dev$Acinar_4.holm < 0.05 & 
           type_anova_results_full_holm_anova_dev$anova.q.value < .05 & 
           type_anova_results_full_holm_anova_dev$max == 'Acinar_4'))
paste0("Acinar_signaling_2 motifs passing holms & anova FDR & greatest in subtype: ", 
       sum(type_anova_results_full_holm_anova_dev$Acinar_5.holm < 0.05 & 
           type_anova_results_full_holm_anova_dev$anova.q.value < .05 & 
           type_anova_results_full_holm_anova_dev$max == 'Acinar_5'))

[1] "Acinar_basal motifs passing holms & anova FDR & greatest in subtype: 295"

[1] "Acinar_signaling_1 motifs passing holms & anova FDR & greatest in subtype: 53"

[1] "Acinar_secreting motifs passing holms & anova FDR & greatest in subtype: 115"

[1] "Acinar_signaling_2 motifs passing holms & anova FDR & greatest in subtype: 40"

In [19]:
# Top hits by holm's significance
head(arrange(type_anova_results_full_holm_anova_dev, Acinar_1_2_6.holm), n=15)
head(arrange(type_anova_results_full_holm_anova_dev, Acinar_3.holm), n=15)
head(arrange(type_anova_results_full_holm_anova_dev, Acinar_4.holm), n=15)
head(arrange(type_anova_results_full_holm_anova_dev, Acinar_5.holm), n=15)

   Motif                Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1  MA0592.3_ESRRA       7.291057e-20         4.999179e-09     4.963146e-10
2  MA0522.3_TCF3        7.807799e-20         4.058820e-09     1.232217e-09
3  MA1559.1_SNAI3       8.164321e-20         7.540437e-09     6.905179e-12
4  MA0745.2_SNAI2       8.832115e-20         8.553561e-10     3.539203e-15
5  MA1935.1_ERF::FOXI1  9.486416e-20         4.418449e-15     5.980277e-11
6  MA1558.1_SNAI1       1.223894e-19         4.951820e-09     2.315334e-11
7  MA0103.3_ZEB1        1.574728e-19         2.689590e-10     2.472934e-10
8  MA0762.1_ETV2        1.698016e-19         2.254607e-12     2.132797e-13
9  MA1648.1_TCF12       2.081354e-19         1.188093e-08     3.195115e-09
10 MA1631.1_ASCL1       4.326072e-19         1.965950e-09     9.486600e-10
11 MA1957.1_HOXB2::ELK1 4.588299e-19         1.687890e-05     1.219505e-03
12 MA1950.1_FLI1::FOXI1 4.893387e-19         2.559704e-12     1.730355e-11
13 MA0076.2_ELK4        4.948097e-19         7.062845e-09     9.144070e-08
14 MA0820.1_FIGLA       1.264630e-18         1.104855e-11     3.439739e-14
15 MA0475.2_FLI1        1.314674e-18         3.541591e-09     3.262911e-08
   Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1  1.192519e-11     2.916423e-19      4.999179e-09  9.926293e-10  3.577556e-11
2  8.678717e-13     3.123120e-19      4.058820e-09  2.464434e-09  2.603615e-12
3  5.997740e-13     3.265728e-19      7.540437e-09  1.381036e-11  1.799322e-12
4  7.046577e-15     3.532846e-19      8.553561e-10  1.061761e-14  1.409315e-14
5  1.531661e-09     3.794566e-19      1.325535e-14  1.196055e-10  1.531661e-09
6  3.311749e-12     4.895578e-19      4.951820e-09  4.630669e-11  9.935248e-12
7  3.423745e-15     6.298912e-19      4.945867e-10  4.945867e-10  1.027123e-14
8  7.083345e-10     6.792064e-19      4.509213e-12  6.398392e-13  7.083345e-10
9  1.106954e-11     8.325415e-19      1.188093e-08  6.390230e-09  3.320862e-11
10 5.352134e-13     1.730429e-18      1.965950e-09  1.897320e-09  1.605640e-12
11 1.694385e-07     1.835320e-18      3.375781e-05  1.219505e-03  5.083155e-07
12 5.151576e-10     1.957355e-18      7.679112e-12  3.460709e-11  5.151576e-10
13 1.123998e-10     1.979239e-18      1.412569e-08  9.144070e-08  3.371993e-10
14 5.048727e-11     5.058522e-18      2.209710e-11  1.031922e-13  5.048727e-11
15 4.439355e-09     5.258697e-18      1.062477e-08  3.262911e-08  1.062477e-08
   anova.p.value ⋯ not.Acinar_5 Acinar_5   Acinar_5.diff not.Acinar_3
1  1.177175e-36  ⋯  1.4851467    2.1205658  0.6354192     1.7271209
2  5.413610e-37  ⋯  2.1415102    3.1208336  0.9793234     2.5592279
3  1.195929e-37  ⋯  2.4584340    3.5791786  1.1207447     2.9600018
4  3.368285e-42  ⋯  2.4043512    3.4802458  1.0758946     2.8764374
5  1.315011e-37  ⋯ -1.5273116   -2.4015425 -0.8742309    -1.8522838
6  1.292575e-36  ⋯  2.3981229    3.5696414  1.1715185     2.9080490
7  2.124091e-41  ⋯  2.3721703    3.4089431  1.0367728     2.8108584
8  1.184151e-36  ⋯ -1.1390021   -1.7888625 -0.6498604    -1.3888046
9  9.913070e-35  ⋯  2.0172381    2.8897298  0.8724918     2.3942250
10 5.863048e-37  ⋯  2.2543412    3.3300586  1.0757174     2.7142743
11 3.902140e-22  ⋯ -0.6419938   -0.9710495 -0.3290556    -0.7675258
12 5.544068e-36  ⋯ -1.4387260   -2.2222027 -0.7834767    -1.7408513
13 1.088123e-32  ⋯ -1.1258931   -1.6713416 -0.5454485    -1.3424968
14 7.120192e-37  ⋯  1.9833281    2.9388179  0.9554897     2.3893966
15 1.087778e-30  ⋯ -0.8860290   -1.3264733 -0.4404444    -1.0589761
   Acinar_3   Acinar_3.diff not.Acinar_4 Acinar_4  Acinar_4.diff max
1   1.4155946 -0.3115263     1.3936511    2.462370  1.0687186    Acinar_4
2   1.9062310 -0.6529969     1.9948947    3.666486  1.6715909    Acinar_4
3   2.1244986 -0.8355032     2.2668351    4.279997  2.0131617    Acinar_4
4   2.1061475 -0.7702898     2.2150132    4.169983  1.9549703    Acinar_4
5  -1.4461984  0.4060854    -1.5193095   -2.492287 -0.9729771    Acinar_1_2_6
6   2.1001217 -0.8079273     2.2490586    4.136897  1.8878384    Acinar_4
7   2.1226393 -0.6882191     2.1942331    4.058333  1.8640995    Acinar_4
8  -1.0597060  0.3290985    -1.1240855   -1.884181 -0.7600950    Acinar_1_2_6
9   1.7880537 -0.6061713     1.8593418    3.463329  1.6039869    Acinar_4
10  1.9933736 -0.7209008     2.1144846    3.861668  1.7471839    Acinar_4
11 -0.6149673  0.1525584    -0.6225182   -1.061221 -0.4387023    Acinar_1_2_6
12 -1.3352937  0.4055575    -1.4096676   -2.374837 -0.9651693    Acinar_1_2_6
13 -1.0395699  0.3029269    -1.0783878   -1.865350 -0.7869621    Acinar_1_2_6
14  1.7487158 -0.6406808     1.8680009    3.383106  1.5151054    Acinar_4
15 -0.8215709  0.2374052    -0.8486632   -1.478845 -0.6301820    Acinar_1_2_6

   Motif                Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1  MA0745.2_SNAI2       8.832115e-20         8.553561e-10     3.539203e-15
2  MA0820.1_FIGLA       1.264630e-18         1.104855e-11     3.439739e-14
3  MA1529.1_NHLH2       1.749667e-15         2.003972e-07     6.815149e-14
4  MA0762.1_ETV2        1.698016e-19         2.254607e-12     2.132797e-13
5  MA0499.2_MYOD1       7.702942e-18         6.171311e-12     6.802537e-13
6  MA1953.1_FOXO1::ELF1 2.578432e-17         3.474334e-12     3.390180e-12
7  MA1559.1_SNAI3       8.164321e-20         7.540437e-09     6.905179e-12
8  MA1418.1_IRF3        3.088693e-14         2.587724e-11     9.863483e-12
9  MA1950.1_FLI1::FOXI1 4.893387e-19         2.559704e-12     1.730355e-11
10 MA1641.1_MYF5        1.365451e-10         3.145863e-08     1.014212e-11
11 MA0462.2_BATF::JUN   1.020715e-04         1.688774e-06     1.084321e-11
12 MA1558.1_SNAI1       1.223894e-19         4.951820e-09     2.315334e-11
13 MA1634.1_BATF        7.126106e-05         1.089571e-06     1.161588e-11
14 MA1100.2_ASCL1       4.060940e-14         1.697679e-11     2.371063e-11
15 MA0835.2_BATF3       6.112197e-05         6.253501e-07     1.338889e-11
   Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1  7.046577e-15     3.532846e-19      8.553561e-10  1.061761e-14  1.409315e-14
2  5.048727e-11     5.058522e-18      2.209710e-11  1.031922e-13  5.048727e-11
3  4.192719e-12     6.998669e-15      2.003972e-07  2.044545e-13  8.385439e-12
4  7.083345e-10     6.792064e-19      4.509213e-12  6.398392e-13  7.083345e-10
5  1.712024e-12     3.081177e-17      6.171311e-12  2.040761e-12  3.424049e-12
6  3.360350e-10     1.031373e-16      1.017054e-11  1.017054e-11  3.360350e-10
7  5.997740e-13     3.265728e-19      7.540437e-09  1.381036e-11  1.799322e-12
8  1.723592e-05     1.235477e-13      5.175447e-11  2.959045e-11  1.723592e-05
9  5.151576e-10     1.957355e-18      7.679112e-12  3.460709e-11  5.151576e-10
10 1.288082e-06     4.096354e-10      6.291727e-08  4.056850e-11  1.288082e-06
11 4.713687e-06     1.020715e-04      5.066322e-06  4.337286e-11  9.427373e-06
12 3.311749e-12     4.895578e-19      4.951820e-09  4.630669e-11  9.935248e-12
13 6.433320e-06     7.126106e-05      3.268713e-06  4.646354e-11  1.286664e-05
14 1.961180e-08     1.624376e-13      5.093036e-11  5.093036e-11  1.961180e-08
15 3.340559e-06     6.112197e-05      1.876050e-06  5.355558e-11  6.681119e-06
   anova.p.value ⋯ not.Acinar_5 Acinar_5   Acinar_5.diff not.Acinar_3
1  3.368285e-42  ⋯  2.4043512    3.4802458  1.0758946     2.8764374
2  7.120192e-37  ⋯  1.9833281    2.9388179  0.9554897     2.3893966
3  4.587000e-33  ⋯  0.6982516    1.0150484  0.3167969     0.8702506
4  1.184151e-36  ⋯ -1.1390021   -1.7888625 -0.6498604    -1.3888046
5  2.640159e-38  ⋯  1.7903112    2.6865896  0.8962785     2.1801882
6  6.465642e-35  ⋯ -1.0508772   -1.6278010 -0.5769238    -1.2777848
7  1.195929e-37  ⋯  2.4584340    3.5791786  1.1207447     2.9600018
8  2.274496e-24  ⋯ -0.7470256   -1.2479890 -0.5009634    -0.9361842
9  5.544068e-36  ⋯ -1.4387260   -2.2222027 -0.7834767    -1.7408513
10 2.941805e-21  ⋯  0.5321287    0.8973619  0.3652332     0.7073987
11 2.015332e-17  ⋯ -0.8852479   -1.6956444 -0.8103965    -1.4432730
12 1.292575e-36  ⋯  2.3981229    3.5696414  1.1715185     2.9080490
13 2.217783e-17  ⋯ -0.8919592   -1.7259112 -0.8339520    -1.4512261
14 1.749907e-28  ⋯  0.9372052    1.5150459  0.5778407     1.1954500
15 5.300354e-18  ⋯ -0.8561657   -1.6592256 -0.8030598    -1.3952824
   Acinar_3    Acinar_3.diff not.Acinar_4 Acinar_4   Acinar_4.diff max
1   2.10614753 -0.7702898     2.2150132    4.1699835  1.9549703    Acinar_4
2   1.74871576 -0.6406808     1.8680009    3.3831063  1.5151054    Acinar_4
3   0.51417624 -0.3560744     0.6088347    1.3248681  0.7160334    Acinar_4
4  -1.05970604  0.3290985    -1.1240855   -1.8841806 -0.7600950    Acinar_1_2_6
5   1.53458054 -0.6456077     1.6744371    3.1255585  1.4511214    Acinar_4
6  -0.95141255  0.3263722    -1.0263564   -1.7479433 -0.7215869    Acinar_1_2_6
7   2.12449856 -0.8355032     2.2668351    4.2799968  2.0131617    Acinar_4
8  -0.69175126  0.2444329    -0.7617550   -1.2389426 -0.4771876    Acinar_1_2_6
9  -1.33529374  0.4055575    -1.4096676   -2.3748369 -0.9651693    Acinar_1_2_6
10  0.38295537 -0.3244433     0.5126553    0.9841608  0.4715055    Acinar_4
11 -0.05732171  1.3859513    -0.7883377   -2.0702210 -1.2818833    Acinar_3
12  2.10012170 -0.8079273     2.2490586    4.1368971  1.8878384    Acinar_4
13 -0.08659045  1.3646357    -0.8104452   -2.0528573 -1.2424121    Acinar_3
14  0.75432330 -0.4411267     0.9063638    1.6565868  0.7502231    Acinar_4
15 -0.07800596  1.3172764    -0.7769664   -1.9767465 -1.1997801    Acinar_3

   Motif                Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1  MA0103.3_ZEB1        1.574728e-19         2.689590e-10     2.472934e-10
2  MA0745.2_SNAI2       8.832115e-20         8.553561e-10     3.539203e-15
3  MA1631.1_ASCL1       4.326072e-19         1.965950e-09     9.486600e-10
4  MA1559.1_SNAI3       8.164321e-20         7.540437e-09     6.905179e-12
5  MA0522.3_TCF3        7.807799e-20         4.058820e-09     1.232217e-09
6  MA0499.2_MYOD1       7.702942e-18         6.171311e-12     6.802537e-13
7  MA0830.2_TCF4        3.758440e-18         4.265788e-08     1.979291e-10
8  MA1529.1_NHLH2       1.749667e-15         2.003972e-07     6.815149e-14
9  MA1558.1_SNAI1       1.223894e-19         4.951820e-09     2.315334e-11
10 MA1648.1_TCF12       2.081354e-19         1.188093e-08     3.195115e-09
11 MA0592.3_ESRRA       7.291057e-20         4.999179e-09     4.963146e-10
12 MA0820.1_FIGLA       1.264630e-18         1.104855e-11     3.439739e-14
13 MA0750.2_ZBTB7A      2.012863e-18         1.607868e-07     2.186183e-08
14 MA1953.1_FOXO1::ELF1 2.578432e-17         3.474334e-12     3.390180e-12
15 MA0076.2_ELK4        4.948097e-19         7.062845e-09     9.144070e-08
   Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1  3.423745e-15     6.298912e-19      4.945867e-10  4.945867e-10  1.027123e-14
2  7.046577e-15     3.532846e-19      8.553561e-10  1.061761e-14  1.409315e-14
3  5.352134e-13     1.730429e-18      1.965950e-09  1.897320e-09  1.605640e-12
4  5.997740e-13     3.265728e-19      7.540437e-09  1.381036e-11  1.799322e-12
5  8.678717e-13     3.123120e-19      4.058820e-09  2.464434e-09  2.603615e-12
6  1.712024e-12     3.081177e-17      6.171311e-12  2.040761e-12  3.424049e-12
7  2.728476e-12     1.503376e-17      4.265788e-08  3.958583e-10  8.185429e-12
8  4.192719e-12     6.998669e-15      2.003972e-07  2.044545e-13  8.385439e-12
9  3.311749e-12     4.895578e-19      4.951820e-09  4.630669e-11  9.935248e-12
10 1.106954e-11     8.325415e-19      1.188093e-08  6.390230e-09  3.320862e-11
11 1.192519e-11     2.916423e-19      4.999179e-09  9.926293e-10  3.577556e-11
12 5.048727e-11     5.058522e-18      2.209710e-11  1.031922e-13  5.048727e-11
13 4.146400e-11     8.051453e-18      1.607868e-07  4.372365e-08  1.243920e-10
14 3.360350e-10     1.031373e-16      1.017054e-11  1.017054e-11  3.360350e-10
15 1.123998e-10     1.979239e-18      1.412569e-08  9.144070e-08  3.371993e-10
   anova.p.value ⋯ not.Acinar_5 Acinar_5  Acinar_5.diff not.Acinar_3 Acinar_3
1  2.124091e-41  ⋯  2.3721703    3.408943  1.0367728     2.8108584    2.1226393
2  3.368285e-42  ⋯  2.4043512    3.480246  1.0758946     2.8764374    2.1061475
3  5.863048e-37  ⋯  2.2543412    3.330059  1.0757174     2.7142743    1.9933736
4  1.195929e-37  ⋯  2.4584340    3.579179  1.1207447     2.9600018    2.1244986
5  5.413610e-37  ⋯  2.1415102    3.120834  0.9793234     2.5592279    1.9062310
6  2.640159e-38  ⋯  1.7903112    2.686590  0.8962785     2.1801882    1.5345805
7  1.743239e-34  ⋯  2.4904315    3.620064  1.1296328     2.9775802    2.2015483
8  4.587000e-33  ⋯  0.6982516    1.015048  0.3167969     0.8702506    0.5141762
9  1.292575e-36  ⋯  2.3981229    3.569641  1.1715185     2.9080490    2.1001217
10 9.913070e-35  ⋯  2.0172381    2.889730  0.8724918     2.3942250    1.7880537
11 1.177175e-36  ⋯  1.4851467    2.120566  0.6354192     1.7271209    1.4155946
12 7.120192e-37  ⋯  1.9833281    2.938818  0.9554897     2.3893966    1.7487158
13 4.362193e-31  ⋯ -0.9501258   -1.388080 -0.4379546    -1.1383088   -0.8336639
14 6.465642e-35  ⋯ -1.0508772   -1.627801 -0.5769238    -1.2777848   -0.9514125
15 1.088123e-32  ⋯ -1.1258931   -1.671342 -0.5454485    -1.3424968   -1.0395699
   Acinar_3.diff not.Acinar_4 Acinar_4  Acinar_4.diff max
1  -0.6882191     2.1942331    4.058333  1.8640995    Acinar_4
2  -0.7702898     2.2150132    4.169983  1.9549703    Acinar_4
3  -0.7209008     2.1144846    3.861668  1.7471839    Acinar_4
4  -0.8355032     2.2668351    4.279997  2.0131617    Acinar_4
5  -0.6529969     1.9948947    3.666486  1.6715909    Acinar_4
6  -0.6456077     1.6744371    3.125558  1.4511214    Acinar_4
7  -0.7760320     2.3146526    4.270708  1.9560549    Acinar_4
8  -0.3560744     0.6088347    1.324868  0.7160334    Acinar_4
9  -0.8079273     2.2490586    4.136897  1.8878384    Acinar_4
10 -0.6061713     1.8593418    3.463329  1.6039869    Acinar_4
11 -0.3115263     1.3936511    2.462370  1.0687186    Acinar_4
12 -0.6406808     1.8680009    3.383106  1.5151054    Acinar_4
13  0.3046449    -0.8880800   -1.619269 -0.7311894    Acinar_1_2_6
14  0.3263722    -1.0263564   -1.747943 -0.7215869    Acinar_1_2_6
15  0.3029269    -1.0783878   -1.865350 -0.7869621    Acinar_1_2_6

   Motif                Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1  MA0081.2_SPIB        7.745088e-15         4.708318e-17     5.711467e-06
2  MA1954.1_FOXO1::ELK1 1.199831e-16         1.545919e-15     7.279538e-10
3  MA1935.1_ERF::FOXI1  9.486416e-20         4.418449e-15     5.980277e-11
4  MA1508.1_IKZF1       1.050028e-15         5.935888e-15     5.974928e-07
5  MA1952.1_FOXJ2::ELF1 1.086882e-17         2.621568e-14     3.537446e-06
6  MA0761.2_ETV1        2.466881e-16         4.632721e-14     2.374780e-10
7  MA1942.1_ETV2::FOXI1 4.382465e-18         4.751845e-14     9.723868e-11
8  MA0598.3_EHF         1.450238e-14         6.469684e-14     1.074528e-08
9  MA0062.3_GABPA       1.140049e-15         6.967626e-14     2.580405e-09
10 MA0687.1_SPIC        1.229371e-15         1.466883e-13     5.400201e-06
11 MA0640.2_ELF3        1.164729e-12         5.647208e-13     1.315897e-09
12 MA0473.3_ELF1        1.202998e-15         1.298989e-12     2.152582e-09
13 MA0762.1_ETV2        1.698016e-19         2.254607e-12     2.132797e-13
14 MA0499.2_MYOD1       7.702942e-18         6.171311e-12     6.802537e-13
15 MA1936.1_ERF::FOXO1  9.417633e-18         2.285850e-12     5.070067e-08
   Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1  2.296461e-05     2.323526e-14      1.883327e-16  1.142293e-05  2.296461e-05
2  1.743483e-07     4.799323e-16      4.637758e-15  1.455908e-09  1.743483e-07
3  1.531661e-09     3.794566e-19      1.325535e-14  1.196055e-10  1.531661e-09
4  1.185637e-06     4.200113e-15      1.780766e-14  1.194986e-06  1.194986e-06
5  1.151851e-06     4.347528e-17      7.864704e-14  3.537446e-06  2.303702e-06
6  6.573434e-09     9.867525e-16      1.389816e-13  4.749559e-10  6.573434e-09
7  7.725707e-09     1.752986e-17      1.425553e-13  1.944774e-10  7.725707e-09
8  7.947419e-08     5.800950e-14      1.940905e-13  2.149055e-08  7.947419e-08
9  2.251794e-08     4.560197e-15      2.090288e-13  5.160810e-09  2.251794e-08
10 3.468878e-05     4.917484e-15      4.400648e-13  1.080040e-05  3.468878e-05
11 8.192950e-07     3.494188e-12      2.258883e-12  2.631793e-09  8.192950e-07
12 6.585035e-08     4.811991e-15      3.896967e-12  4.305164e-09  6.585035e-08
13 7.083345e-10     6.792064e-19      4.509213e-12  6.398392e-13  7.083345e-10
14 1.712024e-12     3.081177e-17      6.171311e-12  2.040761e-12  3.424049e-12
15 5.272507e-07     3.767053e-17      6.857550e-12  1.014013e-07  5.272507e-07
   anova.p.value ⋯ not.Acinar_5 Acinar_5  Acinar_5.diff not.Acinar_3 Acinar_3
1  3.971125e-24  ⋯ -1.734641    -2.756791 -1.0221504    -2.113147    -1.642111
2  3.328790e-31  ⋯ -1.428903    -2.245363 -0.8164601    -1.732167    -1.346756
3  1.315011e-37  ⋯ -1.527312    -2.401542 -0.8742309    -1.852284    -1.446198
4  1.072319e-27  ⋯ -1.583073    -2.470274 -0.8872011    -1.910357    -1.503084
5  6.058559e-28  ⋯ -1.272090    -1.986184 -0.7140935    -1.535284    -1.204586
6  8.181550e-33  ⋯ -1.732933    -2.737019 -1.0040861    -2.132874    -1.564195
7  2.047111e-34  ⋯ -1.490005    -2.338224 -0.8482197    -1.809932    -1.395170
8  7.109810e-29  ⋯ -1.673239    -2.682426 -1.0091876    -2.079699    -1.487909
9  3.738038e-31  ⋯ -1.745967    -2.788307 -1.0423396    -2.153691    -1.584873
10 4.181977e-24  ⋯ -1.354929    -2.137290 -0.7823606    -1.631375    -1.324400
11 2.706754e-25  ⋯ -1.488267    -2.415076 -0.9268092    -1.876750    -1.268700
12 2.464079e-29  ⋯ -1.502698    -2.404040 -0.9013412    -1.867777    -1.329376
13 1.184151e-36  ⋯ -1.139002    -1.788862 -0.6498604    -1.388805    -1.059706
14 2.640159e-38  ⋯  1.790311     2.686590  0.8962785     2.180188     1.534581
15 2.404736e-28  ⋯ -1.019501    -1.573076 -0.5535750    -1.230449    -0.952073
   Acinar_3.diff not.Acinar_4 Acinar_4  Acinar_4.diff max
1   0.4710355    -1.742295    -2.811179 -1.0688837    Acinar_1_2_6
2   0.3854107    -1.423554    -2.324400 -0.9008462    Acinar_1_2_6
3   0.4060854    -1.519310    -2.492287 -0.9729771    Acinar_1_2_6
4   0.4072725    -1.574647    -2.567755 -0.9931076    Acinar_1_2_6
5   0.3306978    -1.261664    -2.074617 -0.8129535    Acinar_1_2_6
6   0.5686792    -1.712402    -2.884182 -1.1717800    Acinar_1_2_6
7   0.4147621    -1.480147    -2.435524 -0.9553772    Acinar_1_2_6
8   0.5917901    -1.659311    -2.806143 -1.1468318    Acinar_1_2_6
9   0.5688180    -1.738586    -2.894696 -1.1561108    Acinar_1_2_6
10  0.3069753    -1.364618    -2.167627 -0.8030089    Acinar_1_2_6
11  0.6080502    -1.476022    -2.527546 -1.0515238    Acinar_1_2_6
12  0.5384011    -1.489943    -2.516766 -1.0268231    Acinar_1_2_6
13  0.3290985    -1.124086    -1.884181 -0.7600950    Acinar_1_2_6
14 -0.6456077     1.674437     3.125558  1.4511214    Acinar_4
15  0.2783764    -1.001176    -1.671528 -0.6703516    Acinar_1_2_6

In [20]:
# Most sig holm's motifs that are signicicant in overal anova and max deviation scores in the given cluster
head(filter(arrange(type_anova_results_full_holm_anova_dev, Acinar_1_2_6.holm), Acinar_1_2_6.holm < .05, anova.q.value < 0.05, max == 'Acinar_1_2_6'), n=15)
head(filter(arrange(type_anova_results_full_holm_anova_dev, Acinar_3.holm), Acinar_3.holm < .05, anova.q.value < 0.05, max == 'Acinar_3'), n=15)
head(filter(arrange(type_anova_results_full_holm_anova_dev, Acinar_4.holm), Acinar_4.holm < .05, anova.q.value < 0.05, max == 'Acinar_4'), n=15)
head(filter(arrange(type_anova_results_full_holm_anova_dev, Acinar_5.holm), Acinar_5.holm < .05, anova.q.value < 0.05, max == 'Acinar_5'), n=15)

   Motif                Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1  MA1935.1_ERF::FOXI1  9.486416e-20         4.418449e-15     5.980277e-11
2  MA0762.1_ETV2        1.698016e-19         2.254607e-12     2.132797e-13
3  MA1957.1_HOXB2::ELK1 4.588299e-19         1.687890e-05     1.219505e-03
4  MA1950.1_FLI1::FOXI1 4.893387e-19         2.559704e-12     1.730355e-11
5  MA0076.2_ELK4        4.948097e-19         7.062845e-09     9.144070e-08
6  MA0475.2_FLI1        1.314674e-18         3.541591e-09     3.262911e-08
7  MA0760.1_ERF         1.739912e-18         2.214106e-10     8.187445e-09
8  MA0750.2_ZBTB7A      2.012863e-18         1.607868e-07     2.186183e-08
9  MA1942.1_ETV2::FOXI1 4.382465e-18         4.751845e-14     9.723868e-11
10 MA1931.1_ELK1::HOXA1 6.095849e-18         3.752592e-03     1.645872e-05
11 MA1936.1_ERF::FOXO1  9.417633e-18         2.285850e-12     5.070067e-08
12 MA1952.1_FOXJ2::ELF1 1.086882e-17         2.621568e-14     3.537446e-06
13 MA1630.2_ZNF281      1.590872e-17         1.421048e-05     1.189267e-07
14 MA1953.1_FOXO1::ELF1 2.578432e-17         3.474334e-12     3.390180e-12
15 MA0156.3_FEV         2.883385e-17         4.089223e-08     1.934876e-06
   Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1  1.531661e-09     3.794566e-19      1.325535e-14  1.196055e-10  1.531661e-09
2  7.083345e-10     6.792064e-19      4.509213e-12  6.398392e-13  7.083345e-10
3  1.694385e-07     1.835320e-18      3.375781e-05  1.219505e-03  5.083155e-07
4  5.151576e-10     1.957355e-18      7.679112e-12  3.460709e-11  5.151576e-10
5  1.123998e-10     1.979239e-18      1.412569e-08  9.144070e-08  3.371993e-10
6  4.439355e-09     5.258697e-18      1.062477e-08  3.262911e-08  1.062477e-08
7  1.844295e-10     6.959646e-18      5.532885e-10  8.187445e-09  5.532885e-10
8  4.146400e-11     8.051453e-18      1.607868e-07  4.372365e-08  1.243920e-10
9  7.725707e-09     1.752986e-17      1.425553e-13  1.944774e-10  7.725707e-09
10 6.692821e-10     2.438339e-17      3.752592e-03  3.291744e-05  2.007846e-09
11 5.272507e-07     3.767053e-17      6.857550e-12  1.014013e-07  5.272507e-07
12 1.151851e-06     4.347528e-17      7.864704e-14  3.537446e-06  2.303702e-06
13 9.522795e-08     6.363488e-17      1.421048e-05  2.856838e-07  2.856838e-07
14 3.360350e-10     1.031373e-16      1.017054e-11  1.017054e-11  3.360350e-10
15 6.411452e-08     1.153354e-16      1.226767e-07  1.934876e-06  1.282290e-07
   anova.p.value ⋯ not.Acinar_5 Acinar_5   Acinar_5.diff not.Acinar_3
1  1.315011e-37  ⋯ -1.5273116   -2.4015425 -0.8742309    -1.8522838
2  1.184151e-36  ⋯ -1.1390021   -1.7888625 -0.6498604    -1.3888046
3  3.902140e-22  ⋯ -0.6419938   -0.9710495 -0.3290556    -0.7675258
4  5.544068e-36  ⋯ -1.4387260   -2.2222027 -0.7834767    -1.7408513
5  1.088123e-32  ⋯ -1.1258931   -1.6713416 -0.5454485    -1.3424968
6  1.087778e-30  ⋯ -0.8860290   -1.3264733 -0.4404444    -1.0589761
7  4.713012e-34  ⋯ -0.9456788   -1.4157123 -0.4700335    -1.1281569
8  4.362193e-31  ⋯ -0.9501258   -1.3880804 -0.4379546    -1.1383088
9  2.047111e-34  ⋯ -1.4900047   -2.3382243 -0.8482197    -1.8099317
10 2.859729e-22  ⋯ -0.6565723   -0.9115156 -0.2549432    -0.7706720
11 2.404736e-28  ⋯ -1.0195011   -1.5730761 -0.5535750    -1.2304494
12 6.058559e-28  ⋯ -1.2720901   -1.9861835 -0.7140935    -1.5352839
13 6.446906e-23  ⋯ -0.4148732   -0.6428242 -0.2279510    -0.5167125
14 6.465642e-35  ⋯ -1.0508772   -1.6278010 -0.5769238    -1.2777848
15 5.064563e-27  ⋯ -0.7782544   -1.1763713 -0.3981169    -0.9265584
   Acinar_3   Acinar_3.diff not.Acinar_4 Acinar_4   Acinar_4.diff max
1  -1.4461984 0.4060854     -1.5193095   -2.4922866 -0.9729771    Acinar_1_2_6
2  -1.0597060 0.3290985     -1.1240855   -1.8841806 -0.7600950    Acinar_1_2_6
3  -0.6149673 0.1525584     -0.6225182   -1.0612205 -0.4387023    Acinar_1_2_6
4  -1.3352937 0.4055575     -1.4096676   -2.3748369 -0.9651693    Acinar_1_2_6
5  -1.0395699 0.3029269     -1.0783878   -1.8653499 -0.7869621    Acinar_1_2_6
6  -0.8215709 0.2374052     -0.8486632   -1.4788452 -0.6301820    Acinar_1_2_6
7  -0.8789790 0.2491779     -0.9087133   -1.5704964 -0.6617831    Acinar_1_2_6
8  -0.8336639 0.3046449     -0.8880800   -1.6192694 -0.7311894    Acinar_1_2_6
9  -1.3951696 0.4147621     -1.4801468   -2.4355240 -0.9553772    Acinar_1_2_6
10 -0.5950279 0.1756441     -0.5922143   -1.1331505 -0.5409362    Acinar_1_2_6
11 -0.9520730 0.2783764     -1.0011760   -1.6715277 -0.6703516    Acinar_1_2_6
12 -1.2045861 0.3306978     -1.2616638   -2.0746173 -0.8129535    Acinar_1_2_6
13 -0.3523858 0.1643267     -0.3932261   -0.7291834 -0.3359574    Acinar_1_2_6
14 -0.9514125 0.3263722     -1.0263564   -1.7479433 -0.7215869    Acinar_1_2_6
15 -0.7418062 0.1847522     -0.7563835   -1.2733179 -0.5169344    Acinar_1_2_6

   Motif                Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1  MA0462.2_BATF::JUN   1.020715e-04         1.688774e-06     1.084321e-11
2  MA1634.1_BATF        7.126106e-05         1.089571e-06     1.161588e-11
3  MA0835.2_BATF3       6.112197e-05         6.253501e-07     1.338889e-11
4  MA1928.1_BNC2        7.396547e-04         3.076904e-06     1.398722e-11
5  MA1138.1_FOSL2::JUNB 4.413773e-04         1.800921e-07     1.437781e-11
6  MA0501.1_MAF::NFE2   1.265579e-05         1.509500e-07     1.469702e-11
7  MA1141.1_FOS::JUND   2.377327e-04         7.619808e-07     1.482023e-11
8  MA0491.2_JUND        6.027011e-05         2.709517e-07     1.513020e-11
9  MA0477.2_FOSL1       2.851182e-04         3.358983e-07     1.556007e-11
10 MA1128.1_FOSL1::JUN  2.935017e-04         1.027483e-06     1.558733e-11
11 MA0490.2_JUNB        6.543828e-05         3.056058e-07     1.566539e-11
12 MA1137.1_FOSL1::JUNB 1.931064e-04         2.039456e-07     1.606703e-11
13 MA0476.1_FOS         1.218191e-04         1.334765e-06     1.712200e-11
14 MA0099.3_FOS::JUN    3.789625e-04         7.699750e-07     2.143008e-11
15 MA0655.1_JDP2        6.281708e-04         5.551403e-07     2.339813e-11
   Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1  4.713687e-06     1.020715e-04      5.066322e-06  4.337286e-11  9.427373e-06
2  6.433320e-06     7.126106e-05      3.268713e-06  4.646354e-11  1.286664e-05
3  3.340559e-06     6.112197e-05      1.876050e-06  5.355558e-11  6.681119e-06
4  1.528436e-05     7.396547e-04      9.230712e-06  5.594888e-11  3.056873e-05
5  3.215151e-06     4.413773e-04      5.402763e-07  5.751122e-11  6.430302e-06
6  6.034259e-05     2.531158e-05      4.528500e-07  5.878809e-11  6.034259e-05
7  3.309391e-06     2.377327e-04      2.285942e-06  5.928090e-11  6.618783e-06
8  2.493698e-06     6.027011e-05      8.128551e-07  6.052079e-11  4.987397e-06
9  7.116509e-06     2.851182e-04      1.007695e-06  6.224029e-11  1.423302e-05
10 7.279212e-06     2.935017e-04      3.082450e-06  6.234933e-11  1.455842e-05
11 4.260960e-06     6.543828e-05      9.168175e-07  6.266155e-11  8.521920e-06
12 7.878110e-06     1.931064e-04      6.118368e-07  6.426814e-11  1.575622e-05
13 4.271062e-06     1.218191e-04      4.004294e-06  6.848799e-11  8.542124e-06
14 5.605623e-06     3.789625e-04      2.309925e-06  8.572031e-11  1.121125e-05
15 3.637490e-06     6.281708e-04      1.665421e-06  9.359253e-11  7.274981e-06
   anova.p.value ⋯ not.Acinar_5 Acinar_5   Acinar_5.diff not.Acinar_3
1  2.015332e-17  ⋯ -0.8852479   -1.6956444 -0.8103965    -1.443273
2  2.217783e-17  ⋯ -0.8919592   -1.7259112 -0.8339520    -1.451226
3  5.300354e-18  ⋯ -0.8561657   -1.6592256 -0.8030598    -1.395282
4  3.202807e-16  ⋯ -0.8077191   -1.6132860 -0.8055669    -1.381229
5  5.181466e-18  ⋯ -0.7683412   -1.5567405 -0.7883993    -1.314440
6  3.023022e-16  ⋯ -0.4985581   -0.9759478 -0.4773897    -0.793457
7  1.101902e-17  ⋯ -0.9221540   -1.8115329 -0.8893789    -1.533985
8  2.091325e-18  ⋯ -0.8556839   -1.6920575 -0.8363736    -1.411024
9  2.273613e-17  ⋯ -0.8389594   -1.6725372 -0.8335778    -1.414215
10 5.655889e-17  ⋯ -0.8984775   -1.7461049 -0.8476275    -1.486220
11 6.314656e-18  ⋯ -0.8628587   -1.6877570 -0.8248983    -1.414451
12 1.832299e-17  ⋯ -0.8457962   -1.6921336 -0.8463373    -1.419332
13 1.857219e-17  ⋯ -0.8990212   -1.7565669 -0.8575457    -1.484284
14 3.404826e-17  ⋯ -0.8547965   -1.6898814 -0.8350848    -1.434574
15 1.718153e-17  ⋯ -0.6840307   -1.3963541 -0.7123234    -1.182522
   Acinar_3     Acinar_3.diff not.Acinar_4 Acinar_4  Acinar_4.diff max
1  -0.057321711 1.3859513     -0.7883377   -2.070221 -1.2818833    Acinar_3
2  -0.086590448 1.3646357     -0.8104452   -2.052857 -1.2424121    Acinar_3
3  -0.078005962 1.3172764     -0.7769664   -1.976747 -1.1997801    Acinar_3
4   0.068285772 1.4495145     -0.7100820   -1.990796 -1.2807142    Acinar_3
5   0.057559626 1.3719993     -0.6830093   -1.891565 -1.2085553    Acinar_3
6  -0.104086490 0.6893705     -0.4704330   -1.103308 -0.6328752    Acinar_3
7  -0.007945383 1.5260401     -0.8233141   -2.198349 -1.3750349    Acinar_3
8  -0.064897868 1.3461259     -0.7829964   -1.988949 -1.2059527    Acinar_3
9   0.018106763 1.4323218     -0.7500323   -2.021443 -1.2714106    Acinar_3
10 -0.012028950 1.4741910     -0.7967375   -2.138429 -1.3416911    Acinar_3
11 -0.067454596 1.3469963     -0.7826040   -2.006918 -1.2243141    Acinar_3
12  0.001552006 1.4208836     -0.7618550   -2.026734 -1.2648787    Acinar_3
13 -0.036987175 1.4472964     -0.8051684   -2.125795 -1.3206271    Acinar_3
14  0.018798267 1.4533724     -0.7598332   -2.059381 -1.2995479    Acinar_3
15  0.068605896 1.2511283     -0.6055747   -1.703089 -1.0975146    Acinar_3

   Motif          Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1  MA0103.3_ZEB1  1.574728e-19         2.689590e-10     2.472934e-10
2  MA0745.2_SNAI2 8.832115e-20         8.553561e-10     3.539203e-15
3  MA1631.1_ASCL1 4.326072e-19         1.965950e-09     9.486600e-10
4  MA1559.1_SNAI3 8.164321e-20         7.540437e-09     6.905179e-12
5  MA0522.3_TCF3  7.807799e-20         4.058820e-09     1.232217e-09
6  MA0499.2_MYOD1 7.702942e-18         6.171311e-12     6.802537e-13
7  MA0830.2_TCF4  3.758440e-18         4.265788e-08     1.979291e-10
8  MA1529.1_NHLH2 1.749667e-15         2.003972e-07     6.815149e-14
9  MA1558.1_SNAI1 1.223894e-19         4.951820e-09     2.315334e-11
10 MA1648.1_TCF12 2.081354e-19         1.188093e-08     3.195115e-09
11 MA0592.3_ESRRA 7.291057e-20         4.999179e-09     4.963146e-10
12 MA0820.1_FIGLA 1.264630e-18         1.104855e-11     3.439739e-14
13 MA0801.1_MGA   7.276620e-18         1.633720e-06     7.119414e-07
14 MA0665.1_MSC   1.295324e-11         1.697260e-05     5.138989e-10
15 MA0806.1_TBX4  1.636504e-17         2.045537e-09     1.891550e-08
   Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1  3.423745e-15     6.298912e-19      4.945867e-10  4.945867e-10  1.027123e-14
2  7.046577e-15     3.532846e-19      8.553561e-10  1.061761e-14  1.409315e-14
3  5.352134e-13     1.730429e-18      1.965950e-09  1.897320e-09  1.605640e-12
4  5.997740e-13     3.265728e-19      7.540437e-09  1.381036e-11  1.799322e-12
5  8.678717e-13     3.123120e-19      4.058820e-09  2.464434e-09  2.603615e-12
6  1.712024e-12     3.081177e-17      6.171311e-12  2.040761e-12  3.424049e-12
7  2.728476e-12     1.503376e-17      4.265788e-08  3.958583e-10  8.185429e-12
8  4.192719e-12     6.998669e-15      2.003972e-07  2.044545e-13  8.385439e-12
9  3.311749e-12     4.895578e-19      4.951820e-09  4.630669e-11  9.935248e-12
10 1.106954e-11     8.325415e-19      1.188093e-08  6.390230e-09  3.320862e-11
11 1.192519e-11     2.916423e-19      4.999179e-09  9.926293e-10  3.577556e-11
12 5.048727e-11     5.058522e-18      2.209710e-11  1.031922e-13  5.048727e-11
13 4.574381e-10     2.910648e-17      1.633720e-06  1.423883e-06  1.372314e-09
14 4.844715e-10     5.181296e-11      1.697260e-05  1.453414e-09  1.453414e-09
15 1.110923e-09     6.546016e-17      4.091073e-09  1.891550e-08  3.332770e-09
   anova.p.value ⋯ not.Acinar_5 Acinar_5 Acinar_5.diff not.Acinar_3 Acinar_3
1  2.124091e-41  ⋯ 2.3721703    3.408943 1.0367728     2.8108584    2.1226393
2  3.368285e-42  ⋯ 2.4043512    3.480246 1.0758946     2.8764374    2.1061475
3  5.863048e-37  ⋯ 2.2543412    3.330059 1.0757174     2.7142743    1.9933736
4  1.195929e-37  ⋯ 2.4584340    3.579179 1.1207447     2.9600018    2.1244986
5  5.413610e-37  ⋯ 2.1415102    3.120834 0.9793234     2.5592279    1.9062310
6  2.640159e-38  ⋯ 1.7903112    2.686590 0.8962785     2.1801882    1.5345805
7  1.743239e-34  ⋯ 2.4904315    3.620064 1.1296328     2.9775802    2.2015483
8  4.587000e-33  ⋯ 0.6982516    1.015048 0.3167969     0.8702506    0.5141762
9  1.292575e-36  ⋯ 2.3981229    3.569641 1.1715185     2.9080490    2.1001217
10 9.913070e-35  ⋯ 2.0172381    2.889730 0.8724918     2.3942250    1.7880537
11 1.177175e-36  ⋯ 1.4851467    2.120566 0.6354192     1.7271209    1.4155946
12 7.120192e-37  ⋯ 1.9833281    2.938818 0.9554897     2.3893966    1.7487158
13 5.765921e-30  ⋯ 0.7913014    1.109893 0.3185913     0.9257288    0.7283104
14 2.324050e-25  ⋯ 0.7756867    1.069571 0.2938839     0.9440862    0.5586842
15 7.633650e-32  ⋯ 1.0890792    1.636906 0.5478265     1.3081317    1.0079594
   Acinar_3.diff not.Acinar_4 Acinar_4 Acinar_4.diff max
1  -0.6882191    2.1942331    4.058333 1.8640995     Acinar_4
2  -0.7702898    2.2150132    4.169983 1.9549703     Acinar_4
3  -0.7209008    2.1144846    3.861668 1.7471839     Acinar_4
4  -0.8355032    2.2668351    4.279997 2.0131617     Acinar_4
5  -0.6529969    1.9948947    3.666486 1.6715909     Acinar_4
6  -0.6456077    1.6744371    3.125558 1.4511214     Acinar_4
7  -0.7760320    2.3146526    4.270708 1.9560549     Acinar_4
8  -0.3560744    0.6088347    1.324868 0.7160334     Acinar_4
9  -0.8079273    2.2490586    4.136897 1.8878384     Acinar_4
10 -0.6061713    1.8593418    3.463329 1.6039869     Acinar_4
11 -0.3115263    1.3936511    2.462370 1.0687186     Acinar_4
12 -0.6406808    1.8680009    3.383106 1.5151054     Acinar_4
13 -0.1974184    0.7245859    1.347006 0.6224204     Acinar_4
14 -0.3854020    0.6589008    1.465294 0.8063933     Acinar_4
15 -0.3001723    1.0469197    1.816410 0.7694901     Acinar_4

   Motif            Acinar_1_2_6.p.value Acinar_5.p.value Acinar_3.p.value
1  MA0757.1_ONECUT3 7.860170e-07         2.518007e-08     3.043517e-02
2  MA1487.2_FOXE1   1.749221e-12         7.534956e-08     1.487714e-03
3  MA0032.2_FOXC1   5.681457e-14         1.004736e-07     6.759203e-04
4  MA0796.1_TGIF1   8.189617e-09         1.123886e-07     4.381274e-01
5  MA0679.2_ONECUT1 1.604247e-08         2.311145e-07     9.086465e-03
6  MA0046.2_HNF1A   1.364581e-08         2.705683e-07     1.618366e-03
7  MA0153.2_HNF1B   1.189166e-08         3.622569e-07     2.705220e-04
8  MA1574.1_THRB    9.948231e-12         3.845449e-07     1.800600e-01
9  MA0845.1_FOXB1   3.893092e-14         8.419081e-07     1.509715e-05
10 MA0754.2_CUX1    7.300647e-07         1.107870e-06     7.046021e-04
11 MA0670.1_NFIA    4.252985e-08         1.546694e-06     4.139679e-03
12 MA0797.1_TGIF2   2.226372e-09         2.098459e-06     2.666548e-01
13 MA0856.1_RXRG    4.584649e-12         6.358260e-06     2.216120e-02
14 MA0041.2_FOXD3   1.046039e-09         9.607334e-06     1.213344e-02
15 MA1537.1_NR2F1   2.131436e-12         1.161642e-05     1.178273e-01
   Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm Acinar_3.holm Acinar_4.holm
1  0.1929661008     2.358051e-06      1.007203e-07  6.087035e-02  0.192966101
2  0.0008561141     6.996885e-12      2.260487e-07  1.712228e-03  0.001712228
3  0.0082339261     2.272583e-13      3.014208e-07  1.351841e-03  0.008233926
4  0.3539432911     3.275847e-08      3.371658e-07  7.078866e-01  0.707886582
5  0.0063969284     6.416990e-08      6.933435e-07  1.279386e-02  0.012793857
6  0.0488345039     5.458326e-08      8.117049e-07  3.236732e-03  0.048834504
7  0.0049901682     4.756665e-08      1.086771e-06  5.410440e-04  0.004990168
8  0.0788297080     3.979292e-11      1.153635e-06  1.800600e-01  0.157659416
9  0.0038604250     1.557237e-13      2.525724e-06  3.019429e-05  0.003860425
10 0.0319040015     2.920259e-06      3.323611e-06  1.409204e-03  0.031904002
11 0.2178036303     1.701194e-07      4.640083e-06  8.279358e-03  0.217803630
12 0.1560694805     8.905490e-09      6.295378e-06  3.121390e-01  0.312138961
13 0.0113754228     1.833859e-11      1.907478e-05  2.275085e-02  0.022750846
14 0.1054000507     4.184154e-09      2.882200e-05  2.426687e-02  0.105400051
15 0.0562225920     8.525745e-12      3.484925e-05  1.178273e-01  0.112445184
   anova.p.value ⋯ not.Acinar_5 Acinar_5  Acinar_5.diff not.Acinar_3 Acinar_3
1  7.019262e-07  ⋯ 0.4098005    0.7504370 0.3406365     0.5296189    0.3943250
2  5.497418e-18  ⋯ 0.5959919    1.0000988 0.4041069     0.7313921    0.6092861
3  1.709051e-16  ⋯ 0.8383168    1.4257605 0.5874437     1.0221162    0.8753280
4  1.174525e-08  ⋯ 0.3571668    0.6339666 0.2767998     0.4366181    0.4047033
5  1.075043e-11  ⋯ 0.5249833    0.8380005 0.3130171     0.6335055    0.5057087
6  5.842930e-12  ⋯ 0.5003708    0.8859084 0.3855376     0.6372235    0.4949076
7  7.747732e-13  ⋯ 0.5624538    0.9215092 0.3590554     0.6979079    0.5345094
8  1.422039e-10  ⋯ 0.3350657    0.5600218 0.2249560     0.4033535    0.3626162
9  6.539704e-15  ⋯ 0.8451525    1.3943851 0.5492326     1.0368112    0.8286820
10 2.741983e-09  ⋯ 0.4502071    0.7417784 0.2915713     0.5558836    0.4184952
11 1.803533e-08  ⋯ 0.3344153    0.6162885 0.2818732     0.4310409    0.3379547
12 2.923222e-08  ⋯ 0.3653654    0.6500238 0.2846583     0.4560301    0.3973815
13 1.091046e-11  ⋯ 0.4598290    0.7091112 0.2492823     0.5424551    0.4716215
14 2.693359e-09  ⋯ 0.3627050    0.6540237 0.2913187     0.4598199    0.3719254
15 1.295635e-11  ⋯ 0.4191810    0.7011536 0.2819726     0.5033680    0.4571269
   Acinar_3.diff not.Acinar_4 Acinar_4  Acinar_4.diff max
1  -0.13529392   0.4561295    0.6275268 0.17139729    Acinar_5
2  -0.12210596   0.6318412    0.9190238 0.28718252    Acinar_5
3  -0.14678824   0.8990675    1.2754877 0.37642019    Acinar_5
4  -0.03191485   0.4096888    0.4895448 0.07985597    Acinar_5
5  -0.12779683   0.5376136    0.8194710 0.28185735    Acinar_5
6  -0.14231585   0.5593840    0.7257210 0.16633704    Acinar_5
7  -0.16339845   0.5898299    0.8604052 0.27057521    Acinar_5
8  -0.04073727   0.3624936    0.4877944 0.12530076    Acinar_5
9  -0.20812924   0.8721682    1.3484419 0.47627367    Acinar_5
10 -0.13738838   0.4703064    0.6981157 0.22780925    Acinar_5
11 -0.09308615   0.3816460    0.4880308 0.10638485    Acinar_5
12 -0.05864859   0.4084106    0.5357341 0.12732347    Acinar_5
13 -0.07083361   0.4662450    0.7065791 0.24033406    Acinar_5
14 -0.08789455   0.4032020    0.5468170 0.14361498    Acinar_5
15 -0.04624107   0.4562223    0.6033856 0.14716328    Acinar_5

In [21]:
#Get families
TFClass_Lookup_sub <- select(TFClass_Lookup, Motif=full_jaspar_motif, Family=lowest_level_family)
TFClass_Lookup_sub <- TFClass_Lookup_sub[!duplicated(TFClass_Lookup_sub$Motif),]

TFClass_Lookup_sub

    Motif                Family
1   MA0030.1_FOXF2       FOXF
2   MA0031.1_FOXD1       FOXD
3   MA0051.1_IRF2        IRF
4   MA0057.1_MZF1(var.2) More than 3 adjacent zinc fingers
5   MA0059.1_MAX::MYC    MYC
6   MA0066.1_PPARG       PPAR(NR1C)
7   MA0069.1_PAX6        PAX4-like
8   MA0070.1_PBX1        PBX
9   MA0071.1_RORA        ROR(NR1F)
10  MA0072.1_RORA(var.2) ROR(NR1F)
11  MA0073.1_RREB1       Factors with multiple dispersed zinc fingers
12  MA0074.1_RXRA::VDR   RXR(NR2B)
13  MA0077.1_SOX9        Group E
14  MA0084.1_SRY         Group A
15  MA0091.1_TAL1::TCF3  TAL-HEN
16  MA0101.1_REL         NFkappaB p65-like
17  MA0107.1_RELA        NFkappaB p65-like
18  MA0115.1_NR1H2::RXRA LXR(NR1H)
19  MA0119.1_NFIC::TLX1  NF-1
20  MA0130.1_ZNF354C     More than 3 adjacent zinc fingers
21  MA0139.1_CTCF        CTCF-like
22  MA0149.1_EWSR1-FLI1  ETS-like
23  MA0138.2_REST        Factors with multiple dispersed zinc fingers
24  MA0152.1_NFATC2      NFAT-related
25  MA0155.1_INSM1       Insulinoma-associated proteins
26  MA0159.1_RARA::RXRA  RAR(NR1B)
27  MA0160.1_NR4A2       NGFI(NR4A)
28  MA0163.1_PLAG1       PLAG
29  MA0259.1_ARNT::HIF1A PAS-ARNT
30  MA0468.1_DUX4        DUX
⋮   ⋮                    ⋮
795 MA0784.2_POU1F1      POU1
796 MA0798.3_RFX3        RFX
797 MA0799.2_RFX4        RFX
798 MA0818.2_BHLHE22     Neurogenin-ATO
799 MA0819.2_CLOCK       PAS-ARNT
800 MA0821.2_HES5        HAIRY
801 MA0828.2_SREBF2      SREBF
802 MA0831.3_TFE3        TFE3
803 MA0837.2_CEBPE       CEBP
804 MA0847.3_FOXD2       FOXD
805 MA0865.2_E2F8        E2F
806 MA0877.3_BARHL1      BARHL
807 MA0878.3_CDX1        CDX
808 MA0879.2_DLX1        DLX
809 MA0884.2_DUXA        DUX
810 MA1483.2_ELF2        ELF1-like
811 MA1487.2_FOXE1       FOXE
812 MA1491.2_GLI3        GLI-lile
813 MA1498.2_HOXA7       HOX6-7
814 MA1511.2_KLF10       Kr-like
815 MA1525.2_NFATC4      NFAT-related
816 MA1532.2_NR1D2       REVERBA(NR1D)
817 MA1547.2_PITX2       PITX
818 MA1563.2_SOX18       Group F
819 MA1566.2_TBX3        TBX2-related
820 MA1601.2_ZNF75D      ZNF75-like
821 MA1630.2_ZNF281      ZNF148-like
822 MA1633.2_BACH1       NFE2
823 MA0597.2_THAP1       THAP
824 NA                   NFE2

In [22]:
# Add on families
dim(type_anova_results_full_holm_anova_dev)

type_anova_results_full_holm_anova_dev_fam <- select(left_join(type_anova_results_full_holm_anova_dev, TFClass_Lookup_sub), Motif, Family, everything())

dim(type_anova_results_full_holm_anova_dev_fam)
head(type_anova_results_full_holm_anova_dev_fam)

[1] 692  24

Joining with `by = join_by(Motif)`

[1] 692  25

  Motif             Family     Acinar_1_2_6.p.value Acinar_5.p.value
1 MA0030.1_FOXF2    FOXF       1.878561e-06         7.161564e-03
2 MA0031.1_FOXD1    FOXD       8.190823e-11         2.474089e-04
3 MA0051.1_IRF2     IRF        2.146152e-10         1.182946e-07
4 MA0059.1_MAX::MYC MYC        7.680233e-03         1.116966e-01
5 MA0066.1_PPARG    PPAR(NR1C) 3.355028e-01         2.115934e-01
6 MA0069.1_PAX6     PAX4-like  1.016753e-06         6.478739e-03
  Acinar_3.p.value Acinar_4.p.value Acinar_1_2_6.holm Acinar_5.holm
1 0.4033856373     0.4695431201     7.514245e-06      2.148469e-02
2 0.7115260632     0.0071438760     3.276329e-10      7.422268e-04
3 0.0001289029     0.0008358103     8.584606e-10      3.548837e-07
4 0.0013265279     0.1502414143     2.304070e-02      2.233933e-01
5 0.2765041439     0.6371728416     8.463736e-01      8.463736e-01
6 0.0012452074     0.0280443027     4.067012e-06      1.295748e-02
  Acinar_3.holm Acinar_4.holm ⋯ not.Acinar_5 Acinar_5    Acinar_5.diff
1 0.8067712747  0.8067712747  ⋯  0.33699151   0.51742727  0.18043576
2 0.7115260632  0.0142877519  ⋯  0.51777387   0.75361113  0.23583726
3 0.0002578058  0.0008358103  ⋯ -0.45760182  -0.77134101 -0.31373919
4 0.0053061117  0.2233932673  ⋯  0.06217336   0.15690768  0.09473432
5 0.8463735940  0.8463735940  ⋯  0.04754416   0.09334931  0.04580514
6 0.0037356223  0.0280443027  ⋯ -0.24760523  -0.39473373 -0.14712850
  not.Acinar_3 Acinar_3    Acinar_3.diff not.Acinar_4 Acinar_4    Acinar_4.diff
1  0.37565291   0.40839287  0.03273996    0.36346805   0.44923345  0.08576540
2  0.58349083   0.57171637 -0.01177446    0.51572609   0.78081496  0.26508887
3 -0.58512056  -0.40493006  0.18019050   -0.46521052  -0.77325198 -0.30804147
4  0.11512127   0.01296847 -0.10215279    0.06592540   0.15121380  0.08528841
5  0.04802604   0.09448791  0.04646187    0.07143713   0.01943405 -0.05200309
6 -0.31250140  -0.20176058  0.11074082   -0.23391655  -0.45161310 -0.21769655
  max
1 Acinar_5
2 Acinar_4
3 Acinar_1_2_6
4 Acinar_5
5 Acinar_3
6 Acinar_1_2_6

In [23]:
# Write it all out!
write.table(type_anova_results_full_holm_anova_dev_fam, 
            '/nfs/lab/welison/multiome/chromvar/240209_ChromVar_Outputs/Acinar_subtype_donor_anova_holm_results.tsv',
            row.names=F, col.names=T, quote=F, sep='\t')

write.table(filter(arrange(type_anova_results_full_holm_anova_dev_fam, Acinar_1_2_6.holm), 
              Acinar_1_2_6.holm < .05, anova.q.value < .05, max == 'Acinar_1_2_6'), 
            '/nfs/lab/welison/multiome/chromvar/240209_ChromVar_Outputs/Acinar_subtype_donor_anova_holm_results_Acinar_1_2_6_max.tsv',
            row.names=F, col.names=T, quote=F, sep='\t')
write.table(filter(arrange(type_anova_results_full_holm_anova_dev_fam, Acinar_3.holm), 
              Acinar_3.holm < .05, anova.q.value < .05, max == 'Acinar_3'), 
            '/nfs/lab/welison/multiome/chromvar/240209_ChromVar_Outputs/Acinar_subtype_donor_anova_holm_results_Acinar_3_max.tsv',
            row.names=F, col.names=T, quote=F, sep='\t')
write.table(filter(arrange(type_anova_results_full_holm_anova_dev_fam, Acinar_4.holm), 
              Acinar_4.holm < .05, anova.q.value < .05, max == 'Acinar_4'), 
            '/nfs/lab/welison/multiome/chromvar/240209_ChromVar_Outputs/Acinar_subtype_donor_anova_holm_results_Acinar_4_max.tsv',
            row.names=F, col.names=T, quote=F, sep='\t')
write.table(filter(arrange(type_anova_results_full_holm_anova_dev_fam, Acinar_5.holm), 
              Acinar_5.holm < .05, anova.q.value < .05, max == 'Acinar_5'), 
            '/nfs/lab/welison/multiome/chromvar/240209_ChromVar_Outputs/Acinar_subtype_donor_anova_holm_results_Acinar_5_max.tsv',
            row.names=F, col.names=T, quote=F, sep='\t')