In [273]:
options(scipen=999)
pacman::p_load(plyr,dplyr, stringr, data.table, tidyr,
               pheatmap, colorRamps, gridExtra, ggplot2, ggrepel, RColorBrewer,vioplot,ggforce,
              gridExtra, ggplot2, ggrepel, RColorBrewer,vioplot,grid, patchwork, grid, ggh4x, ggalluvial,
               ggsankey)

## Directories

In [274]:
# Set working directories
base.dir =  "/nfs/lab/projects/CellCrosstalk/npod.pancreas/Final/"
assets.dir = paste(base.dir, "Assets/", sep = "") 
results.dir = paste(base.dir, "Results/corrected/", sep = "")
permutation.result.dir = paste(base.dir, "Results/corrected.permutation.test/", sep = "")


# Databases
cc.db = "/nfs/lab/projects/islet_multiomics_stress/analysis/CellChat/Assets/CellChatDB.human.txt"
Gaulton.db.dir = "/nfs/lab/Luca/Assets/LR.Database/GaultonDB_V2.txt"

permutations.test.tmp.dir = paste(permutation.result.dir, "TMP/", sep = "")
permutations.test.res.dir = paste(permutation.result.dir, "Results/", sep = "")

cc.db = "/nfs/lab/projects/islet_multiomics_stress/analysis/CellChat/Assets/CellChatDB.human.txt"

## Variables

In [275]:
# conditions
condition.ls = c("ND", "Aab", "T1D_early","T1D_late")

colors.conditions = c("ND" = "#85EF1B",
                      "Aab" = "#EFEF1B",
                      "T1D_early" = "#EF851B",
                      "T1D_late" = "#EF1B1B")

# Contrasts
Contrast_1 = c(condition.ls[2], condition.ls[3], condition.ls[4])
Contrast_2 = c(condition.ls[1], condition.ls[1], condition.ls[1])

# Celltypes and compartments
Endocrine = c('Alpha', 'Beta', 'Delta')
Exocrine = c('Acinar1_2_6','Acinar_3','Acinar_4','Acinar_5','Ductal','MUC5b_Ductal')
Immune = c('Tcells','Macrophage')
Endothelial = c('Endothelial')
Stromal = c('Activated_Stellate','Quiescent_Stellate')

cell.pop.order = c(Endocrine, Exocrine, Immune, Endothelial, Stromal)
rev.cell.pop.order = c(rev(Stromal), rev(Endothelial), rev(Immune), rev(Exocrine), rev(Endocrine), use.names = TRUE)

compartment = cell.pop.order
compartment = ifelse(compartment  %in%  Endocrine, "Endocrine", 
                 ifelse(compartment  %in%  Exocrine, "Exocrine",
                        ifelse(compartment  %in%  Immune, "Immune",
                               ifelse(compartment  %in%  Endothelial, "Endothelial", "Stromal"))))

Cellpop.compartment = as.data.frame(cbind(cell.pop.order, compartment))
Cellpop.compartment$compartment = factor(Cellpop.compartment$compartment, levels = c('Endocrine','Exocrine','Immune','Endothelial', "Stromal"))
colnames(Cellpop.compartment)[1] = "Celltype"

colors.compartments = c('Endocrine'='#26bfbf',
           'Exocrine'='#ed872d',
           'Immune'='#3F98E0',
           'Endothelial'='#800080',
           'Stromal'='#F5DE6C')

Cellpop.compartment$colors.compartments = compartment
Cellpop.compartment$colors.compartments = mapvalues(Cellpop.compartment$colors.compartments, names(colors.compartments), colors.compartments, warn_missing = TRUE)
gaps.compartments = c(3, 9, 11, 12)

In [276]:
# Load and prepare Gaulton DB
Gaulton.db.dir = "/nfs/lab/Luca/Assets/LR.Database/GaultonDB_V3.txt"
# Load list of ligands and receptors
SM.ls.df = read.table(paste(assets.dir, "SM.ls.df.txt", sep=""), sep = "\t", stringsAsFactors = F, header = T)
SM.ls = unique(SM.ls.df$gene)
length(SM.ls)

# Load database
cc.db.data = read.table(cc.db, sep = "\t", stringsAsFactors = F, header = T)
# cc.db.data = cc.db.data[,c(11,2,3)]
message("CCDB number of interactions: ", length(levels(factor(cc.db.data$interaction_name))))

gaulton.db.data = read.table(Gaulton.db.dir, sep = "\t", stringsAsFactors = F, header = T)
colnames(gaulton.db.data)[1] = "gene"

SM.ls.df.GDB = merge(SM.ls.df, gaulton.db.data, by = "gene", all.x = TRUE)
SM.ls.df.GDB[is.na(SM.ls.df.GDB)] <- ""

# Calculate category sizes
categories.size = SM.ls.df.GDB[SM.ls.df.GDB$Type == "Ligand",]

# Ligands
ligands.GDB = filter(SM.ls.df.GDB, Type != "Receptor")
colnames(ligands.GDB)[1] = "ligand"
head(ligands.GDB)


Functional.classification.order = c('Hormones & Neuropeptides', 'Enzymes', 'Developmental Proteins', 
                                    'Growth Factors and Cytokines', 'Antigen-Presenting Molecules', 'Complement System',
                                    'Immune regulators', 'Modulators', 'Cell Adhesion Molecule', 'ECM Proteins')

[1] 857

CCDB number of interactions: 1939

  ligand  Type   Mode.of.Action     Signaling
1 ADCYAP1 Ligand Secreted Signaling Hormones & Neuropeptides
2 ADGRE5  Ligand Cell-Cell Contact  CAM
3 ADIPOQ  Ligand Secreted Signaling Growth Factors & Cytokines
4 ADM     Ligand Secreted Signaling Hormones & Neuropeptides
5 AGRN    Ligand ECM-Receptor       ECM
6 AGT     Ligand Secreted Signaling Hormones & Neuropeptides
  Functional.classification Functional.sub.classification
1 Other                     Other
2 Other                     Other Cell Adhesion Proteins
3 Other Cytokines           Other Cytokines
4 Hormone-like (Heart)      Hormone (Heart)
5 Other                     Other ECM proteins
6 Hormone (Liver)           Hormone (Liver)
  Gene.Family
1 PACAP Family
2 -
3 Adipokine Family
4 Adrenomedullin Family
5 Agrin Family
6 Angiotensinogen Family

# Permutation test

## Observations

In [277]:
LR.data.consensus.sig.thresh = read.table(paste(results.dir,
                                               "LR.data.consensus.sig.thresh.txt", sep = ""),
                                          sep = "\t", stringsAsFactors = F, header = T)
LR.data.consensus.sig.thresh = LR.data.consensus.sig.thresh[LR.data.consensus.sig.thresh$target %in% cell.pop.order, ]
LR.data.consensus.sig.thresh = LR.data.consensus.sig.thresh[LR.data.consensus.sig.thresh$source %in% cell.pop.order, ]

In [278]:
# Split LR pairs
LR.data.ND = LR.data.consensus.sig.thresh[LR.data.consensus.sig.thresh$condition == condition.ls[1], ]
LR.data.AAB = LR.data.consensus.sig.thresh[LR.data.consensus.sig.thresh$condition == condition.ls[2], ]
LR.data.ETD = LR.data.consensus.sig.thresh[LR.data.consensus.sig.thresh$condition == condition.ls[3], ]
LR.data.LTD = LR.data.consensus.sig.thresh[LR.data.consensus.sig.thresh$condition == condition.ls[4], ]
nrow(LR.data.consensus.sig.thresh)
# Print stats
message("LR pairs in ND: ", nrow(LR.data.ND))
message("LR pairs in AAB : ", nrow(LR.data.AAB))
message("LR pairs in Early T1D: ", nrow(LR.data.ETD))
message("LR pairs in Late T1D: ", nrow(LR.data.LTD))

[1] 87650

LR pairs in ND: 27139

LR pairs in AAB : 27459

LR pairs in Early T1D: 18179

LR pairs in Late T1D: 14873

In [279]:
head(LR.data.consensus.sig.thresh, n=1)

  ligand  source target             receptor  prob          pval
1 ADCYAP1 Beta   Quiescent_Stellate ADCYAP1R1 0.00006164112 0.0001
  interaction_name  interaction_name_2  pathway_name annotation         ⋯
1 ADCYAP1_ADCYAP1R1 ADCYAP1 - ADCYAP1R1 PACAP        Secreted Signaling ⋯
  FDR         interaction.id                               compartment.source
1 0.000153715 Beta--Quiescent_Stellate--ADCYAP1--ADCYAP1R1 Endocrine
  compartment.target Type   Mode.of.Action     Signaling
1 Stromal            Ligand Secreted Signaling Hormones & Neuropeptides
  Functional.classification Functional.sub.classification Gene.Family
1 Other                     Other                         PACAP Family

In [280]:
condition.sizes = c(nrow(LR.data.ND), nrow(LR.data.AAB), nrow(LR.data.ETD), nrow(LR.data.LTD))
condition.sizes

condition.size_1 = c(condition.sizes[2], condition.sizes[3], condition.sizes[4])
condition.size_2 = c(condition.sizes[1], condition.sizes[1], condition.sizes[1])

[1] 27139 27459 18179 14873

In [281]:
nsim = 100

In [282]:
# Create a named vector that maps conditions to sizes
condition_mapping <- c("ND" = condition.sizes[1], "Aab" = condition.sizes[2],
                       "T1D_early" = condition.sizes[3], "T1D_late" = condition.sizes[4])

In [283]:
LR.data.consensus.use = LR.data.consensus.sig.thresh
nrow(LR.data.consensus.use)

[1] 87650

In [284]:
head(LR.data.consensus.use, n = 2)

  ligand  source target             receptor  prob          pval
1 ADCYAP1 Beta   Quiescent_Stellate ADCYAP1R1 0.00006164112 0.0001
2 ADCYAP1 Beta   Activated_Stellate ADCYAP1R1 0.00022605242 0.0001
  interaction_name  interaction_name_2  pathway_name annotation         ⋯
1 ADCYAP1_ADCYAP1R1 ADCYAP1 - ADCYAP1R1 PACAP        Secreted Signaling ⋯
2 ADCYAP1_ADCYAP1R1 ADCYAP1 - ADCYAP1R1 PACAP        Secreted Signaling ⋯
  FDR         interaction.id                               compartment.source
1 0.000153715 Beta--Quiescent_Stellate--ADCYAP1--ADCYAP1R1 Endocrine
2 0.000153715 Beta--Activated_Stellate--ADCYAP1--ADCYAP1R1 Endocrine
  compartment.target Type   Mode.of.Action     Signaling
1 Stromal            Ligand Secreted Signaling Hormones & Neuropeptides
2 Stromal            Ligand Secreted Signaling Hormones & Neuropeptides
  Functional.classification Functional.sub.classification Gene.Family
1 Other                     Other                         PACAP Family
2 Other                     Other                         PACAP Family

In [285]:
# Perform the aggregation
aggregated_data <- aggregate(prob ~ Signaling + source + target + condition + compartment.source + compartment.target, LR.data.consensus.sig.thresh, sum)
# normalize by condition size
aggregated_data <- aggregated_data %>%
  dplyr::mutate(prob.norm = prob / condition_mapping[as.character(condition)]) %>%
  dplyr::mutate(condition.size = condition_mapping[as.character(condition)])
aggregated_data$compartment.source = factor(aggregated_data$compartment.source, levels = unique(compartment))
aggregated_data$compartment.target = factor(aggregated_data$compartment.target, levels = unique(compartment))
aggregated_data$classification.source.target = paste(aggregated_data$Signaling, aggregated_data$source, aggregated_data$target, sep = "--")

In [286]:
head(filter(aggregated_data, condition == "ND"))

  Signaling                  source target condition compartment.source
1 CAM                        Alpha  Alpha  ND        Endocrine
2 Developmental              Alpha  Alpha  ND        Endocrine
3 ECM                        Alpha  Alpha  ND        Endocrine
4 Enzymatic                  Alpha  Alpha  ND        Endocrine
5 Growth Factors & Cytokines Alpha  Alpha  ND        Endocrine
6 Hormones & Neuropeptides   Alpha  Alpha  ND        Endocrine
  compartment.target prob         prob.norm         condition.size
1 Endocrine          0.1547314336 0.000005701441969 27139
2 Endocrine          0.0119908891 0.000000441832385 27139
3 Endocrine          0.0166483944 0.000000613449075 27139
4 Endocrine          0.0001232913 0.000000004542958 27139
5 Endocrine          0.0018826797 0.000000069371740 27139
6 Endocrine          0.0369990901 0.000001363318107 27139
  classification.source.target
1 CAM--Alpha--Alpha
2 Developmental--Alpha--Alpha
3 ECM--Alpha--Alpha
4 Enzymatic--Alpha--Alpha
5 Growth Factors & Cytokines--Alpha--Alpha
6 Hormones & Neuropeptides--Alpha--Alpha

In [287]:
diff.obs = list()
abs.diff.obs = list()
obs.interaction.consensus = list()

for (i in seq_along(Contrast_1)){
    LR.data.use <- aggregated_data
    # Subset for the contrast
    contrast = c(Contrast_1[i], Contrast_2[i])
    # Create consensus
    interaction.consensus = filter(aggregated_data, condition %in% contrast) %>%
        select(classification.source.target) %>%
        dplyr::distinct()
    obs.interaction.consensus[[i]] = interaction.consensus
    message("Processing ", Contrast_1[i], " vs ", Contrast_2[i])
    LR.data.c1 = LR.data.use[LR.data.use$condition %in% contrast[1], ]
    LR.data.c2 = LR.data.use[LR.data.use$condition %in% contrast[2], ]
    message("Distribution of interactions in contrast: \n",
            Contrast_1[i], ": ", nrow(LR.data.c1), "\n",
            Contrast_2[i], ": ", nrow(LR.data.c2))
    # Complete dataset
    LR.data.c1 = merge(LR.data.c1, interaction.consensus, by = "classification.source.target", all.y = TRUE)
    LR.data.c2 = merge(LR.data.c2, interaction.consensus, by = "classification.source.target", all.y = TRUE)
    # Replace NA with 0
    LR.data.c1$prob.norm[is.na(LR.data.c1$prob.norm)] = 0
    LR.data.c2$prob.norm[is.na(LR.data.c2$prob.norm)] = 0 
    message("Distribution of interactions in contrast - Number should be the same - : \n",
            Contrast_1[i], ": ", nrow(LR.data.c1), "\n",
            Contrast_2[i], ": ", nrow(LR.data.c2))
    # Order 
    LR.data.c1 = arrange(LR.data.c1, classification.source.target)
    LR.data.c2 = arrange(LR.data.c2, classification.source.target)
    message("Are Dataframe ordered in the same way? ", identical(LR.data.c1$classification.source.target, LR.data.c2$classification.source.target))
    # Compute difference
    diff = LR.data.c1$prob.norm - LR.data.c2$prob.norm
    diff.obs[[i]] = data.frame(classification.source.target = LR.data.c1$classification.source.target,
                               condition = contrast[1],
                               diff = diff, abs.diff = abs(diff))
}

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1255
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1016
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 849
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

## Simulations

In [288]:
setwd(permutations.test.tmp.dir)
sim.list <- dir(pattern = "_DFnet.txt")

In [289]:
# Create tables to fill up
diff.sim = list()
random.success.table = list()
# Create tables with correct number of rows
random.success.table[[1]] = data.frame(classification.source.target = obs.interaction.consensus[[1]])
random.success.table[[2]] = data.frame(classification.source.target = obs.interaction.consensus[[2]])
random.success.table[[3]] = data.frame(classification.source.target = obs.interaction.consensus[[3]])

for (s.i in seq_along(sim.list)){
        # Get files
        print(paste0("Processing: ", sim.list[s.i]))
        # Load simulation data
        LR.data.use <- read.table(sim.list[s.i], sep = "\t", stringsAsFactors = F, header = T)
        # add functional classification info
        LR.data.use = merge(LR.data.use, ligands.GDB, by = "ligand")
        message("\t Detected: ", nrow(LR.data.use), " interactions")
        # Create a named vector that maps conditions to sizes
        condition.sim_mapping <- c("ND" = nrow(LR.data.use[LR.data.use$condition == "ND",]),
                               "Aab" = nrow(LR.data.use[LR.data.use$condition == "Aab",]),          
                               "T1D_early" = nrow(LR.data.use[LR.data.use$condition == "T1D_early",]),           
                               "T1D_late" = nrow(LR.data.use[LR.data.use$condition == "T1D_late",]))
        message(" Normalizing ND: ", condition.sim_mapping[1],
                "\n Normalizing AAB: ", condition.sim_mapping[2],
                "\n Normalizing ETD: ", condition.sim_mapping[3],
                "\n Normalizing LTD: ", condition.sim_mapping[4]
               )        
        # Perform the aggregation
        aggregated_data.sim <- aggregate(prob ~ Signaling + source + target + condition, LR.data.use, sum)
        # normalize by condition size
        aggregated_data.sim <- aggregated_data.sim %>%
          dplyr::mutate(prob.norm = prob / condition.sim_mapping[as.character(condition)]) %>%
          dplyr::mutate(condition.size = condition_mapping[as.character(condition)])
        aggregated_data.sim$classification.source.target = paste(aggregated_data.sim$Signaling, aggregated_data.sim$source, aggregated_data.sim$target, sep = "--")
        for (i in seq_along(Contrast_1)){
                        # Subset for the contrast
                        contrast = c(Contrast_1[i], Contrast_2[i])
                        message("Processing ", Contrast_1[i], " vs ", Contrast_2[i])
                        # Use consensus of the observations to compare the same category
                        interaction.consensus = obs.interaction.consensus[[i]]
                        LR.data.c1 = aggregated_data.sim[aggregated_data.sim$condition %in% contrast[1], ]
                        LR.data.c2 = aggregated_data.sim[aggregated_data.sim$condition %in% contrast[2], ]
                        message("Distribution of interactions in contrast: \n",
                                Contrast_1[i], ": ", nrow(LR.data.c1), "\n",
                                Contrast_2[i], ": ", nrow(LR.data.c2))
                        # Complete dataset
                        LR.data.c1 = merge(LR.data.c1, interaction.consensus, by = "classification.source.target", all.y = TRUE)
                        LR.data.c2 = merge(LR.data.c2, interaction.consensus, by = "classification.source.target", all.y = TRUE)
                        # Replace NA with 0
                        LR.data.c1$prob.norm[is.na(LR.data.c1$prob.norm)] = 0
                        LR.data.c2$prob.norm[is.na(LR.data.c2$prob.norm)] = 0 
                        message("Distribution of interactions in contrast - Number should be the same - : \n",
                                Contrast_1[i], ": ", nrow(LR.data.c1), "\n",
                                Contrast_2[i], ": ", nrow(LR.data.c2))
                        # Order 
                        LR.data.c1 = arrange(LR.data.c1, classification.source.target)
                        LR.data.c2 = arrange(LR.data.c2, classification.source.target)
                        message("Are Dataframe ordered in the same way? ", identical(LR.data.c1$classification.source.target, LR.data.c2$classification.source.target))
                        # Compute difference
                        diff = LR.data.c1$prob.norm - LR.data.c2$prob.norm
                        diff.sim[[i]] = data.frame(classification.source.target = LR.data.c1$classification.source.target, condition = contrast[1],
                                        diff = diff, abs.diff = abs(diff))
                        random.success = diff.sim[[i]]$abs.diff > diff.obs[[i]]$abs.diff
                        random.success.table[[i]] = cbind(random.success.table[[i]], random.success)
                        colnames(random.success.table[[i]])[ncol(random.success.table[[i]])] = s.i  
                }
}

[1] "Processing: CellChat_Permutation_n1_DFnet.txt"

	 Detected: 99223 interactions

 Normalizing ND: 21962
 Normalizing AAB: 27346
 Normalizing ETD: 26497
 Normalizing LTD: 23418

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1238
ND: 1176

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1241
ND: 1176

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1176

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n10_DFnet.txt"

	 Detected: 100143 interactions

 Normalizing ND: 27234
 Normalizing AAB: 25830
 Normalizing ETD: 23698
 Normalizing LTD: 23381

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1227
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1210
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1212
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n100_DFnet.txt"

	 Detected: 100138 interactions

 Normalizing ND: 26694
 Normalizing AAB: 23830
 Normalizing ETD: 23624
 Normalizing LTD: 25990

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1220
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1210
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1253
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n11_DFnet.txt"

	 Detected: 99880 interactions

 Normalizing ND: 27702
 Normalizing AAB: 25778
 Normalizing ETD: 22516
 Normalizing LTD: 23884

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1209
ND: 1251

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1195
ND: 1251

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1216
ND: 1251

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n12_DFnet.txt"

	 Detected: 98969 interactions

 Normalizing ND: 23865
 Normalizing AAB: 26969
 Normalizing ETD: 24297
 Normalizing LTD: 23838

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1250
ND: 1206

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1223
ND: 1206

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1219
ND: 1206

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n13_DFnet.txt"

	 Detected: 100772 interactions

 Normalizing ND: 26104
 Normalizing AAB: 25885
 Normalizing ETD: 25537
 Normalizing LTD: 23246

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1218
ND: 1237

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1234
ND: 1237

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1210
ND: 1237

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n14_DFnet.txt"

	 Detected: 99891 interactions

 Normalizing ND: 25761
 Normalizing AAB: 26399
 Normalizing ETD: 23388
 Normalizing LTD: 24343

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1241
ND: 1222

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1216
ND: 1222

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1225
ND: 1222

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n15_DFnet.txt"

	 Detected: 100396 interactions

 Normalizing ND: 25808
 Normalizing AAB: 25058
 Normalizing ETD: 22324
 Normalizing LTD: 27206

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1240
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1173
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1237
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n16_DFnet.txt"

	 Detected: 96849 interactions

 Normalizing ND: 25262
 Normalizing AAB: 24958
 Normalizing ETD: 19349
 Normalizing LTD: 27280

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1216
ND: 1208

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1029
ND: 1208

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1260
ND: 1208

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n17_DFnet.txt"

	 Detected: 98381 interactions

 Normalizing ND: 23106
 Normalizing AAB: 27027
 Normalizing ETD: 24924
 Normalizing LTD: 23324

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1237
ND: 1077

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1225
ND: 1077

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1077

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n18_DFnet.txt"

	 Detected: 101101 interactions

 Normalizing ND: 26505
 Normalizing AAB: 23459
 Normalizing ETD: 26979
 Normalizing LTD: 24158

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1204
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1240
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1245
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n19_DFnet.txt"

	 Detected: 95054 interactions

 Normalizing ND: 27143
 Normalizing AAB: 23033
 Normalizing ETD: 19502
 Normalizing LTD: 25376

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1190
ND: 1234

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1125
ND: 1234

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1236
ND: 1234

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n2_DFnet.txt"

	 Detected: 99460 interactions

 Normalizing ND: 26276
 Normalizing AAB: 27931
 Normalizing ETD: 20563
 Normalizing LTD: 24690

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1252
ND: 1251

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1182
ND: 1251

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1215
ND: 1251

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n20_DFnet.txt"

	 Detected: 99101 interactions

 Normalizing ND: 25654
 Normalizing AAB: 20642
 Normalizing ETD: 27768
 Normalizing LTD: 25037

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1177
ND: 1225

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1261
ND: 1225

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1245
ND: 1225

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n21_DFnet.txt"

	 Detected: 98226 interactions

 Normalizing ND: 26388
 Normalizing AAB: 27291
 Normalizing ETD: 19927
 Normalizing LTD: 24620

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1243
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1166
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1206
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n22_DFnet.txt"

	 Detected: 101276 interactions

 Normalizing ND: 25502
 Normalizing AAB: 25447
 Normalizing ETD: 26191
 Normalizing LTD: 24136

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1211
ND: 1217

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1246
ND: 1217

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1237
ND: 1217

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n23_DFnet.txt"

	 Detected: 98941 interactions

 Normalizing ND: 24202
 Normalizing AAB: 22470
 Normalizing ETD: 26893
 Normalizing LTD: 25376

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1178
ND: 1205

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1261
ND: 1205

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1236
ND: 1205

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n24_DFnet.txt"

	 Detected: 97109 interactions

 Normalizing ND: 27232
 Normalizing AAB: 26001
 Normalizing ETD: 19535
 Normalizing LTD: 24341

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1230
ND: 1250

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1151
ND: 1250

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1219
ND: 1250

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n25_DFnet.txt"

	 Detected: 97894 interactions

 Normalizing ND: 26922
 Normalizing AAB: 23094
 Normalizing ETD: 22727
 Normalizing LTD: 25151

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1176
ND: 1237

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1214
ND: 1237

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1225
ND: 1237

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n26_DFnet.txt"

	 Detected: 100134 interactions

 Normalizing ND: 27668
 Normalizing AAB: 24310
 Normalizing ETD: 24902
 Normalizing LTD: 23254

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1211
ND: 1247

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1221
ND: 1247

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1247

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n27_DFnet.txt"

	 Detected: 98601 interactions

 Normalizing ND: 26751
 Normalizing AAB: 26147
 Normalizing ETD: 21794
 Normalizing LTD: 23909

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1241
ND: 1258

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1188
ND: 1258

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1218
ND: 1258

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n28_DFnet.txt"

	 Detected: 101216 interactions

 Normalizing ND: 24526
 Normalizing AAB: 25938
 Normalizing ETD: 25149
 Normalizing LTD: 25603

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1244
ND: 1211

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1239
ND: 1211

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1212
ND: 1211

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n29_DFnet.txt"

	 Detected: 101411 interactions

 Normalizing ND: 22568
 Normalizing AAB: 26802
 Normalizing ETD: 26898
 Normalizing LTD: 25143

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1252
ND: 1207

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1254
ND: 1207

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1207

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n3_DFnet.txt"

	 Detected: 100192 interactions

 Normalizing ND: 22344
 Normalizing AAB: 24897
 Normalizing ETD: 25630
 Normalizing LTD: 27321

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1236
ND: 1182

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1213
ND: 1182

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1247
ND: 1182

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n30_DFnet.txt"

	 Detected: 99017 interactions

 Normalizing ND: 25612
 Normalizing AAB: 22730
 Normalizing ETD: 22689
 Normalizing LTD: 27986

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1184
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1192
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1262
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n31_DFnet.txt"

	 Detected: 99636 interactions

 Normalizing ND: 25364
 Normalizing AAB: 23093
 Normalizing ETD: 25427
 Normalizing LTD: 25752

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1194
ND: 1213

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1243
ND: 1213

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1246
ND: 1213

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n32_DFnet.txt"

	 Detected: 101462 interactions

 Normalizing ND: 24786
 Normalizing AAB: 26508
 Normalizing ETD: 25598
 Normalizing LTD: 24570

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1230
ND: 1217

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1233
ND: 1217

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1204
ND: 1217

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n33_DFnet.txt"

	 Detected: 94749 interactions

 Normalizing ND: 27945
 Normalizing AAB: 21499
 Normalizing ETD: 19837
 Normalizing LTD: 25468

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1182
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1163
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1219
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n34_DFnet.txt"

	 Detected: 94899 interactions

 Normalizing ND: 26892
 Normalizing AAB: 24758
 Normalizing ETD: 18592
 Normalizing LTD: 24657

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1234
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1150
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1215
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n35_DFnet.txt"

	 Detected: 99897 interactions

 Normalizing ND: 24611
 Normalizing AAB: 26571
 Normalizing ETD: 22719
 Normalizing LTD: 25996

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1248
ND: 1200

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1216
ND: 1200

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1238
ND: 1200

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n36_DFnet.txt"

	 Detected: 99237 interactions

 Normalizing ND: 26105
 Normalizing AAB: 26375
 Normalizing ETD: 20435
 Normalizing LTD: 26322

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1220
ND: 1214

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1187
ND: 1214

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1239
ND: 1214

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n37_DFnet.txt"

	 Detected: 99847 interactions

 Normalizing ND: 26844
 Normalizing AAB: 25261
 Normalizing ETD: 24336
 Normalizing LTD: 23406

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1223
ND: 1257

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1223
ND: 1257

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1208
ND: 1257

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n38_DFnet.txt"

	 Detected: 101562 interactions

 Normalizing ND: 24440
 Normalizing AAB: 27467
 Normalizing ETD: 24964
 Normalizing LTD: 24691

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1237
ND: 1216

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1226
ND: 1216

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1215
ND: 1216

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n39_DFnet.txt"

	 Detected: 100443 interactions

 Normalizing ND: 25486
 Normalizing AAB: 27401
 Normalizing ETD: 23104
 Normalizing LTD: 24452

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1239
ND: 1199

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1207
ND: 1199

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1213
ND: 1199

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n4_DFnet.txt"

	 Detected: 98151 interactions

 Normalizing ND: 25891
 Normalizing AAB: 25798
 Normalizing ETD: 22357
 Normalizing LTD: 24105

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1218
ND: 1233

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1195
ND: 1233

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1223
ND: 1233

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n40_DFnet.txt"

	 Detected: 100696 interactions

 Normalizing ND: 25060
 Normalizing AAB: 26098
 Normalizing ETD: 23853
 Normalizing LTD: 25685

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1231
ND: 1202

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1228
ND: 1202

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1229
ND: 1202

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n41_DFnet.txt"

	 Detected: 100239 interactions

 Normalizing ND: 26727
 Normalizing AAB: 24998
 Normalizing ETD: 23742
 Normalizing LTD: 24772

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1206
ND: 1265

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1197
ND: 1265

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1239
ND: 1265

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n42_DFnet.txt"

	 Detected: 101160 interactions

 Normalizing ND: 26918
 Normalizing AAB: 26295
 Normalizing ETD: 24065
 Normalizing LTD: 23882

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1251
ND: 1246

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1215
ND: 1246

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1203
ND: 1246

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n43_DFnet.txt"

	 Detected: 99466 interactions

 Normalizing ND: 22872
 Normalizing AAB: 27537
 Normalizing ETD: 25418
 Normalizing LTD: 23639

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1254
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1245
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1209
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n44_DFnet.txt"

	 Detected: 97153 interactions

 Normalizing ND: 26915
 Normalizing AAB: 20448
 Normalizing ETD: 23159
 Normalizing LTD: 26631

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1034
ND: 1249

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1187
ND: 1249

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1241
ND: 1249

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n45_DFnet.txt"

	 Detected: 100039 interactions

 Normalizing ND: 23710
 Normalizing AAB: 25799
 Normalizing ETD: 23025
 Normalizing LTD: 27505

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1234
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1201
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1243
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n46_DFnet.txt"

	 Detected: 98390 interactions

 Normalizing ND: 25820
 Normalizing AAB: 25398
 Normalizing ETD: 21012
 Normalizing LTD: 26160

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1227
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1194
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1238
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n47_DFnet.txt"

	 Detected: 99400 interactions

 Normalizing ND: 25610
 Normalizing AAB: 26727
 Normalizing ETD: 20774
 Normalizing LTD: 26289

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1230
ND: 1230

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1148
ND: 1230

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1239
ND: 1230

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n48_DFnet.txt"

	 Detected: 97529 interactions

 Normalizing ND: 26547
 Normalizing AAB: 18942
 Normalizing ETD: 25449
 Normalizing LTD: 26591

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1007
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1240
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1249
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n49_DFnet.txt"

	 Detected: 98290 interactions

 Normalizing ND: 24736
 Normalizing AAB: 22282
 Normalizing ETD: 26422
 Normalizing LTD: 24850

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1177
ND: 1213

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1251
ND: 1213

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1241
ND: 1213

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n5_DFnet.txt"

	 Detected: 97511 interactions

 Normalizing ND: 25160
 Normalizing AAB: 23642
 Normalizing ETD: 20165
 Normalizing LTD: 28544

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1198
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1169
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1262
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n50_DFnet.txt"

	 Detected: 98420 interactions

 Normalizing ND: 25444
 Normalizing AAB: 25383
 Normalizing ETD: 20979
 Normalizing LTD: 26614

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1216
ND: 1222

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1047
ND: 1222

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1242
ND: 1222

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n51_DFnet.txt"

	 Detected: 100657 interactions

 Normalizing ND: 25414
 Normalizing AAB: 24649
 Normalizing ETD: 26162
 Normalizing LTD: 24432

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1213
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1251
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1218
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n52_DFnet.txt"

	 Detected: 101096 interactions

 Normalizing ND: 25562
 Normalizing AAB: 22655
 Normalizing ETD: 26946
 Normalizing LTD: 25933

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1190
ND: 1207

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1257
ND: 1207

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1244
ND: 1207

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n53_DFnet.txt"

	 Detected: 101353 interactions

 Normalizing ND: 23845
 Normalizing AAB: 28030
 Normalizing ETD: 24696
 Normalizing LTD: 24782

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1264
ND: 1196

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1233
ND: 1196

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1216
ND: 1196

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n54_DFnet.txt"

	 Detected: 99845 interactions

 Normalizing ND: 26817
 Normalizing AAB: 24038
 Normalizing ETD: 25651
 Normalizing LTD: 23339

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1205
ND: 1242

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1232
ND: 1242

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1205
ND: 1242

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n55_DFnet.txt"

	 Detected: 99208 interactions

 Normalizing ND: 22455
 Normalizing AAB: 25861
 Normalizing ETD: 23570
 Normalizing LTD: 27322

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1246
ND: 1201

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1194
ND: 1201

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1248
ND: 1201

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n56_DFnet.txt"

	 Detected: 99552 interactions

 Normalizing ND: 27864
 Normalizing AAB: 23755
 Normalizing ETD: 24033
 Normalizing LTD: 23900

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1200
ND: 1243

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1207
ND: 1243

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1223
ND: 1243

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n57_DFnet.txt"

	 Detected: 100372 interactions

 Normalizing ND: 23384
 Normalizing AAB: 25312
 Normalizing ETD: 26270
 Normalizing LTD: 25406

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1213
ND: 1206

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1251
ND: 1206

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1255
ND: 1206

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n58_DFnet.txt"

	 Detected: 97562 interactions

 Normalizing ND: 27290
 Normalizing AAB: 23437
 Normalizing ETD: 21369
 Normalizing LTD: 25466

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1187
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1189
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1236
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n59_DFnet.txt"

	 Detected: 101007 interactions

 Normalizing ND: 25515
 Normalizing AAB: 27442
 Normalizing ETD: 23449
 Normalizing LTD: 24601

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1250
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1219
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1222
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n6_DFnet.txt"

	 Detected: 98706 interactions

 Normalizing ND: 25549
 Normalizing AAB: 24287
 Normalizing ETD: 22634
 Normalizing LTD: 26236

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1215
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1198
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1237
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n60_DFnet.txt"

	 Detected: 99931 interactions

 Normalizing ND: 24987
 Normalizing AAB: 23451
 Normalizing ETD: 23489
 Normalizing LTD: 28004

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1212
ND: 1224

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1198
ND: 1224

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1262
ND: 1224

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n61_DFnet.txt"

	 Detected: 100953 interactions

 Normalizing ND: 26345
 Normalizing AAB: 26743
 Normalizing ETD: 24259
 Normalizing LTD: 23606

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1245
ND: 1210

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1242
ND: 1210

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1210

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n62_DFnet.txt"

	 Detected: 95979 interactions

 Normalizing ND: 28375
 Normalizing AAB: 24347
 Normalizing ETD: 20930
 Normalizing LTD: 22327

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1214
ND: 1252

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1062
ND: 1252

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1185
ND: 1252

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n63_DFnet.txt"

	 Detected: 100284 interactions

 Normalizing ND: 24943
 Normalizing AAB: 25623
 Normalizing ETD: 26196
 Normalizing LTD: 23522

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1227
ND: 1225

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1237
ND: 1225

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1209
ND: 1225

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n64_DFnet.txt"

	 Detected: 98876 interactions

 Normalizing ND: 26841
 Normalizing AAB: 20989
 Normalizing ETD: 26093
 Normalizing LTD: 24953

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1172
ND: 1246

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1222
ND: 1246

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1216
ND: 1246

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n65_DFnet.txt"

	 Detected: 98409 interactions

 Normalizing ND: 27012
 Normalizing AAB: 25875
 Normalizing ETD: 19716
 Normalizing LTD: 25806

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1247
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1163
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1221
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n66_DFnet.txt"

	 Detected: 101795 interactions

 Normalizing ND: 24757
 Normalizing AAB: 26433
 Normalizing ETD: 26043
 Normalizing LTD: 24562

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1232
ND: 1215

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1245
ND: 1215

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1214
ND: 1215

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n67_DFnet.txt"

	 Detected: 98595 interactions

 Normalizing ND: 25372
 Normalizing AAB: 24894
 Normalizing ETD: 21700
 Normalizing LTD: 26629

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1215
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1049
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1241
ND: 1229

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n68_DFnet.txt"

	 Detected: 101574 interactions

 Normalizing ND: 25704
 Normalizing AAB: 24823
 Normalizing ETD: 26410
 Normalizing LTD: 24637

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1217
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1230
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1232
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n69_DFnet.txt"

	 Detected: 101199 interactions

 Normalizing ND: 24317
 Normalizing AAB: 26677
 Normalizing ETD: 26673
 Normalizing LTD: 23532

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1248
ND: 1230

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1239
ND: 1230

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1207
ND: 1230

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n7_DFnet.txt"

	 Detected: 100055 interactions

 Normalizing ND: 28534
 Normalizing AAB: 25154
 Normalizing ETD: 21833
 Normalizing LTD: 24534

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1229
ND: 1275

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1178
ND: 1275

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1222
ND: 1275

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n70_DFnet.txt"

	 Detected: 96221 interactions

 Normalizing ND: 24535
 Normalizing AAB: 19619
 Normalizing ETD: 26201
 Normalizing LTD: 25866

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1012
ND: 1210

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1253
ND: 1210

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1241
ND: 1210

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n71_DFnet.txt"

	 Detected: 101142 interactions

 Normalizing ND: 26018
 Normalizing AAB: 27079
 Normalizing ETD: 24546
 Normalizing LTD: 23499

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1233
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1237
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1206
ND: 1221

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n72_DFnet.txt"

	 Detected: 97318 interactions

 Normalizing ND: 22135
 Normalizing AAB: 25821
 Normalizing ETD: 23525
 Normalizing LTD: 25837

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1242
ND: 1200

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1194
ND: 1200

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1233
ND: 1200

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n73_DFnet.txt"

	 Detected: 100515 interactions

 Normalizing ND: 25493
 Normalizing AAB: 25633
 Normalizing ETD: 25013
 Normalizing LTD: 24376

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1227
ND: 1234

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1211
ND: 1234

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1239
ND: 1234

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n74_DFnet.txt"

	 Detected: 99177 interactions

 Normalizing ND: 25917
 Normalizing AAB: 25493
 Normalizing ETD: 22118
 Normalizing LTD: 25649

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1232
ND: 1232

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1182
ND: 1232

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1223
ND: 1232

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n75_DFnet.txt"

	 Detected: 100637 interactions

 Normalizing ND: 24691
 Normalizing AAB: 24182
 Normalizing ETD: 25261
 Normalizing LTD: 26503

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1203
ND: 1215

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1238
ND: 1215

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1234
ND: 1215

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n76_DFnet.txt"

	 Detected: 98782 interactions

 Normalizing ND: 26096
 Normalizing AAB: 27003
 Normalizing ETD: 22342
 Normalizing LTD: 23341

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1241
ND: 1211

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1196
ND: 1211

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1211

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n77_DFnet.txt"

	 Detected: 94620 interactions

 Normalizing ND: 26927
 Normalizing AAB: 17908
 Normalizing ETD: 24809
 Normalizing LTD: 24976

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 886
ND: 1245

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1220
ND: 1245

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1222
ND: 1245

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n78_DFnet.txt"

	 Detected: 100645 interactions

 Normalizing ND: 27275
 Normalizing AAB: 24392
 Normalizing ETD: 25508
 Normalizing LTD: 23470

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1217
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1221
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1204
ND: 1235

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n79_DFnet.txt"

	 Detected: 96783 interactions

 Normalizing ND: 26807
 Normalizing AAB: 20406
 Normalizing ETD: 23836
 Normalizing LTD: 25734

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1045
ND: 1254

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1201
ND: 1254

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1216
ND: 1254

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n8_DFnet.txt"

	 Detected: 100487 interactions

 Normalizing ND: 25334
 Normalizing AAB: 26608
 Normalizing ETD: 23782
 Normalizing LTD: 24763

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1231
ND: 1204

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1208
ND: 1204

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1221
ND: 1204

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n80_DFnet.txt"

	 Detected: 99429 interactions

 Normalizing ND: 24771
 Normalizing AAB: 23308
 Normalizing ETD: 24169
 Normalizing LTD: 27181

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1205
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1183
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1237
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n81_DFnet.txt"

	 Detected: 97406 interactions

 Normalizing ND: 29256
 Normalizing AAB: 23324
 Normalizing ETD: 21507
 Normalizing LTD: 23319

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1206
ND: 1260

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1185
ND: 1260

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1210
ND: 1260

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n82_DFnet.txt"

	 Detected: 98072 interactions

 Normalizing ND: 26663
 Normalizing AAB: 21050
 Normalizing ETD: 26566
 Normalizing LTD: 23793

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1170
ND: 1224

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1259
ND: 1224

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1221
ND: 1224

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n83_DFnet.txt"

	 Detected: 97387 interactions

 Normalizing ND: 26163
 Normalizing AAB: 25389
 Normalizing ETD: 19658
 Normalizing LTD: 26177

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1227
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1040
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1250
ND: 1228

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n84_DFnet.txt"

	 Detected: 98717 interactions

 Normalizing ND: 26852
 Normalizing AAB: 22289
 Normalizing ETD: 24428
 Normalizing LTD: 25148

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1211
ND: 1242

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1204
ND: 1242

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1231
ND: 1242

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n85_DFnet.txt"

	 Detected: 97370 interactions

 Normalizing ND: 27130
 Normalizing AAB: 24360
 Normalizing ETD: 21007
 Normalizing LTD: 24873

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1207
ND: 1240

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1055
ND: 1240

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1215
ND: 1240

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n86_DFnet.txt"

	 Detected: 99475 interactions

 Normalizing ND: 25603
 Normalizing AAB: 22171
 Normalizing ETD: 25020
 Normalizing LTD: 26681

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1193
ND: 1214

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1212
ND: 1214

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1251
ND: 1214

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n87_DFnet.txt"

	 Detected: 96666 interactions

 Normalizing ND: 26118
 Normalizing AAB: 23026
 Normalizing ETD: 21819
 Normalizing LTD: 25703

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1177
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1072
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1239

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n88_DFnet.txt"

	 Detected: 100491 interactions

 Normalizing ND: 27286
 Normalizing AAB: 26762
 Normalizing ETD: 22054
 Normalizing LTD: 24389

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1225
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1196
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1228
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n89_DFnet.txt"

	 Detected: 99923 interactions

 Normalizing ND: 22622
 Normalizing AAB: 26213
 Normalizing ETD: 26828
 Normalizing LTD: 24260

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1229
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1245
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1241
ND: 1193

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n9_DFnet.txt"

	 Detected: 99284 interactions

 Normalizing ND: 26445
 Normalizing AAB: 23486
 Normalizing ETD: 26966
 Normalizing LTD: 22387

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1183
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1260
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1190
ND: 1248

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n90_DFnet.txt"

	 Detected: 99562 interactions

 Normalizing ND: 24786
 Normalizing AAB: 26798
 Normalizing ETD: 22070
 Normalizing LTD: 25908

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1238
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1173
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1236
ND: 1231

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n91_DFnet.txt"

	 Detected: 100833 interactions

 Normalizing ND: 23202
 Normalizing AAB: 24769
 Normalizing ETD: 28853
 Normalizing LTD: 24009

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1219
ND: 1196

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1262
ND: 1196

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1245
ND: 1196

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n92_DFnet.txt"

	 Detected: 96892 interactions

 Normalizing ND: 20201
 Normalizing AAB: 25187
 Normalizing ETD: 27300
 Normalizing LTD: 24204

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1208
ND: 1033

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1259
ND: 1033

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1239
ND: 1033

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n93_DFnet.txt"

	 Detected: 96566 interactions

 Normalizing ND: 28201
 Normalizing AAB: 24999
 Normalizing ETD: 19852
 Normalizing LTD: 23514

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1200
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1021
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1223
ND: 1253

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n94_DFnet.txt"

	 Detected: 100900 interactions

 Normalizing ND: 24497
 Normalizing AAB: 26885
 Normalizing ETD: 25916
 Normalizing LTD: 23602

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1241
ND: 1195

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1235
ND: 1195

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1195

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n95_DFnet.txt"

	 Detected: 99043 interactions

 Normalizing ND: 24546
 Normalizing AAB: 26491
 Normalizing ETD: 22193
 Normalizing LTD: 25813

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1241
ND: 1202

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1054
ND: 1202

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1231
ND: 1202

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n96_DFnet.txt"

	 Detected: 100580 interactions

 Normalizing ND: 24710
 Normalizing AAB: 27050
 Normalizing ETD: 24952
 Normalizing LTD: 23868

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1229
ND: 1232

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1245
ND: 1232

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1203
ND: 1232

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n97_DFnet.txt"

	 Detected: 100686 interactions

 Normalizing ND: 25551
 Normalizing AAB: 26512
 Normalizing ETD: 25835
 Normalizing LTD: 22788

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1233
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1240
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1223
ND: 1227

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n98_DFnet.txt"

	 Detected: 98776 interactions

 Normalizing ND: 27324
 Normalizing AAB: 24853
 Normalizing ETD: 21963
 Normalizing LTD: 24636

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1216
ND: 1241

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1164
ND: 1241

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1228
ND: 1241

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

[1] "Processing: CellChat_Permutation_n99_DFnet.txt"

	 Detected: 100458 interactions

 Normalizing ND: 28236
 Normalizing AAB: 24233
 Normalizing ETD: 24409
 Normalizing LTD: 23580

Processing Aab vs ND

Distribution of interactions in contrast:
Aab: 1218
ND: 1259

Distribution of interactions in contrast - Number should be the same - :
Aab: 1286
ND: 1286

Are Dataframe ordered in the same way? TRUE

Processing T1D_early vs ND

Distribution of interactions in contrast:
T1D_early: 1207
ND: 1259

Distribution of interactions in contrast - Number should be the same - :
T1D_early: 1267
ND: 1267

Are Dataframe ordered in the same way? TRUE

Processing T1D_late vs ND

Distribution of interactions in contrast:
T1D_late: 1217
ND: 1259

Distribution of interactions in contrast - Number should be the same - :
T1D_late: 1257
ND: 1257

Are Dataframe ordered in the same way? TRUE

In [295]:
# Wrap up test results
for (i in seq_along(diff.obs)){
    message("Processing contrast #", i)
    diff.obs[[i]]$random.success = rowSums(random.success.table[[i]] == "TRUE", na.rm = TRUE)
    diff.obs[[i]]$pvalue = diff.obs[[i]]$random.success/nsim
    # correct pvalues of what had no difference to begin with
    diff.obs[[i]]$pvalue = replace(diff.obs[[i]]$pvalue, diff.obs[[i]]$diff == 0, 1)
    # calculate FDR
    diff.obs[[i]]$pvalue[diff.obs[[i]]$pvalue == 0] = 0.0001
    diff.obs[[i]]$FDR = p.adjust(diff.obs[[i]]$pvalue, 'BH')
    # counting stars
    diff.obs[[i]]$stars = diff.obs[[i]]$FDR
    diff.obs[[i]]$stars[diff.obs[[i]]$FDR > 0.1]<-""
    diff.obs[[i]]$stars[diff.obs[[i]]$FDR < 0.1]<-"*"
    diff.obs[[i]]$stars[diff.obs[[i]]$FDR < 0.05]<-"**"
    diff.obs[[i]]$stars[diff.obs[[i]]$FDR < 0.01]<-"***"
    file.name = paste(permutations.test.res.dir, "Permutation.test_cellpairs_signaling.", Contrast_1[i], ".res", sep = "")
    write.table(diff.obs[[i]], file.name, sep = "\t", quote = F, col.names=T, row.names = T) 
}

Processing contrast #1

Processing contrast #2

Processing contrast #3

In [296]:
test = filter(diff.obs[[2]], pvalue < 0.05)
nrow(test)
test = filter(diff.obs[[2]], FDR < 0.1)
nrow(test)

[1] 299

[1] 182

In [312]:
cell.pairs.classification = NULL
setwd(permutations.test.res.dir)

for (i in dir(pattern = "Permutation.test_cellpairs_signaling.")){
    message(i)
    data.use = read.table(i, sep = "\t")
    cell.pairs.classification = rbind(cell.pairs.classification, data.use)
}

Permutation.test_cellpairs_signaling.Aab.res

Permutation.test_cellpairs_signaling.T1D_early.res

Permutation.test_cellpairs_signaling.T1D_late.res

In [313]:
# Add metadata
cell.pairs.classification$classification = str_split_fixed(cell.pairs.classification$classification.source.target, pattern = "--", n = 3)[,1]
cell.pairs.classification$source = str_split_fixed(cell.pairs.classification$classification.source.target, pattern = "--", n = 3)[,2]
cell.pairs.classification$target = str_split_fixed(cell.pairs.classification$classification.source.target, pattern = "--", n = 3)[,3]
cell.pairs.classification = merge(cell.pairs.classification, Cellpop.compartment, 
                                  by.x = "source", by.y = "Celltype")
cell.pairs.classification$compartment = factor(cell.pairs.classification$compartment, levels = unique(compartment))
cell.pairs.classification$source = factor(cell.pairs.classification$source, levels = cell.pop.order)
cell.pairs.classification$target = factor(cell.pairs.classification$target, levels = cell.pop.order)

# Linear transformation
# normalize applying linear transformation
cell.pairs.classification$diff = cell.pairs.classification$diff * 10000
cell.pairs.classification$abs.diff = cell.pairs.classification$abs.diff * 10000

head(cell.pairs.classification, n= 2)

  source   classification.source.target     condition diff
1 Acinar_3 Enzymatic--Acinar_3--Endothelial T1D_early 0.015080276135
2 Acinar_3 Enzymatic--Acinar_3--Tcells      Aab       0.000007828976
  abs.diff       random.success pvalue FDR       stars classification
1 0.015080276135  11            0.11   0.3203908       Enzymatic
2 0.000007828976 100            1.00   1.0000000 NA    Enzymatic
  target      compartment colors.compartments
1 Endothelial Exocrine    #ed872d
2 Tcells      Exocrine    #ed872d

In [314]:
file.name = paste(permutations.test.res.dir, "Permutation.test_ALL_cellpairs_signaling.res", sep = "")
write.table(cell.pairs.classification, file.name, sep = "\t", quote = F, col.names=T, row.names = T)

# Plot

In [318]:
# Normalize adding the same 10k to the differece
# add labels to the sankey plot
# Show sankey plots for both beta to all and all to beta

In [320]:
cell.use = "Beta"
condition.ls

[1] "ND"        "Aab"       "T1D_early" "T1D_late"

In [348]:
plot.data = cell.pairs.classification %>%
        dplyr::mutate(source.classification = paste(source, classification, sep = "--"))%>%
        dplyr::mutate(direction = ifelse(diff > 0, "up", "down"))%>%
        dplyr::filter(source == "Beta" &
                      condition %in% condition.ls[3] &
                      !classification %in% c("Other"))

In [349]:
plot.data$diff.scaled <- scale(plot.data$diff)

In [351]:
ggplot(plot.data, aes(axis1 = classification, axis2 = target, y = diff)) +
  geom_alluvium(aes(fill = classification, alpha = -log(FDR)), color = "black") +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  facet_grid(direction ~ source, scales = "free", space = "free") +
  theme_bw()

ERROR while rich displaying an object: Error in `combine_vars()`:
! At least one layer must contain all faceting variables: `up or down`
✖ Plot is missing `up or down`
✖ Layer 1 is missing `up or down`
✖ Layer 2 is missing `up or down`
✖ Layer 3 is missing `up or down`
✖ Layer 4 is missing `up or down`

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, classes, parentenv, handlers)
3. tryCatchOne(expr, names, parentenv, handlers[[1L]])
4. doTryCatch(return(expr), name, parentenv, handler)
5. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
6. repr::mime2repr[[mime]](obj)
7. repr_text.default(obj)
8. paste(capture.output(print(obj)), collapse = "\n")
9. capture.output(print(obj))
10. withVisible(...elt(i))
11. print(obj)
12. print.ggplot(obj)
13. ggplot_build(x)
14. ggplot_build.ggplot(x)
15. layout$setup(data, plot$data, plot$plot_env)
16. setup(..., self = self)
17. self$facet$compute_layout(data, self$facet_params)
18. compute_layout(..., self = self)
19. combine_vars(data, params$plot_env, rows, drop = params$drop)
20. cli::cli_abort(c("At least one layer must contain all faceting variables: {.var {names(vars)}}",
  .     missing_vars))
21. rlang::abort(message, ..., call = call, use_cli_format = TRUE,
  .     .frame = .frame)
22. signal_abort(cnd, .file)

In [85]:
# Perform the aggregation
aggregated_data <- aggregate(prob ~ Functional.classification + source + target + condition + compartment.source + compartment.target, LR.data.consensus.sig.thresh, sum)
# normalize by condition size
aggregated_data <- aggregated_data %>%
  dplyr::mutate(prob.norm = prob / condition_mapping[as.character(condition)]) %>%
  dplyr::mutate(condition.size = condition_mapping[as.character(condition)])
aggregated_data$compartment.source = factor(aggregated_data$compartment.source, levels = unique(compartment))
aggregated_data$compartment.target = factor(aggregated_data$compartment.target, levels = unique(compartment))
aggregated_data$classification.source.target = paste(aggregated_data$Functional.classification, aggregated_data$source, aggregated_data$target, sep = "--")

In [ ]:
# Plot datasets as is
# Plot differential signaling?!

In [86]:
aggregated_data

     Functional.classification    source             target
1    Cell Adhesion Molecule       Alpha              Alpha
2    Developmental Proteins       Alpha              Alpha
3    ECM Proteins                 Alpha              Alpha
4    Enzymes                      Alpha              Alpha
5    Growth Factors and Cytokines Alpha              Alpha
6    Hormones & Neuropeptides     Alpha              Alpha
7    Modulators                   Alpha              Alpha
8    Cell Adhesion Molecule       Beta               Alpha
9    Developmental Proteins       Beta               Alpha
10   ECM Proteins                 Beta               Alpha
11   Growth Factors and Cytokines Beta               Alpha
12   Hormones & Neuropeptides     Beta               Alpha
13   Modulators                   Beta               Alpha
14   Cell Adhesion Molecule       Delta              Alpha
15   Developmental Proteins       Delta              Alpha
16   ECM Proteins                 Delta              Alpha
17   Enzymes                      Delta              Alpha
18   Growth Factors and Cytokines Delta              Alpha
19   Hormones & Neuropeptides     Delta              Alpha
20   Cell Adhesion Molecule       Alpha              Beta
21   Developmental Proteins       Alpha              Beta
22   ECM Proteins                 Alpha              Beta
23   Enzymes                      Alpha              Beta
24   Growth Factors and Cytokines Alpha              Beta
25   Hormones & Neuropeptides     Alpha              Beta
26   Cell Adhesion Molecule       Beta               Beta
27   Developmental Proteins       Beta               Beta
28   ECM Proteins                 Beta               Beta
29   Growth Factors and Cytokines Beta               Beta
30   Hormones & Neuropeptides     Beta               Beta
⋮    ⋮                            ⋮                  ⋮
4587 Growth Factors and Cytokines Quiescent_Stellate Quiescent_Stellate
4588 Immune regulators            Quiescent_Stellate Quiescent_Stellate
4589 Modulators                   Quiescent_Stellate Quiescent_Stellate
4590 Cell Adhesion Molecule       Activated_Stellate Activated_Stellate
4591 Developmental Proteins       Activated_Stellate Activated_Stellate
4592 ECM Proteins                 Activated_Stellate Activated_Stellate
4593 Enzymes                      Activated_Stellate Activated_Stellate
4594 Growth Factors and Cytokines Activated_Stellate Activated_Stellate
4595 Hormones & Neuropeptides     Activated_Stellate Activated_Stellate
4596 Modulators                   Activated_Stellate Activated_Stellate
4597 Cell Adhesion Molecule       Quiescent_Stellate Activated_Stellate
4598 Developmental Proteins       Quiescent_Stellate Activated_Stellate
4599 ECM Proteins                 Quiescent_Stellate Activated_Stellate
4600 Enzymes                      Quiescent_Stellate Activated_Stellate
4601 Growth Factors and Cytokines Quiescent_Stellate Activated_Stellate
4602 Modulators                   Quiescent_Stellate Activated_Stellate
4603 Cell Adhesion Molecule       Activated_Stellate Quiescent_Stellate
4604 Complement System            Activated_Stellate Quiescent_Stellate
4605 Developmental Proteins       Activated_Stellate Quiescent_Stellate
4606 ECM Proteins                 Activated_Stellate Quiescent_Stellate
4607 Enzymes                      Activated_Stellate Quiescent_Stellate
4608 Growth Factors and Cytokines Activated_Stellate Quiescent_Stellate
4609 Immune regulators            Activated_Stellate Quiescent_Stellate
4610 Modulators                   Activated_Stellate Quiescent_Stellate
4611 Cell Adhesion Molecule       Quiescent_Stellate Quiescent_Stellate
4612 Developmental Proteins       Quiescent_Stellate Quiescent_Stellate
4613 ECM Proteins                 Quiescent_Stellate Quiescent_Stellate
4614 Growth Factors and Cytokines Quiescent_Stellate Quiescent_Stellate
4615 Immune regulators            Quiescent_Stellate Quiescent_Stellate
4616 Modulators                   Quiescent_Stellate Quiescent_Stellate
     condition compartment.source compartment.target prob
1    Aab       Endocrine          Endocrine          0.16098081135
2    Aab       Endocrine          Endocrine          0.01121850205
3    Aab       Endocrine          Endocrine          0.01798352315
4    Aab       Endocrine          Endocrine          0.00003752931
5    Aab       Endocrine          Endocrine          0.00232782120
6    Aab       Endocrine          Endocrine          0.03032926571
7    Aab       Endocrine          Endocrine          0.00003645492
8    Aab       Endocrine          Endocrine          0.14967617611
9    Aab       Endocrine          Endocrine          0.01446340781
10   Aab       Endocrine          Endocrine          0.00525998806
11   Aab       Endocrine          Endocrine          0.03859477556
12   Aab       Endocrine          Endocrine          0.02924831854
13   Aab       Endocrine          Endocrine          0.00003629168
14   Aab       Endocrine          Endocrine          0.15395654842
15   Aab       Endocrine          Endocrine          0.01469841570
16   Aab       Endocrine          Endocrine          0.01660744998
17   Aab       Endocrine          Endocrine          0.00006082344
18   Aab       Endocrine          Endocrine          0.01652167317
19   Aab       Endocrine          Endocrine          0.01056154160
20   Aab       Endocrine          Endocrine          0.17286331087
21   Aab       Endocrine          Endocrine          0.01050261728
22   Aab       Endocrine          Endocrine          0.00570934931
23   Aab       Endocrine          Endocrine          0.00012096574
24   Aab       Endocrine          Endocrine          0.00110451378
25   Aab       Endocrine          Endocrine          0.03986663142
26   Aab       Endocrine          Endocrine          0.19360211554
27   Aab       Endocrine          Endocrine          0.00992108500
28   Aab       Endocrine          Endocrine          0.00195168012
29   Aab       Endocrine          Endocrine          0.01345052831
30   Aab       Endocrine          Endocrine          0.01733562190
⋮    ⋮         ⋮                  ⋮                  ⋮
4587 T1D_early Stromal            Stromal            0.02580933743
4588 T1D_early Stromal            Stromal            0.00288996298
4589 T1D_early Stromal            Stromal            0.00169059277
4590 T1D_late  Stromal            Stromal            0.20219425655
4591 T1D_late  Stromal            Stromal            0.03544224007
4592 T1D_late  Stromal            Stromal            0.77950463439
4593 T1D_late  Stromal            Stromal            0.06359006484
4594 T1D_late  Stromal            Stromal            0.07497594880
4595 T1D_late  Stromal            Stromal            0.00005142067
4596 T1D_late  Stromal            Stromal            0.00255143897
4597 T1D_late  Stromal            Stromal            0.04687924676
4598 T1D_late  Stromal            Stromal            0.00831055318
4599 T1D_late  Stromal            Stromal            0.23377584049
4600 T1D_late  Stromal            Stromal            0.01799175481
4601 T1D_late  Stromal            Stromal            0.05015393070
4602 T1D_late  Stromal            Stromal            0.00100015415
4603 T1D_late  Stromal            Stromal            0.04808571751
4604 T1D_late  Stromal            Stromal            0.00055330827
4605 T1D_late  Stromal            Stromal            0.02946956289
4606 T1D_late  Stromal            Stromal            0.70137599510
4607 T1D_late  Stromal            Stromal            0.03761758946
4608 T1D_late  Stromal            Stromal            0.06323839585
4609 T1D_late  Stromal            Stromal            0.00003855107
4610 T1D_late  Stromal            Stromal            0.00296056132
4611 T1D_late  Stromal            Stromal            0.01111317045
4612 T1D_late  Stromal            Stromal            0.02235114919
4613 T1D_late  Stromal            Stromal            0.19931363794
4614 T1D_late  Stromal            Stromal            0.02367005712
4615 T1D_late  Stromal            Stromal            0.00224382816
4616 T1D_late  Stromal            Stromal            0.00118157718
     prob.norm         condition.size
1    0.000005862588272 27459
2    0.000000408554647 27459
3    0.000000654922727 27459
4    0.000000001366740 27459
5    0.000000084774435 27459
6    0.000001104529142 27459
7    0.000000001327613 27459
8    0.000005450896832 27459
9    0.000000526727405 27459
10   0.000000191557888 27459
11   0.000001405541919 27459
12   0.000001065163281 27459
13   0.000000001321668 27459
14   0.000005606779141 27459
15   0.000000535285906 27459
16   0.000000604808987 27459
17   0.000000002215064 27459
18   0.000000601685173 27459
19   0.000000384629506 27459
20   0.000006295324333 27459
21   0.000000382483604 27459
22   0.000000207922696 27459
23   0.000000004405322 27459
24   0.000000040224108 27459
25   0.000001451860280 27459
26   0.000007050588715 27459
27   0.000000361305401 27459
28   0.000000071076154 27459
29   0.000000489840428 27459
30   0.000000631327503 27459
⋮    ⋮                 ⋮
4587 0.000001419733617 18179
4588 0.000000158972605 18179
4589 0.000000092997017 18179
4590 0.000013594719058 14873
4591 0.000002382992003 14873
4592 0.000052410719719 14873
4593 0.000004275537204 14873
4594 0.000005041077711 14873
4595 0.000000003457317 14873
4596 0.000000171548374 14873
4597 0.000003151969795 14873
4598 0.000000558767779 14873
4599 0.000015718136253 14873
4600 0.000001209692383 14873
4601 0.000003372146218 14873
4602 0.000000067246295 14873
4603 0.000003233087979 14873
4604 0.000000037202197 14873
4605 0.000001981413494 14873
4606 0.000047157667928 14873
4607 0.000002529253645 14873
4608 0.000004251892412 14873
4609 0.000000002592017 14873
4610 0.000000199056096 14873
4611 0.000000747204360 14873
4612 0.000001502800322 14873
4613 0.000013401037984 14873
4614 0.000001591478324 14873
4615 0.000000150865875 14873
4616 0.000000079444442 14873
     classification.source.target
1    Cell Adhesion Molecule--Alpha--Alpha
2    Developmental Proteins--Alpha--Alpha
3    ECM Proteins--Alpha--Alpha
4    Enzymes--Alpha--Alpha
5    Growth Factors and Cytokines--Alpha--Alpha
6    Hormones & Neuropeptides--Alpha--Alpha
7    Modulators--Alpha--Alpha
8    Cell Adhesion Molecule--Beta--Alpha
9    Developmental Proteins--Beta--Alpha
10   ECM Proteins--Beta--Alpha
11   Growth Factors and Cytokines--Beta--Alpha
12   Hormones & Neuropeptides--Beta--Alpha
13   Modulators--Beta--Alpha
14   Cell Adhesion Molecule--Delta--Alpha
15   Developmental Proteins--Delta--Alpha
16   ECM Proteins--Delta--Alpha
17   Enzymes--Delta--Alpha
18   Growth Factors and Cytokines--Delta--Alpha
19   Hormones & Neuropeptides--Delta--Alpha
20   Cell Adhesion Molecule--Alpha--Beta
21   Developmental Proteins--Alpha--Beta
22   ECM Proteins--Alpha--Beta
23   Enzymes--Alpha--Beta
24   Growth Factors and Cytokines--Alpha--Beta
25   Hormones & Neuropeptides--Alpha--Beta
26   Cell Adhesion Molecule--Beta--Beta
27   Developmental Proteins--Beta--Beta
28   ECM Proteins--Beta--Beta
29   Growth Factors and Cytokines--Beta--Beta
30   Hormones & Neuropeptides--Beta--Beta
⋮    ⋮
4587 Growth Factors and Cytokines--Quiescent_Stellate--Quiescent_Stellate
4588 Immune regulators--Quiescent_Stellate--Quiescent_Stellate
4589 Modulators--Quiescent_Stellate--Quiescent_Stellate
4590 Cell Adhesion Molecule--Activated_Stellate--Activated_Stellate
4591 Developmental Proteins--Activated_Stellate--Activated_Stellate
4592 ECM Proteins--Activated_Stellate--Activated_Stellate
4593 Enzymes--Activated_Stellate--Activated_Stellate
4594 Growth Factors and Cytokines--Activated_Stellate--Activated_Stellate
4595 Hormones & Neuropeptides--Activated_Stellate--Activated_Stellate
4596 Modulators--Activated_Stellate--Activated_Stellate
4597 Cell Adhesion Molecule--Quiescent_Stellate--Activated_Stellate
4598 Developmental Proteins--Quiescent_Stellate--Activated_Stellate
4599 ECM Proteins--Quiescent_Stellate--Activated_Stellate
4600 Enzymes--Quiescent_Stellate--Activated_Stellate
4601 Growth Factors and Cytokines--Quiescent_Stellate--Activated_Stellate
4602 Modulators--Quiescent_Stellate--Activated_Stellate
4603 Cell Adhesion Molecule--Activated_Stellate--Quiescent_Stellate
4604 Complement System--Activated_Stellate--Quiescent_Stellate
4605 Developmental Proteins--Activated_Stellate--Quiescent_Stellate
4606 ECM Proteins--Activated_Stellate--Quiescent_Stellate
4607 Enzymes--Activated_Stellate--Quiescent_Stellate
4608 Growth Factors and Cytokines--Activated_Stellate--Quiescent_Stellate
4609 Immune regulators--Activated_Stellate--Quiescent_Stellate
4610 Modulators--Activated_Stellate--Quiescent_Stellate
4611 Cell Adhesion Molecule--Quiescent_Stellate--Quiescent_Stellate
4612 Developmental Proteins--Quiescent_Stellate--Quiescent_Stellate
4613 ECM Proteins--Quiescent_Stellate--Quiescent_Stellate
4614 Growth Factors and Cytokines--Quiescent_Stellate--Quiescent_Stellate
4615 Immune regulators--Quiescent_Stellate--Quiescent_Stellate
4616 Modulators--Quiescent_Stellate--Quiescent_Stellate

In [ ]:
# flow chart sample data
plot.data = LR.data.consensus.sig.thresh %>% 
    dplyr::filter(condition == condition.ls[3]) %>%
    dplyr::mutate(interaction.group = paste(source, Functional.classification, target, sep = "--")) %>%
    dplyr::group_by(interaction.group) %>%
    dplyr::summarize(prob.norm = sum(prob, na.rm = TRUE) / first(condition.size)) %>%
    dplyr::mutate(source = str_split_fixed(interaction.group, "--", 3)[,1],
                            classification = str_split_fixed(interaction.group, "--", 3)[,2],
                            target = str_split_fixed(interaction.group, "--", 3)[,3],
                            logFDR = 1) %>% 
              dplyr::ungroup()